import { create } from 'zustand';
import { persist } from 'zustand/middleware';

interface LanguageState {
  language: 'zh' | 'en' | 'ja';
  setLanguage: (lang: 'zh' | 'en' | 'ja') => void;
  t: (key: string) => string;
}

export const translations: Record<string, { zh: string; en: string; ja: string }> = {
  // AUTH namespace
  'auth.access_password': { zh: '访问密码', en: 'Password', ja: 'パスワード' },
  'auth.and': { zh: '与', en: 'and', ja: 'および' },
  'auth.back_to_login': { zh: '返回登录', en: 'Back to Login', ja: 'ログインに戻る' },
  'auth.create_account': { zh: '创建账号', en: 'Create Account', ja: 'アカウント作成' },
  'auth.email': { zh: '邮箱地址', en: 'Email Address', ja: 'メールアドレス' },
  'auth.email_tab': { zh: '邮箱账号', en: 'Email Account', ja: 'メールアカウント' },
  'auth.enter_otp': { zh: '请输入验证码', en: 'Enter OTP', ja: 'OTPを入力' },
  'auth.forgot_pwd': { zh: '忘记密码？', en: 'Forgot Password?', ja: 'パスワードを忘れた？' },
  'auth.get_otp': { zh: '获取验证码', en: 'Get OTP', ja: 'OTPを取得' },
  'auth.get_otp_first': { zh: '请先获取验证码', en: 'Get OTP first', ja: '先にOTPを取得' },
  'auth.has_account': { zh: '已有账号？点击登录', en: 'Have an account? Login', ja: 'アカウントがある？ログイン' },
  'auth.invite_bonus': { zh: '双方均得奖励', en: 'Both get rewards', ja: '両方が報酬を受け取る' },
  'auth.invite_code': { zh: '邀请码 (选填)', en: 'Invite Code (optional)', ja: '招待コード (任意)' },
  'auth.invite_placeholder': { zh: '请输入邀请码 (选填)', en: 'Enter invite code (optional)', ja: '招待コードを入力 (任意)' },
  'auth.join_community': { zh: '加入民主化音乐社区，共享创作收益', en: 'Join the democratized music community, share creative earnings', ja: '民主化された音楽コミュニティに参加し、クリエイティブ収益を共有' },
  'auth.join_echorura': { zh: '开启 ECHORURA', en: 'Join ECHORURA', ja: 'ECHORURAに参加' },
  'auth.logging_in': { zh: '正在登录...', en: 'Logging in...', ja: 'ログイン中...' },
  'auth.login_now': { zh: '立即登录', en: 'Login Now', ja: '今すぐログイン' },
  'auth.login_or_register': { zh: '立即登录', en: 'Login', ja: 'ログイン' },
  'auth.new_password': { zh: '设置新密码 (不低于6位)', en: 'New Password (min 6 chars)', ja: '新しいパスワード (6文字以上)' },
  'auth.no_account': { zh: '还没有账号？点击注册', en: 'Don\'t have an account? Sign up', ja: 'アカウントがない？登録する' },
  'auth.password': { zh: '登录密码', en: 'Password', ja: 'パスワード' },
  'auth.phone_login': { zh: '手机号登录', en: 'Phone Login', ja: '電話番号でログイン' },
  'auth.phone_login_desc': { zh: '使用手机号与密码登录极声', en: 'Login with phone number and password', ja: '電話番号とパスワードでログイン' },
  'auth.phone_number': { zh: '手机号码', en: 'Phone Number', ja: '電話番号' },
  'auth.phone_recover_desc': { zh: '填写手机号并验证以重置密码', en: 'Enter phone number and verify to reset password', ja: '電話番号を入力して確認しパスワードをリセット' },
  'auth.phone_register': { zh: '手机号注册', en: 'Phone Register', ja: '電話番号で登録' },
  'auth.phone_register_desc': { zh: '填写手机号与密码，获取验证码激活', en: 'Enter phone number and password, get OTP to activate', ja: '電話番号とパスワードを入力してOTPを取得' },
  'auth.phone_tab': { zh: '手机号账号', en: 'Phone Account', ja: '電話番号アカウント' },
  'auth.recover_pwd': { zh: '找回密码', en: 'Recover Password', ja: 'パスワード回復' },
  'auth.register_now': { zh: '立即注册', en: 'Register Now', ja: '今すぐ登録' },
  'auth.registering': { zh: '注册中...', en: 'Registering...', ja: '登録中...' },
  'auth.resend_countdown': { zh: 's 后重新获取', en: 's to resend', ja: '秒後に再送信' },
  'auth.reset_login': { zh: '重置密码并登录', en: 'Reset & Login', ja: 'リセットしてログイン' },
  'auth.resetting': { zh: '重置中...', en: 'Resetting...', ja: 'リセット中...' },
  'auth.set_password': { zh: '自设密码 (不低于6位)', en: 'Set Password (min 6 chars)', ja: 'パスワード設定 (6文字以上)' },
  'auth.sms_code': { zh: '短信验证码', en: 'SMS Code', ja: 'SMS認証コード' },
  'auth.terms_agree': { zh: '注册即代表您同意', en: 'By registering you agree to the', ja: '登録することで以下に同意します：' },
  'auth.welcome_back': { zh: '欢迎回来', en: 'Welcome Back', ja: 'おかえりなさい' },
  'auth.or_continue_with': { zh: '或者使用以下方式继续', en: 'Or continue with', ja: 'または以下で続行' },

  // COMMON namespace
  'common.cancel': { zh: '取消', en: 'Cancel', ja: 'キャンセル' },
  'common.confirm': { zh: '确认', en: 'Confirm', ja: '確認' },
  'common.just_now': { zh: '刚刚', en: 'Just now', ja: 'たった今' },
  'common.login_required': { zh: '请先登录', en: 'Please log in first', ja: '先にログインしてください' },
  'common.me': { zh: '我', en: 'Me', ja: '自分' },

  // COMMUNITY namespace
  'community.assembly': { zh: '议事厅', en: 'Assembly', ja: '議事堂' },
  'community.desc': { zh: '民主决策、创作共鸣与权益交易的枢纽中心', en: 'Hub for democratic decisions, creative resonance and equity trading', ja: '民主的決定、創作の共鳴、株式取引のハブセンター' },
  'community.empty': { zh: '荒野之中，虚位以待... 成为第一个发言的人吧！', en: 'No posts yet. Be the first to speak!', ja: 'まだ投稿はありません。最初に投稿しましょう！' },
  'community.equity_distributed': { zh: '权益已分发', en: 'Equity Distributed', ja: '権益配布済み' },
  'community.equity_sold': { zh: '% 权益售出', en: '% equity sold', ja: '% 権益売却' },
  'community.ipo_progress': { zh: 'IPO 进度', en: 'IPO Progress', ja: 'IPO 進捗' },
  'community.login_btn': { zh: '立即登录', en: 'Log In Now', ja: '今すぐログイン' },
  'community.login_only': { zh: '仅限已登录用户发表', en: 'Logged-in users only', ja: 'ログインユーザーのみ投稿可能' },
  'community.login_placeholder': { zh: '只有登录后才能发表动态，快去登录吧！', en: 'Please log in to post updates.', ja: 'ログインすると投稿できます。' },
  'community.market': { zh: '市场', en: 'Market', ja: 'マーケット' },
  'community.no_comments': { zh: '荒野之中，虚位以待... 来抢沙发吧！', en: 'No comments yet. Be the first!', ja: 'まだコメントはありません。最初に！' },
  'community.placeholder_assembly': { zh: '发起一个民主提案...', en: 'Propose a democratic initiative...', ja: '民主的な提案を発議...' },
  'community.placeholder_square': { zh: '分享你的创作灵感...', en: 'Share your creative inspiration...', ja: '創作のインスピレーションを共有...' },
  'community.post': { zh: '发布动态', en: 'Post', ja: '投稿' },
  'community.publish': { zh: '发布动态', en: 'Publish Post', ja: '投稿する' },
  'community.publishing': { zh: '发布中...', en: 'Publishing...', ja: '投稿中...' },
  'community.raising': { zh: '正在募集', en: 'Raising', ja: '募集中' },
  'community.reply': { zh: '回复讨论', en: 'Reply', ja: '返信' },
  'community.reply_login': { zh: '登录后即可参与讨论...', en: 'Login to join the discussion...', ja: 'ログインして議論に参加...' },
  'community.reply_placeholder': { zh: '写下你的回复...', en: 'Write a reply...', ja: '返信を書く...' },
  'community.send': { zh: '发送', en: 'Send', ja: '送信' },
  'community.sending': { zh: '发送中...', en: 'Sending...', ja: '送信中...' },
  'community.shares_left_c': { zh: '剩余', en: 'Left', ja: '残り' },
  'community.square': { zh: '广场', en: 'Square', ja: '広場' },
  'community.title': { zh: 'ECHORURA 社区', en: 'ECHORURA Community', ja: 'ECHORURAコミュニティ' },

  // COMPLIANCE namespace
  'compliance.app_name_global': { zh: '极声音乐 Global', en: 'ECHORURA Global', ja: 'ECHORURA Global' },
  'compliance.app_name_hk': { zh: '极声音乐 (ECHORURA HK)', en: 'ECHORURA HK', ja: 'ECHORURA HK' },
  'compliance.app_name_sg': { zh: 'ECHORURA SG', en: 'ECHORURA SG', ja: 'ECHORURA SG' },
  'compliance.equity_global': { zh: '版权股权 (Music Equity)', en: 'Music Equity', ja: '音楽著作権持分' },
  'compliance.equity_hk': { zh: '共创共享权益', en: 'Co-Curation Equity', ja: '共創共有持分' },
  'compliance.equity_sg': { zh: '粉丝成就徽章 (Fan Badges)', en: 'Fan Badges', ja: 'ファンバッジ' },
  'compliance.fiat_exchange_rate_global': { zh: '1.00 USD = 10.00 ECHO 代币', en: '1.00 USD = 10.00 ECHO Token', ja: '1.00 USD = 10.00 ECHOトークン' },
  'compliance.fiat_exchange_rate_hk': { zh: '10.00 HKD = 10.00 ECHO 社区积分', en: '10.00 HKD = 10.00 ECHO Community Points', ja: '10.00 HKD = 10.00 ECHOコミュニティポイント' },
  'compliance.fiat_exchange_rate_sg': { zh: '1.50 SGD = 10.00 ECHO 代币', en: '1.50 SGD = 10.00 ECHO Token', ja: '1.50 SGD = 10.00 ECHOトークン' },
  'compliance.token_global': { zh: 'ECHO Token', en: 'ECHO Token', ja: 'ECHOトークン' },
  'compliance.token_hk': { zh: 'ECHO 社区积分', en: 'ECHO Community Points', ja: 'ECHOコミュニティポイント' },
  'compliance.token_sg': { zh: 'ECHO Token', en: 'ECHO Token', ja: 'ECHOトークン' },

  // DISCOVER namespace
  'discover.add_playlist': { zh: '收录到歌单', en: 'Add to Playlist', ja: 'プレイリストに追加' },
  'discover.ai_pass': { zh: 'AI 首性质检通过', en: 'AI Quality Check Passed', ja: 'AI品質チェック通過' },
  'discover.ai_score': { zh: 'AI 评分:', en: 'AI Score:', ja: 'AIスコア：' },
  'discover.all_qualify': { zh: '🛡️ 全员上榜', en: '🛡️ All qualify', ja: '🛡️ 全員通過' },
  'discover.arena': { zh: '听审竞技场', en: 'Curation Arena', ja: 'キュレーションアリーナ' },
  'discover.arena_title': { zh: '听审竞技场', en: 'Curation Arena', ja: 'キュレーションアリーナ' },
  'discover.artist_label': { zh: '艺人:', en: 'Artist:', ja: 'アーティスト：' },
  'discover.clear_filters': { zh: '清除所有筛选', en: 'Clear All Filters', ja: 'すべてのフィルターをクリア' },
  'discover.creator_channel': { zh: '创作者极速报名通道 (Creator Registration Channel)', en: 'Creator Fast-Register Channel', ja: 'クリエイター高速登録通道' },
  'discover.dao_badge': { zh: 'DAO 社区听审投票机制', en: 'DAO Community Curation', ja: 'DAOコミュニティキュレーション' },
  'discover.dashboard': { zh: '本轮对决数值仪表盘', en: 'Round Dashboard', ja: 'ラウンドダッシュボード' },
  'discover.day1_desc': { zh: '当前处于「质押报名期」。创作者可质押 10.00 ECHO 为自己的原创歌曲报名参赛。每日参赛限制前 20 首。报名成功的作品将于今晚 24:00 自动进入投票环节。', en: 'Currently in Registration Day. Creators stake 10 ECHO to enter. Daily limit: 20 songs. Registered songs enter voting at midnight.', ja: '現在登録期間中。クリエイターは10 ECHOをステークして参加可能。1日制限：20曲。登録曲は深夜0時に投票フェーズに移行。' },
  'discover.day1_label': { zh: '今日质押报名期', en: 'Today: Registration Day', ja: '今日：登録日' },
  'discover.day2_desc': { zh: '以下歌曲今日开放公众投票。每位用户可对每首歌曲进行一次「支持」或「反对」打分。当日 24:00 截止，得票最多的前10首将晋级首页推荐！', en: 'Songs below are open for public voting. Each user can vote once per song. Deadline: midnight. Top 10 will be featured on the homepage!', ja: '以下の曲が一般投票に公開されています。各ユーザーは1曲につき1回投票可能。締切：深夜0時。上位10曲がホームページに掲載！' },
  'discover.day2_label': { zh: '今日待投票金曲', en: 'Today: Voting Day', ja: '今日：投票日' },
  'discover.day3_desc': { zh: '✅ 今日投票已于 24:00 截止。本批次结算完成，胜出曲目已同步至首页「今日推荐榜」。感谢所有参与投票的听审会员！', en: '✅ Voting closed at midnight. Results settled. Winners synced to homepage. Thank you all voters!', ja: '✅ 投票は深夜0時に締め切られました。結果確定。勝者はホームページに表示。ありがとう！' },
  'discover.day3_label': { zh: '今日已结算榜单', en: 'Today: Results Day', ja: '今日：結果発表' },
  'discover.deadline': { zh: '截止: 当日 24:00', en: 'Deadline: Midnight', ja: '締切：深夜0時' },
  'discover.default_playlist_desc': { zh: '由极声共创创作者精选分享的声学合辑。', en: 'A curated acoustic collection by ECHORURA co-creators.', ja: 'ECHORURAの共同クリエイターがキュレーションしたアコースティックコレクション。' },
  'discover.echorura_user': { zh: '极声用户', en: 'ECHORURA User', ja: 'ECHORURAユーザー' },
  'discover.genre': { zh: '音乐风格 (Genre)', en: 'Music Genre', ja: '音楽ジャンル' },
  'discover.genre_cyber': { zh: '赛博', en: 'Cyber', ja: 'サイバー' },
  'discover.genre_joy': { zh: '喜悦', en: 'Joy', ja: '喜び' },
  'discover.genre_party': { zh: '派对', en: 'Party', ja: 'パーティー' },
  'discover.genre_pop': { zh: '流行', en: 'Pop', ja: 'ポップ' },
  'discover.goto_profile': { zh: '前往个人中心发布并质押报名', en: 'Go to Profile to publish & register', ja: 'プロフィールで公開して登録する' },
  'discover.live_duels': { zh: '🔥 本日待投票对决金曲 (Live Voting Duels)', en: '🔥 Today\'s Live Voting Duels', ja: '🔥 本日の投票対決曲' },
  'discover.loser_msg': { zh: '🔽 抱歉落榜淘汰：未能杀入本批次前 10。作品以普通身份上架曲库；您的 10.00 ECHO 保证金已被收回充公，作为伯乐奖励均分给了参与投票的听审会员。', en: '🔽 Not qualified: Did not make top 10. Song listed normally. 10 ECHO stake forfeited and split among voters.', ja: '🔽 不通過：上位10入りならず。曲は通常掲載。10 ECHOのステークは没収され投票者に均等分配。' },
  'discover.loser_settled': { zh: '已结算：淘汰未通过', en: 'Settled: Eliminated', ja: '決済済み：脱落' },
  'discover.main_stage': { zh: '探索主舞台', en: 'Main Stage', ja: 'メインステージ' },
  'discover.no_duel': { zh: '🔘 暂无对决', en: '🔘 No duels', ja: '🔘 対決なし' },
  'discover.no_duel_desc': { zh: '今日暂无处于对决中的听审曲目。每日 0:00 会将报名的歌曲自动转移至此进行投票！', en: 'No songs in duel today. Songs are moved here automatically at midnight!', ja: '本日対決中の曲はありません。登録曲は毎日深夜0時に自動的にここに移行します！' },
  'discover.no_duel_songs': { zh: '暂无对决作品', en: 'No duel songs', ja: '対決曲なし' },
  'discover.no_playlists': { zh: '🌌 暂未发掘到公开的精选推荐歌单', en: '🌌 No featured playlists found yet', ja: '🌌 おすすめプレイリストはまだありません' },
  'discover.no_results': { zh: '暂时没有找到匹配的作品，换个心情试试？', en: 'No matching songs found, try another mood?', ja: '一致する曲が見つかりません。別のムードを試してください？' },
  'discover.no_songs': { zh: '暂无歌曲', en: 'No Songs', ja: '曲なし' },
  'discover.no_songs_to_register': { zh: '您当前没有待报名的原创歌曲。上传并发布您的第一首原创歌曲（或等今日报名期结束后明天再投），即可在此通道质押 10.00 ECHO 报名参赛！', en: 'No songs ready to register. Upload your first original song (or try again tomorrow after registration closes) and stake 10 ECHO to compete!', ja: '登録可能な曲はありません。最初のオリジナル曲をアップロード（または本日の登録終了後に明日再試行）し、10 ECHOをステークして競争に参加！' },
  'discover.pending': { zh: '⚠️ 待定', en: '⚠️ Pending', ja: '⚠️ 保留中' },
  'discover.play_count': { zh: '次收听', en: 'plays', ja: '再生' },
  'discover.playlists': { zh: '精选推荐歌单 (Featured Playlists)', en: 'Featured Playlists', ja: 'おすすめプレイリスト' },
  'discover.protect_msg': { zh: '🛡️ 保护机制生效：本批次不足 10 首，作品无淘汰成功晋级首页「本日推荐榜」！根据 DAO 协议，您的 10.00 ECHO 保证金已转为社区伯乐激励均分给听审员。', en: '🛡️ Protection active: Fewer than 10 songs this round, all qualify for homepage! Per DAO protocol, your 10 ECHO stake is split among voters as reward.', ja: '🛡️ 保護発動：今回は10曲未満のため全曲がホームページに掲載！DAOプロトコルに従い、10 ECHOのステークは投票者に均等分配。' },
  'discover.qualified': { zh: '✅ 上榜圈', en: '✅ Qualified', ja: '✅ 通過' },
  'discover.queue_empty_desc': { zh: '今日还没有任何作品报名听审竞技场。赶快成为首个发起质押报名的创作者吧！', en: 'No songs registered today. Be the first creator to stake and register!', ja: '本日登録された曲はありません。最初にステークして登録するクリエイターになりましょう！' },
  'discover.queue_empty_title': { zh: '今日报名队列为空', en: 'Registration queue is empty', ja: '登録キューは空です' },
  'discover.queue_full': { zh: '当前已满:', en: 'Currently full:', ja: '現在満員：' },
  'discover.queue_locked_msg': { zh: '🔒 队列锁定中：该作品已成功完成质押排队。每天 0:00 将会自动转移到上方对决投票区开启 24 小时公开听审。', en: '🔒 Queued: Song staked successfully. It will move to the voting area at midnight for 24h public curation.', ja: '🔒 キュー中：曲のステーク完了。毎日深夜0時に投票エリアに移動し24時間の公開キュレーションが始まります。' },
  'discover.queue_status': { zh: '报名队列状态:', en: 'Queue Status:', ja: 'キュー状態：' },
  'discover.queue_title': { zh: '🔒 今日已报名待流转队列 (Registered Queue)', en: '🔒 Today\'s Registered Queue', ja: '🔒 本日登録済みキュー' },
  'discover.queued': { zh: '🔒 排队中', en: '🔒 Queued', ja: '🔒 キュー中' },
  'discover.rank_rule': { zh: '上榜规则:', en: 'Ranking Rule:', ja: 'ランキングルール：' },
  'discover.settled': { zh: '🏆 往期对决已结算金曲 (Previous Settled Winners)', en: '🏆 Previous Settled Winners', ja: '🏆 過去の決済勝者' },
  'discover.sink': { zh: '下沉 (Down)', en: 'Sink (Down)', ja: '沈める (Down)' },
  'discover.songs_count': { zh: '首歌曲', en: 'songs', ja: '曲' },
  'discover.songs_today': { zh: '今日待决金曲:', en: 'Today\'s Songs:', ja: '今日の曲数：' },
  'discover.soul_state': { zh: '灵魂状态 (Soul State)', en: 'Soul State', ja: 'ソウルステート' },
  'discover.stake_locked': { zh: '10.00 ECHO 质押锁仓中 🔒', en: '10.00 ECHO Staked & Locked 🔒', ja: '10.00 ECHO ステーク＆ロック中 🔒' },
  'discover.stake_register': { zh: '💎 质押 10 ECHO 报名参赛', en: '💎 Stake 10 ECHO to Register', ja: '💎 10 ECHOをステークして登録' },
  'discover.staking': { zh: '正在质押报名...', en: 'Staking...', ja: 'ステーク中...' },
  'discover.support': { zh: '支持 (Up)', en: 'Support (Up)', ja: 'サポート (Up)' },
  'discover.support_votes': { zh: '支持得票:', en: 'Support Votes:', ja: 'サポート票数：' },
  'discover.top10': { zh: '🔥 前10首上榜', en: '🔥 Top 10 qualify', ja: '🔥 上位10曲通過' },
  'discover.voted': { zh: '已打分', en: 'Voted', ja: '投票済み' },
  'discover.votes': { zh: '票', en: 'votes', ja: '票' },
  'discover.voting_closed': { zh: '🔒 投票已截止', en: '🔒 Voting Closed', ja: '🔒 投票終了' },
  'discover.waiting_duel': { zh: '等待明日对决', en: 'Awaiting Tomorrow\'s Duel', ja: '明日の対決を待機中' },
  'discover.waiting_transfer': { zh: '等待明日 0:00 流转开启对决', en: 'Waiting for midnight to start duel', ja: '深夜0時の対決開始を待機中' },
  'discover.winner_msg': { zh: '🏆 竞选挑战成功：歌曲在激烈比拼中挺进前 10！已自动登上极声主页「今日推荐榜」黄金资源位，且 10.00 ECHO 保证金全额退还！', en: '🏆 Challenge success: Song made top 10! Featured on homepage & 10 ECHO stake refunded!', ja: '🏆 挑戦成功：曲が上位10入り！ホームページに掲載、10 ECHOのステークも返還！' },
  'discover.winner_settled': { zh: '已结算：晋级上榜', en: 'Settled: Promoted', ja: '決済済み：昇格' },

  // GENRE namespace
  'genre.acg': { zh: '二次元', en: 'ACG', ja: 'アニメ・ゲーム' },
  'genre.alternative': { zh: '另类独立', en: 'Alternative', ja: 'オルタナティブ' },
  'genre.ambient': { zh: '氛围放松', en: 'Ambient', ja: 'アンビエント' },
  'genre.china': { zh: '国风', en: 'Chinese Style', ja: '中国風' },
  'genre.classical': { zh: '古典', en: 'Classical', ja: 'クラシック' },
  'genre.electro': { zh: '电子舞曲', en: 'Electronic', ja: 'エレクトロ' },
  'genre.folk': { zh: '民谣', en: 'Folk', ja: 'フォーク' },
  'genre.hiphop': { zh: '嘻哈', en: 'Hip-Hop', ja: 'ヒップホップ' },
  'genre.jazz': { zh: '爵士', en: 'Jazz', ja: 'ジャズ' },
  'genre.pop': { zh: '流行', en: 'Pop', ja: 'ポップ' },
  'genre.rock': { zh: '摇滚', en: 'Rock', ja: 'ロック' },
  'genre.soul': { zh: '灵魂乐', en: 'Soul', ja: 'ソウル' },
  'genre.soundtrack': { zh: '影视原声', en: 'Soundtrack', ja: 'サウンドトラック' },

  // HERO namespace
  'hero.desc': { 
    zh: 'ECHORURA是基于WEB3技术的去中心化音乐社区。在 ECHORURA，创作与收听都是在挖掘价值。让音乐回归民众，让收益归于听众与创作者。', 
    en: 'ECHORURA is a decentralized music community based on Web3 technology. At ECHORURA, both creation and listening are mining value. Return music to the people, and rewards to listeners and creators.', 
    ja: 'ECHORURAはWeb3技術に基づいた分散型音楽コミュニティです。ECHORURAでは、創作とリスニングの両方が価値をマイニングしています。音楽を人々に返し、報酬をリスナーとクリエイターに還元します。' 
  },
  'hero.ipo_info': { zh: '共创音乐市集', en: 'Co-Curation Market', ja: 'マーケットへ' },
  'hero.start': { zh: '开启音乐之旅', en: 'Start Music Journey', ja: '音楽の旅を始める' },
  'hero.title': { zh: '创作与收听，皆为价值', en: 'CREATION & LISTENING, ALL ARE VALUE', ja: '創作とリスニング、すべてに価値がある' },

  // HOME namespace
  'home.creator_fans': { zh: '近期粉丝: +', en: 'New Fans: +', ja: '新規ファン: +' },
  'home.creator_score': { zh: '热度:', en: 'Score:', ja: 'スコア:' },
  'home.dao_badge': { zh: '🏆 DAO 听审认证', en: '🏆 DAO Certified', ja: '🏆 DAO 公認' },
  'home.empty_arena': { zh: '今日听审擂台暂无胜出金曲，快去发现页投票，或者上传你的歌曲吧！', en: 'No winners in today\'s Arena yet. Go vote on Discover, or upload your song!', ja: '今日のアリーナにはまだ勝者がいません。発見ページで投票するか、あなたの曲をアップロードしましょう！' },
  'home.empty_hot': { zh: '当前还没有热播歌曲，上传您的音乐开启播放收益吧！', en: 'No hot plays yet. Upload your music to start earning!', ja: '急上昇曲はまだありません。音楽をアップロードして収益を得ましょう！' },
  'home.empty_join': { zh: '等你加入', en: 'Be the First!', ja: 'あなたが最初に！' },
  'home.empty_new': { zh: '当前暂无新发布歌曲，上传并分享您的第一首原创音乐！', en: 'No new releases yet. Upload and share your first original music!', ja: '新着リリースはまだありません。最初のオリジナル音楽をアップロードして共有しましょう！' },
  'home.empty_trending': { zh: '当前没有被发现的歌曲，快去上传第一首吧！', en: 'No trending songs yet. Upload the first one!', ja: 'トレンド曲はまだありません。最初の曲をアップロードしましょう！' },
  'home.follow': { zh: '关注', en: 'Follow', ja: 'フォロー' },
  'home.hot_plays': { zh: '本日热播 TOP10', en: 'Today\'s Hot Plays TOP10', ja: '本日急上昇 TOP10' },
  'home.new_releases': { zh: '新歌速递', en: 'New Releases', ja: '新着リリース' },
  'home.play_count': { zh: '次收听', en: 'plays', ja: '再生' },
  'home.rising_artists': { zh: '新锐艺人 TOP10', en: 'Rising Artists TOP10', ja: '急上昇アーティスト TOP10' },
  'home.stat_active_nodes': { zh: '活跃创作者节点', en: 'Active Creator Nodes', ja: 'アクティブクリエイターノード' },
  'home.stat_community_share': { zh: '社区分润率', en: 'Community Revenue Share', ja: 'コミュニティ収益分配率' },
  'home.stat_decentralized': { zh: '● 去中心化节点认证', en: '● Decentralized Node Certified', ja: '● 分散型ノード認証' },
  'home.stat_listen_rewards': { zh: '全网累计收听奖励', en: 'Total Listen Rewards', ja: '累計リスニング報酬' },
  'home.stat_profit_back': { zh: '● 100% 利润社区回馈', en: '● 100% Profit Returned to Community', ja: '● 100% 利益をコミュニティに還元' },
  'home.stat_smart_contract': { zh: '● 智能合约实时结算', en: '● Smart Contract Settlement', ja: '● スマートコントラクト決済' },
  'home.top_picks': { zh: '本日推荐金曲 TOP10', en: 'Today\'s Top Picks', ja: '本日おすすめ TOP10' },
  'home.trending': { zh: '热门发现', en: 'Trending Discoveries', ja: 'トレンド発見' },
  'home.unknown_creator': { zh: '极声创作者', en: 'ECHORURA Creator', ja: 'ECHORURAクリエイター' },
  'home.view_all': { zh: '查看全部 →', en: 'View All →', ja: '全て見る →' },
  'home.visit_profile': { zh: '去主页关注', en: 'Visit Profile', ja: 'プロフィールを見る' },

  // MARKET namespace
  'market.aa_wallet_balance': { zh: '您的 AA 智能钱包余额', en: 'Your AA Smart Wallet Balance', ja: 'AAスマートウォレット残高' },
  'market.active_ipos': { zh: '正在募集中', en: 'Active IPOs', ja: '募集中' },
  'market.available_credit': { zh: '当前可用', en: 'Available Credit', ja: '現在の利用可能額' },
  'market.co_creation_market': { zh: '共创共享市集', en: 'Co-Curation Market', ja: '共創マーケット' },
  'market.confirm_curation_support': { zh: '确认参与共创共享', en: 'Confirm Curation Support', ja: '共同制作支援を確定する' },
  'market.confirm_support': { zh: '确认支持', en: 'Confirm Support', ja: '支援を確認' },
  'market.cost_per_share': { zh: '单价', en: 'Price per Share', ja: '単価/シェア' },
  'market.curation_payment': { zh: '共创支持付款', en: 'Curation Payment', ja: '共創支援支払い' },
  'market.curation_shares': { zh: '认购份额', en: 'Curation Shares', ja: '購入シェア数' },
  'market.curation_success': { zh: '共创支持成功！', en: 'Curation Support Success!', ja: '共創支援に成功しました！' },
  'market.desc_earn': { zh: '永久分享该歌曲产生的每一次收听奖励。', en: 'Earn a share of every listening reward permanently.', ja: 'その曲が再生されるたびに発生する報酬を永続的に共有します。' },
  'market.desc_equity_detail_1': { zh: '认购完成后，您将直接持有该歌曲在去中心化网络中的分红权。', en: 'Once subscribed, you will directly hold the dividend rights of the song in the decentralized network.', ja: '購入完了後、分散型ネットワーク内における該当楽曲の配当権を直接保有します。' },
  'market.desc_equity_detail_2': { zh: '收益将通过智能合约自动结算至您的账户。', en: 'Earnings will be automatically settled to your account via smart contracts.', ja: '収益はスマートコントラクトを介して自動的にアカウントに決済されます。' },
  'market.desc_ipo': { zh: '创作者将其作品的部分收益权（股权）进行公开募集。', en: 'Creators raise funds by offering equity of their works.', ja: 'クリエイターが作品の収益権（株式）の一部を公開募集します。' },
  'market.desc_trust_contract': { zh: '该项目由智能合约自动托管与执行。', en: 'This project is automatically managed and executed by smart contracts.', ja: 'このプロジェクトはスマートコントラクトによって自動的に管理および実行されます。' },
  'market.equity': { zh: '权益', en: 'Equity', ja: '持分' },
  'market.funded': { zh: '已募集', en: 'Funded', ja: '募集完了' },
  'market.header_subtitle': { zh: '发现优质音乐，参与共创，分享链上播放红利', en: 'Discover quality music, participate in co-creation, and share on-chain streaming dividends', ja: '優れた音楽を発見し、共創に参加して、オンチェーン再生の配当を共有します' },
  'market.header_title': { zh: '共创音乐市集', en: 'Co-Curation Market', ja: '共創音楽マーケット' },
  'market.no_active_songs': { zh: '当前没有正在募集中或已经结束的项目', en: 'No active or completed projects currently', ja: '現在募集中のプロジェクトはありません' },
  'market.preview': { zh: '试听', en: 'Preview', ja: '試聴' },
  'market.shares_left': { zh: '剩余份额', en: 'Shares Left', ja: '残りシェア' },
  'market.shares_left_format': { zh: '剩余 {shares} 股', en: '{shares} Shares Left', ja: '残り {shares} シェア' },
  'market.sold_out': { zh: '已售罄', en: 'Sold Out', ja: '完売' },
  'market.support_now': { zh: '立即支持', en: 'Support Now', ja: '今すぐ支援' },
  'market.support_progress': { zh: '支持进度', en: 'Support Progress', ja: '支援進捗' },
  'market.title': { zh: '什么是音乐 IPO?', en: 'What is Music IPO?', ja: '音楽IPOとは？' },
  'market.toast_confirm_metamask': { zh: '请在 MetaMask 钱包中确认交易', en: 'Please confirm the transaction in MetaMask wallet', ja: 'MetaMaskウォレットでトランザクションを確認してください' },
  'market.toast_curation_success_1': { zh: '成功认购 ', en: 'Successfully subscribed to ', ja: 'の購入に成功しました：' },
  'market.toast_curation_success_2': { zh: ' 份份额！', en: ' shares!', ja: ' シェア！' },
  'market.toast_curation_success_3': { zh: '已计入您的资产中心。', en: 'Has been added to your Asset Center.', ja: 'アセットセンターに追加されました。' },
  'market.toast_insufficient_balance': { zh: '账户余额不足！请充值或切换至信用额度代付。', en: 'Insufficient account balance! Please top up or switch to Credit Limit payment.', ja: 'アカウント残高が不足しています！チャージするか信用枠払いに切り替えてください。' },
  'market.toast_insufficient_credit': { zh: '信用额度不足！请使用余额或充值。', en: 'Insufficient credit limit! Please use balance or top up.', ja: '信用枠が不足しています！残高を使用するか、チャージしてください。' },
  'market.toast_network_error': { zh: '网络错误，请稍后重试', en: 'Network error, please try again later', ja: 'ネットワークエラーが発生しました。後で再試行してください' },
  'market.toast_not_logged_in': { zh: '请先登录！', en: 'Please log in first!', ja: '先にログインしてください！' },
  'market.toast_payment_failed': { zh: '付款失败：', en: 'Payment failed: ', ja: '支払い失敗：' },
  'market.toast_payment_success': { zh: '付款成功，正在处理交易...', en: 'Payment success, processing transaction...', ja: '支払い成功、トランザクションを処理中...' },
  'market.toast_tx_failed': { zh: '链上代币划转失败！请检查余额或重试。', en: 'On-chain token transfer failed! Check balance or retry.', ja: 'オンチェーンのトークン転送に失敗しました！残高を確認するか再試行してください。' },
  'market.toast_tx_submitted': { zh: '代币划转交易已提交，等待链上确认...', en: 'Token transfer transaction submitted, waiting for confirmation...', ja: 'トークン転送トランザクションが送信されました。確認を待機中...' },
  'market.use_credit_limit': { zh: '使用信用额度支付', en: 'Pay with Credit Limit', ja: '信用枠で支払う' },
  'market.waiting_join': { zh: '等待加入', en: 'Waiting to Join', ja: '参加待機中' },
  'market.wallet_signing': { zh: '正在调用钱包签名...', en: 'Calling wallet signature...', ja: 'ウォレット署名を呼び出し中...' },

  // MOOD namespace
  'mood.focus': { zh: '专注', en: 'Focus', ja: '集中' },
  'mood.healing': { zh: '治愈', en: 'Healing', ja: '癒し' },
  'mood.hot': { zh: '热血', en: 'Energetic', ja: '熱血' },
  'mood.lonely': { zh: '孤独', en: 'Lonely', ja: '孤独' },
  'mood.meditation': { zh: '冥想', en: 'Meditation', ja: '瞑想' },
  'mood.midnight': { zh: '午夜', en: 'Midnight', ja: '真夜中' },
  'mood.relax': { zh: '放松', en: 'Relax', ja: 'リラックス' },
  'mood.sad': { zh: '伤感', en: 'Sad', ja: '悲しい' },
  'mood.sleep': { zh: '助眠', en: 'Sleep', ja: '睡眠' },
  'mood.workout': { zh: '运动', en: 'Workout', ja: 'ワークアウト' },

  // NAV namespace
  'nav.community': { zh: '社区', en: 'Community', ja: 'コミュニティ' },
  'nav.discover': { zh: '发现', en: 'Discover', ja: '発見' },
  'nav.home': { zh: '首页', en: 'Home', ja: 'ホーム' },
  'nav.login': { zh: '登录 / 注册', en: 'Login / Register', ja: 'ログイン / 登録' },
  'nav.logout': { zh: '退出登录', en: 'Logout', ja: 'ログアウト' },
  'nav.profile': { zh: '我的', en: 'Profile', ja: 'プロファイル' },
  'nav.wallet': { zh: '钱包', en: 'Wallet', ja: 'ウォレット' },

  // PLAYER namespace
  'player.add_to_playlist': { zh: '添加至歌单', en: 'Add to Playlist', ja: 'プレイリストに追加' },
  'player.back_to_cover': { zh: '返回封面', en: 'Back to Cover', ja: 'カバーに戻る' },
  'player.clear_queue': { zh: '清空播放队列', en: 'Clear Queue', ja: 'キューをクリア' },
  'player.clear_queue_confirm': { zh: '确定要清空播放队列吗？', en: 'Are you sure you want to clear the playback queue?', ja: '再生キューを空にしますか？' },
  'player.co_creation': { zh: '共创', en: 'Co-Curation', ja: '共創' },
  'player.co_creation_cost_estimate': { zh: '本次共创认购预计可获得该作品约 <strong>{percentage}%</strong> 的版权共有份额及对应的版税分红权。', en: 'This co-creation subscription is estimated to yield approximately <strong>{percentage}%</strong> of the work\'s shared copyright and corresponding royalty dividends.', ja: 'この共創サブスクリプションにより、作品の共有著作権の約 <strong>{percentage}%</strong> と対応するロイヤリティ配当が得られると推定されます。' },
  'player.co_creation_inactive': { zh: '筹备中', en: 'Upcoming', ja: '準備中' },
  'player.co_creator': { zh: '联合创作者', en: 'Co-Creator', ja: '共同制作者' },
  'player.collapse': { zh: '收起', en: 'Collapse', ja: '折りたたむ' },
  'player.comment_failed': { zh: '发表评论失败，请重试', en: 'Failed to post comment, please try again', ja: 'コメントの投稿に失敗しました。再試行してください' },
  'player.comment_placeholder': { zh: '发表你的精彩评论...', en: 'Write a comment...', ja: 'コメントを書く...' },
  'player.comment_submit': { zh: '发送', en: 'Send', ja: '送信' },
  'player.comments': { zh: '评论', en: 'Comments', ja: 'コメント' },
  'player.confirm_download': { zh: '确认下载', en: 'Confirm Download', ja: 'ダウンロード確認' },
  'player.confirm_purchase': { zh: '确认认购', en: 'Confirm Purchase', ja: '購入確認' },
  'player.current_queue': { zh: '播放队列', en: 'Play Queue', ja: '再生キュー' },
  'player.current_song': { zh: '当前播放', en: 'Current Song', ja: '再生中の曲' },
  'player.download': { zh: '下载', en: 'Download', ja: 'ダウンロード' },
  'player.download_cost_desc': { zh: '下载作品《{title}》需要支付 2.00 ECHO 积分（直接分配给创作者与版权合伙人），确认下载吗？', en: 'Downloading "{title}" costs 2.00 ECHO (distributed directly to creators and equity holders). Confirm download?', ja: '作品「{title}」をダウンロードするには2.00 ECHOが必要です（クリエイターおよび持分保有者に直接分配されます）。ダウンロードしますか？' },
  'player.download_started': { zh: '开始下载...', en: 'Download started...', ja: 'ダウンロードを開始しました...' },
  'player.favorite': { zh: '收藏', en: 'Favorite', ja: 'お気に入り' },
  'player.favorite_added': { zh: '已添加至收藏', en: 'Added to favorites', ja: 'お気に入りに追加しました' },
  'player.favorite_removed': { zh: '已从收藏中移除', en: 'Removed from favorites', ja: 'お気に入りから削除しました' },
  'player.insufficient_balance_download': { zh: '余额不足以支付下载费用！', en: 'Insufficient balance for download!', ja: 'ダウンロードするための残高が不足しています！' },
  'player.insufficient_balance_ipo': { zh: '余额不足，无法参与认购！', en: 'Insufficient balance to invest!', ja: '残高不足のため購入できません！' },
  'player.insufficient_shares_ipo': { zh: '剩余份额不足！', en: 'Insufficient shares left!', ja: '残りシェアが不足しています！' },
  'player.invest': { zh: '支持共创', en: 'Invest', ja: '投資' },
  'player.ipo_failed_toast': { zh: '认购失败，请稍后重试', en: 'Investment failed, please try again later', ja: '購入に失敗しました。後で再試行してください' },
  'player.ipo_percentage_label': { zh: '分红比例', en: 'Dividend %', ja: '配当割合' },
  'player.ipo_success_toast': { zh: '认购成功！', en: 'Investment successful!', ja: '購入に成功しました！' },
  'player.ipo_tx_failed_err': { zh: '交易执行失败，请重试', en: 'Transaction failed, please try again', ja: 'トランザクションに失敗しました。再試行してください' },
  'player.like': { zh: '点赞', en: 'Like', ja: 'いいね' },
  'player.login_to_comment': { zh: '请先登录以发表评论', en: 'Please log in to comment', ja: 'コメントするにはログインしてください' },
  'player.login_to_download': { zh: '请先登录以进行下载', en: 'Please log in to download', ja: 'ダウンロードするにはログインしてください' },
  'player.login_to_favorite': { zh: '请先登录以收藏歌曲', en: 'Please log in to favorite songs', ja: 'お気に入り登録するにはログインしてください' },
  'player.lyrics': { zh: '词', en: 'Lyrics', ja: '歌詞' },
  'player.lyrics_synced': { zh: '歌词同步', en: 'Lyrics Synced', ja: '歌詞シンク' },
  'player.max_label': { zh: '最大', en: 'MAX', ja: '最大' },
  'player.metamask_payment_prompt': { zh: '请在 MetaMask 中确认付款...', en: 'Please confirm payment in MetaMask...', ja: 'MetaMaskで支払いを確認してください...' },
  'player.mining': { zh: '听歌挖矿中', en: 'Mining Rewards', ja: 'マイニング報酬中' },
  'player.mining_rate_desc': { zh: '产出速率 1.00 ECHO/分', en: 'Rate: 1.00 ECHO/min', ja: 'レート: 1.00 ECHO/分' },
  'player.play_queue': { zh: '播放队列', en: 'Play Queue', ja: '再生キュー' },
  'player.price_per_share': { zh: '单价', en: 'Price/Share', ja: '単価/シェア' },
  'player.purchase_equity_title': { zh: '认购音乐 IPO 份额', en: 'Purchase Music IPO Shares', ja: '音楽IPOシェアを購入' },
  'player.queue_empty': { zh: '播放队列为空', en: 'Playback queue is empty', ja: '再生キューが空です' },
  'player.remaining_shares_label': { zh: '剩余份额', en: 'Remaining Shares', ja: '残りシェア数' },
  'player.remove_from_queue': { zh: '从队列中移除', en: 'Remove from Queue', ja: 'キューから削除' },
  'player.reviews_title': { zh: '乐评', en: 'Reviews', ja: 'レビュー' },
  'player.share': { zh: '分享', en: 'Share', ja: '共有' },
  'player.share_click_to_listen': { zh: '点击立刻收听', en: 'Click to listen now', ja: 'クリックして今すぐ聴く' },
  'player.share_item': { zh: '分享歌曲', en: 'Share Song', ja: '曲を共有' },
  'player.share_prompt_copied': { zh: '复制成功！', en: 'Copied successfully!', ja: 'コピーに成功しました！' },
  'player.share_prompt_copied_link': { zh: '分享链接已复制到剪贴板！', en: 'Share link copied to clipboard!', ja: '共有リンクをクリップボードにコピーしました！' },
  'player.share_prompt_copied_link_fallback': { zh: '已复制链接，请手动分享', en: 'Link copied, please share manually', ja: 'リンクがコピーされました。手動で共有してください' },
  'player.share_prompt_copied_rt': { zh: '分享文案已复制！', en: 'Share text copied!', ja: '共有テキストをコピーしました！' },
  'player.share_text': { zh: '向你推荐一首在 ECHORURA 上发掘的好歌：《{title}》- {artist}。听歌还能挖矿，快来一起收听吧！', en: 'I recommend a great song I discovered on ECHORURA: "{title}" - {artist}. You can mine rewards while listening, come join me!', ja: 'ECHORURAで見つけた素晴らしい曲をおすすめします：「{title}」- {artist}。聴きながらマイニングもできます、一緒に聴きましょう！' },
  'player.shares_to_buy': { zh: '认购份额', en: 'Shares to Buy', ja: '購入シェア数' },
  'player.shares_unit': { zh: '份', en: 'Shares', ja: 'シェア' },
  'player.total_cost': { zh: '总额', en: 'Total Cost', ja: '合計金額' },
  'player.transferring': { zh: '划转代币中...', en: 'Transferring tokens...', ja: 'トークンを転送中...' },
  'player.tx_failed': { zh: '链上支付失败: ', en: 'On-chain payment failed: ', ja: 'オンチェーン決済失敗: ' },
  'player.tx_submitted_waiting': { zh: '交易已提交，等待链上确认...', en: 'Transaction submitted, waiting for on-chain confirmation...', ja: 'トランザクション送信済み、チェーン上の確認を待機中...' },
  'player.view_lyrics': { zh: '查看歌词', en: 'View Lyrics', ja: '歌詞を見る' },

  // PLAYLIST namespace
  'playlist.add_to_collection': { zh: '收藏到歌单', en: 'Add to Playlist', ja: 'プレイリストに追加' },
  'playlist.added': { zh: '已加入', en: 'Added', ja: '追加済み' },
  'playlist.adding_song': { zh: '正在将《{songTitle}》加入您的收藏', en: 'Adding \"{songTitle}\" to your collection', ja: '「{songTitle}」をコレクションに追加中' },
  'playlist.back_to_page': { zh: '返回页面', en: 'Back', ja: '戻る' },
  'playlist.confirm_create_add': { zh: '确认创建并加入', en: 'Create & Add', ja: '作成して追加' },
  'playlist.confirm_remove': { zh: '确定要从该歌单中移除这首歌曲吗？', en: 'Are you sure you want to remove this song from the playlist?', ja: 'この曲をプレイリストから削除してもよろしいですか？' },
  'playlist.create_first': { zh: '创建首个歌单', en: 'Create First Playlist', ja: '最初のプレイリストを作成' },
  'playlist.create_new': { zh: '创建新歌单', en: 'Create New Playlist', ja: '新規プレイリスト作成' },
  'playlist.empty': { zh: '📭 您还没有创建任何歌单', en: '📭 You haven\'t created any playlists yet', ja: '📭 プレイリストがまだ作成されていません' },
  'playlist.empty_list': { zh: '空空如也', en: 'Empty', ja: '空っぽ' },
  'playlist.label': { zh: '歌单', en: 'Playlist', ja: 'プレイリスト' },
  'playlist.link_copied': { zh: '链接已复制', en: 'Link copied', ja: 'リンクがコピーされました' },
  'playlist.loading': { zh: '载入歌单列表中...', en: 'Loading playlist list...', ja: 'プレイリスト一覧を読み込み中...' },
  'playlist.loading_content': { zh: '正在极速载入歌单内容...', en: 'Loading playlist content...', ja: 'プレイリストのコンテンツを読み込み中...' },
  'playlist.new_name': { zh: '新建歌单名称', en: 'New Playlist Name', ja: '新規プレイリスト名' },
  'playlist.new_playlist': { zh: '新建歌单', en: 'New Playlist', ja: '新規プレイリスト' },
  'playlist.no_custom_playlists': { zh: '您尚未创建任何自定义歌单', en: 'You have not created any custom playlists yet', ja: 'カスタムプレイリストはまだ作成されていません' },
  'playlist.no_desc': { zh: '暂无描述信息', en: 'No description info', ja: '説明はありません' },
  'playlist.no_songs': { zh: '暂无歌曲，快去探索音乐并把歌曲加入你的歌单吧！', en: 'No songs yet, explore music and add some to your playlist!', ja: '曲がありません。音楽を探索してプレイリストに追加しましょう！' },
  'playlist.no_songs_short': { zh: '暂无歌曲', en: 'No Songs', ja: '曲がありません' },
  'playlist.not_found': { zh: '⚠️ 歌单不存在或已被删除', en: '⚠️ Playlist not found or deleted', ja: '⚠️ プレイリストが見つからないか削除されました' },
  'playlist.not_found_desc': { zh: '无法加载此歌单的信息，可能链接已失效。', en: 'Unable to load info, the link may have expired.', ja: '情報を読み込めません。リンクの有効期限が切れている可能性があります。' },
  'playlist.placeholder': { zh: '例如：深夜解压纯音乐、午后节奏特调', en: 'e.g. Midnight Ambient, Afternoon Beats', ja: '例：深夜のアンビエント、午後のビート' },
  'playlist.play_all': { zh: '播放全部', en: 'Play All', ja: 'すべて再生' },
  'playlist.remove': { zh: '从歌单中移除', en: 'Remove from Playlist', ja: 'プレイリストから削除' },
  'playlist.remove_failed': { zh: '移除失败', en: 'Remove failed', ja: '削除に失敗しました' },
  'playlist.share': { zh: '分享歌单', en: 'Share Playlist', ja: 'プレイリストを共有' },
  'playlist.share_desc': { zh: '向您推荐这张高品质极声音频歌单《{name}》！快来加入共创并听歌获取收益。', en: 'Highly recommend this high-quality ECHORURA playlist \"{name}\"! Join co-creation & listen to earn.', ja: '高品質なECHORURAプレイリスト『{name}』をおすすめします！共創に参加して聴いて稼ぎましょう。' },
  'playlist.share_link': { zh: '歌单链接：', en: 'Link: ', ja: 'リンク：' },
  'playlist.share_title': { zh: '极声音乐推荐歌单《{name}》', en: 'ECHORURA Recommended Playlist: {name}', ja: 'ECHORURAおすすめプレイリスト『{name}』' },
  'playlist.songs_count': { zh: '{count} 首作品', en: '{count} songs', ja: '{count} 曲' },
  'playlist.songs_list': { zh: '歌单曲目 ({count})', en: 'Playlist Tracks ({count})', ja: '収録曲 ({count})' },

  // PROFILE namespace
  'profile.audience_holder': { zh: '0.3(听众) / 0.7(权益人)', en: '0.3(Audience) / 0.7(Equity Holder)', ja: '0.3(リスナー) / 0.7(持分保有者)' },
  'profile.creator_overview': { zh: '创作者概览', en: 'Creator Overview', ja: 'クリエイター概要' },
  'profile.current_balance': { zh: '当前账户余额', en: 'Current Account Balance', ja: '現在のアカウント残高' },
  'profile.earning_model': { zh: '收益模型: ', en: 'Revenue Model: ', ja: '収益モデル: ' },
  'profile.login_required': { zh: '请先登录', en: 'Please Log In', ja: 'ログインしてください' },
  'profile.login_required_desc': { zh: '只有登录后才能管理你的作品和收益', en: 'You need to log in to manage your works and earnings.', ja: '作品と収益を管理するにはログインが必要です。' },
  'profile.my_favorites': { zh: '我的收藏', en: 'My Favorites', ja: 'マイお気に入り' },
  'profile.my_follows': { zh: '我的关注', en: 'My Follows', ja: 'マイフォロー' },
  'profile.my_playlists': { zh: '我的歌单', en: 'My Playlists', ja: 'プレイリスト' },
  'profile.my_works': { zh: '我的作品', en: 'My Works', ja: 'マイ作品' },
  'profile.no_bio': { zh: '暂无简介', en: 'No bio yet', ja: 'プロフィール文は未設定です' },
  'profile.no_favorites': { zh: '暂无收藏作品', en: 'No favorite works yet', ja: 'お気に入り作品はありません' },
  'profile.no_follows': { zh: '您还未关注任何创作者', en: 'You have not followed any creators yet', ja: 'まだクリエイターをフォローしていません' },
  'profile.no_works': { zh: '你还没有发布过任何作品', en: 'You have not published any works yet', ja: 'まだ作品を公開していません' },
  'profile.plays_count': { zh: '播放量', en: 'Plays', ja: '再生数' },
  'profile.publish_new_work': { zh: '发布新作品', en: 'Publish New Work', ja: '新規作品を公開' },
  'profile.published_works': { zh: '已发布作品', en: 'Published Works', ja: '公開済み作品' },
  'profile.staked_today': { zh: '今日推荐质押中 (10 ECHO)', en: 'Staking Today (10 ECHO)', ja: '本日アリーナ質押中 (10 ECHO)' },
  'profile.total_plays': { zh: '累计收听量', en: 'Total Plays', ja: '累計再生数' },
  'profile.visit_homepage': { zh: '访问主页', en: 'Visit Profile', ja: 'プロフィールを見る' },

  // WALLET namespace
  'wallet.aa_sca': { zh: 'AA 智能托管账户 (SCA)', en: 'AA Smart Custody Account (SCA)', ja: 'AAスマートコントラクトウォレット (SCA)' },
  'wallet.aa_sca_desc': { zh: '极声音乐为每位用户静默托管的无感 Web3 智能账号，安全合规，私钥未备份前不可直接导出。', en: 'Silently escrowed Web3 smart account for seamless UX. Private key cannot be exported before KYC backup.', ja: 'ECHORURAがすべてのユーザーにサイレントカストディするWeb3スマートアカウント。KYCバックアップを行うまで秘密鍵は直接エクスポートできません。' },
  'wallet.accumulated_dividends_earned': { zh: '累计赚取分红', en: 'Accumulated Dividends Earned', ja: '累積獲得配当' },
  'wallet.address_copied': { zh: '地址已复制到剪贴板', en: 'Address copied to clipboard', ja: 'アドレスをクリップボードにコピーしました' },
  'wallet.asset_hub_subtitle': { zh: '管理您的数字资产、分红权益与钱包连接', en: 'Manage your digital assets, dividend rights, and wallet connection', ja: 'デジタルアセット、配当権利、ウォレット接続を管理します' },
  'wallet.asset_name': { zh: '资产名称', en: 'Asset Name', ja: 'アセット名' },
  'wallet.asset_portfolios': { zh: ' 资产', en: ' Asset Portfolios', ja: ' アセットポートフォリオ' },
  'wallet.auditing': { zh: '听审中', en: 'Auditing', ja: '監査中' },
  'wallet.back': { zh: '返回', en: 'Back', ja: '戻る' },
  'wallet.beta_alert': { zh: '该功能处于 Beta 测试阶段，仅支持模拟交易体验！', en: 'This feature is in Beta, only simulating transaction experience!', ja: 'この機能はベータテスト中であり、シミュレーション取引のみをサポートしています！' },
  'wallet.card_number': { zh: '卡号', en: 'Card Number', ja: 'カード番号' },
  'wallet.claim_failed': { zh: '领取分红失败', en: 'Claim dividends failed', ja: '配当請求失敗' },
  'wallet.claim_on_chain_dividends': { zh: '领取链上分红收益', en: 'Claim On-chain Dividends', ja: 'オンチェーン配当を請求' },
  'wallet.claim_success_msg': { zh: '分红领取成功！已转入您的托管钱包。', en: 'Dividends claimed successfully! Transferred to escrow wallet.', ja: '配当の請求に成功しました！カストディウォレットに転送されました。' },
  'wallet.claim_tx_submitted': { zh: '分红领取交易已提交，等待链上打包...', en: 'Dividends claim transaction submitted, waiting for packaging...', ja: '配当請求トランザクションが送信されました。オンチェーンの処理を待機中...' },
  'wallet.connect_failed': { zh: '连接钱包失败，请确保已安装 MetaMask 插件', en: 'Wallet connection failed, ensure MetaMask plugin is installed', ja: 'ウォレット接続失敗、MetaMaskプラグインがインストールされているか確認してください' },
  'wallet.connect_metamask': { zh: '连接 MetaMask 钱包', en: 'Connect MetaMask Wallet', ja: 'MetaMaskウォレットを接続' },
  'wallet.connect_metamask_claim': { zh: '请先连接 MetaMask 钱包以领取链上收益', en: 'Please connect MetaMask wallet first to claim on-chain rewards', ja: 'オンチェーン報酬を請求するには、先にMetaMaskウォレットを接続してください' },
  'wallet.connect_metamask_desc': { zh: '通过连接外部 MetaMask 钱包，您可以查看、转账链上真实 ECHO 代币及音乐所有权资产。', en: 'Connect MetaMask to view and transfer real on-chain ECHO tokens and music equity.', ja: '外部のMetaMaskウォレットを接続することで、オンチェーン上のリアルなECHOトークンおよび音楽所有権アセットの確認・転送が可能です。' },
  'wallet.connected_base': { zh: '已连接 Base 主网', en: 'Connected Base', ja: 'Baseメインネットに接続中' },
  'wallet.contract_read_error': { zh: '读取链上余额失败，请确保已切换到 Base Sepolia 测试网', en: 'Failed to read on-chain balance. Make sure to switch to Base Sepolia testnet', ja: 'オンチェーン残高の読み取りに失敗しました。Base Sepoliaテストネットに切り替えてください' },
  'wallet.copy': { zh: '复制', en: 'Copy', ja: 'コピー' },
  'wallet.credit_card': { zh: '信用卡 / 借记卡', en: 'Credit / Debit Card', ja: 'クレジットカード / デビットカード' },
  'wallet.credit_desc': { zh: '基于您的信用额度进行先行代付，免去频繁签名的繁琐，适合日常快速操作。', en: 'Advance payment based on credit limit, bypassing frequent signatures.', ja: '与信枠に基づいて先行支払いを行います。頻繁な署名の手間を省き、日常の高速な操作に適しています。' },
  'wallet.credit_limit': { zh: '可用信用额度 (Available Credit)', en: 'Available Credit', ja: '利用可能与信枠 (Available Credit)' },
  'wallet.used_limit': { zh: '已用额度', en: 'Used Limit', ja: '使用済み額' },
  'wallet.credit_privilege': { zh: '信用支付特权 (Web2.5)', en: 'Credit Payment Privilege (Web2.5)', ja: '信用支付特権 (Web2.5)' },
  'wallet.curation_total': { zh: '共创共享音乐总值', en: 'Co-Curation Total Value', ja: '共創音楽総価値' },
  'wallet.current_price': { zh: '当前单价', en: 'Current Price', ja: '現在の単価' },
  'wallet.custody_status': { zh: '托管状态', en: 'Custody Status', ja: 'カストディ状態' },
  'wallet.custom_amount': { zh: '自定义金额', en: 'Custom Amount', ja: 'カスタム金額' },
  'wallet.cvc': { zh: '验证码', en: 'CVC', ja: 'セキュリティコード' },
  'wallet.equity_ref_value': { zh: '版权持股参考估值', en: 'Equity Reference Valuation', ja: '著作権持分参考評価' },
  'wallet.est_market_value': { zh: '估算市场价值', en: 'Est. Market Value', ja: '推定市場価値' },
  'wallet.evm_self_custody': { zh: 'EVM 自托管钱包 (MetaMask)', en: 'EVM Self-Custody Wallet (MetaMask)', ja: 'EVM自己管理ウォレット (MetaMask)' },
  'wallet.expiry': { zh: '有效期', en: 'Expiry', ja: '有効期限' },
  'wallet.external_metamask': { zh: '外部 MetaMask 账户', en: 'External MetaMask Account', ja: '外部MetaMaskアカウント' },
  'wallet.fiat_disclaimer': { zh: '提示：由于汇率及测试网限制，法币充值仅做测试阶段模拟展示，充值成功后将以 1 USD = 100 ECHO 的汇率计入您的极声账户余额。', en: 'Note: Fiat deposit is for demo simulation only. 1 USD = 100 ECHO.', ja: '注意：為替レートおよびテストネットの制限により、法定通貨チャージはテスト段階のシミュレーション展示のみであり、チャージ成功後は1 USD = 100 ECHOのレートでアカウント残高に加算されます。' },
  'wallet.fiat_exchange_rate': { zh: '法币汇率 (模拟)：1 USD = 100 ECHO', en: 'Fiat Rate (Sim): 1 USD = 100 ECHO', ja: '法定通貨レート (シミュレーション)：1 USD = 100 ECHO' },
  'wallet.go_to_market': { zh: '前往市集认购', en: 'Go to Market', ja: 'マーケットへ' },
  'wallet.interest_free': { zh: '免息先付', en: 'Interest-Free Pay', ja: '無利息先払い' },
  'wallet.kyc_protected': { zh: 'KYC 身份受保护', en: 'KYC Protected', ja: 'KYC保護済み' },
  'wallet.listener_weight': { zh: '基于你的 Listener Weight (收听活跃度) 动态评估', en: 'Dynamically evaluated based on your Listener Weight', ja: 'リスナーウェイト（再生アクティビティ）に基づいて動的に評価' },
  'wallet.locked_available': { zh: '已锁定可用 (Available)', en: 'Locked & Available', ja: 'ロック済み（利用可能）' },
  'wallet.min_sync_threshold': { zh: '提示：当收益累积达 5.00 ECHO 时方可进行链上清算与提取', en: 'Note: On-chain settlement & withdrawal is available when earnings reach 5.00 ECHO', ja: '注意：収益が5.00 ECHOに達すると、オンチェーン決済と引き出しが可能になります' },
  'wallet.not_connected': { zh: '未连接外部钱包', en: 'External Wallet Not Connected', ja: '外部ウォレット未接続' },
  'wallet.quick_topup': { zh: '极速充值', en: 'Quick Top-Up', ja: 'クイックチャージ' },
  'wallet.reset_midnight': { zh: '至24点清零', en: 'Resets at midnight', ja: '深夜0時リセット' },
  'wallet.sync_amount_rewards': { zh: '一键同步上链已审计收益 ({amount} ECHO)', en: 'Sync Audited Earnings to Chain ({amount} ECHO)', ja: '監査済み収益をオンチェーン同期 ({amount} ECHO)' },
  'wallet.today_listen_earn': { zh: '本日音乐收听收益', en: 'Today\'s Listen Earnings', ja: '本日のリスニング収益' },
  'wallet.token_balance': { zh: '余额', en: 'Balance', ja: '残高' },
  'wallet.topup_not_available': { zh: '内测期间，充值暂未开通', en: 'Top-up is not available during beta test', ja: 'ベータテスト中、チャージはご利用いただけません' },
  'wallet.total_limit': { zh: '总额度', en: 'Total Limit', ja: '総枠' },
  'wallet.tx_stream': { zh: '收益流水 (Txs)', en: 'Earnings (Txs)', ja: '収益ログ (Txs)' },
    'wallet.no_valid_address': { zh: '没有有效的托管地址', en: 'No valid custody address', ja: '有効なカストディアドレスがありません' },
  'wallet.insufficient_balance_sync': { zh: '当前余额不足，无法发起清算同步！', en: 'Insufficient balance, cannot initiate sync!', ja: '残高不足のため、同期を開始できません！' },
  'wallet.session_expired_sync': { zh: '会话已过期，请重新登录后再试！', en: 'Session expired, please log in again!', ja: 'セッションの期限が切れました。再ログインしてください！' },
  'wallet.sync_success': { zh: '收益已成功同步至链上智能账户！', en: 'Earnings successfully synced to chain smart account!', ja: '収益がチェーン上のスマートアカウントに同期されました！' },
  'wallet.sync_failed': { zh: '同步失败: ', en: 'Sync failed: ', ja: '同期失敗: ' },
  'wallet.syncing_rewards': { zh: '正在清算同步收益...', en: 'Syncing rewards to chain...', ja: '収益を同期中...' },
  'wallet.silent_custody': { zh: '设备密钥安全保护', en: 'Device Key Protected', ja: 'デバイスキー保護' },
  'wallet.connect_smart_wallet': { zh: '创建 / 连接 Base 智能钱包', en: 'Create / Connect Base Smart Wallet', ja: 'Baseスマートウォレットを作成 / 接続' },
  'wallet.disconnect_wallet': { zh: '断开连接', en: 'Disconnect Wallet', ja: '接続を解除' },
  'wallet.connect_first': { zh: '请先连接您的 Base 智能钱包！', en: 'Please connect your Base Smart Wallet first!', ja: '先にBaseスマートウォレットを连接してください！' },
  'wallet.wallet_status_connected': { zh: '已连接 (真实链上)', en: 'Connected (On-Chain)', ja: '接続済み (オンチェーン)' },
  'wallet.wallet_status_disconnected': { zh: '未连接', en: 'Not Connected', ja: '未接続' },
  'wallet.smart_wallet_desc': { zh: '基于 Base 链的智能合约账户，由您的设备生物识别（Passkey）安全保护。一键同步指令将自动将您的收益铸造分发到该地址。', en: 'Base smart contract account, secured by your device biometrics (Passkey). Synchronized earnings will be minted directly to this address.', ja: 'Baseスマートアカウント。デバイスの生体認証（Passkey）で安全に保護されています。同期された収益はこのアドレスに直接ミントされます。' },
  'wallet.sync_tx_sent': { zh: '一键清算指令已送达智能合约', en: 'Settlement command sent to smart contract', ja: '決済コマンドがスマートコントラクトに送信されました' },
  'wallet.sync_tx_sent_desc': { zh: '智能合约正在异步执行清算，代币分发将直接到达您的智能账户地址。', en: 'Smart contract is curating settlement. Tokens will arrive directly in your smart account.', ja: 'スマートコントラクトが決済を处理中。トークンはスマートアカウントに直接到着します。' },
  'wallet.view_on_basescan': { zh: '在 BaseScan 上查看交易', en: 'View transaction on BaseScan', ja: 'BaseScanでトランザクションを表示' },
  'wallet.onchain_balance': { zh: '已同步链上余额', en: 'Synced On-Chain Balance', ja: '同期済みオンチェーン残高' },
  'wallet.transfer_out': { zh: '转出代币', en: 'Transfer Tokens', ja: 'トークンを転送' },
  'wallet.recipient_address': { zh: '接收端以太坊地址 (0x...)', en: 'Recipient EVM Address (0x...)', ja: '受信先EVMアドレス (0x...)' },
  'wallet.transfer_amount_input': { zh: '要转出的代币数量 (ECHO)', en: 'Amount of ECHO to transfer', ja: '転送するECHO数量' },
  'wallet.transfer_sending': { zh: '正在发送区块链交易...', en: 'Sending on-chain transaction...', ja: 'チェーン上にトランザクションを送信中...' },
  'wallet.transfer_confirming': { zh: '正在等待区块确认...', en: 'Waiting for block confirmation...', ja: 'ブロックの承認を待机中...' },
  'wallet.transfer_success': { zh: '🎉 转账成功！交易已被区块打包。', en: 'Transfer successful! Transaction confirmed on block.', ja: '転送が成功しました！' },
  'wallet.transfer_failed': { zh: '❌ 转账失败: ', en: 'Transfer failed: ', ja: '転送失敗: ' },
  'wallet.close': { zh: '关闭', en: 'Close', ja: '閉じる' },
  'wallet.send': { zh: '立即发送', en: 'Send Now', ja: '送信する' },
  'wallet.invalid_recipient': { zh: '请输入有效的 0x 格式以太坊地址！', en: 'Please enter a valid 0x EVM address!', ja: '有効なEVMアドレスを入力してください！' },
  'wallet.invalid_amount': { zh: '请输入大于 0 且不超过当前余额的数量！', en: 'Please enter an amount greater than 0 and less than your balance!', ja: '有效な数量を入力してください！' },
  'wallet.deposit_to_platform': { zh: '存入平台账户', en: 'Deposit to App', ja: 'プラットフォームに入金' },
  'wallet.deposit_amount_input': { zh: '要存入的代币数量 (ECHO)', en: 'Amount of ECHO to deposit', ja: '入金するECHO数量' },
  'wallet.deposit_sending': { zh: '正在发送代币到平台...', en: 'Transferring tokens to app...', ja: 'アプリにトークンを转送中...' },
  'wallet.deposit_verifying': { zh: '正在验证链上交易并入账...', en: 'Verifying on-chain transaction & crediting...', ja: 'チェーン上のトランザクションを検証して入金中...' },
  'wallet.deposit_success': { zh: '🎉 存入成功！代币已成功兑换并转入您的平台账户余额。', en: 'Deposit successful! Tokens converted and credited to your app balance.', ja: '入金成功！トークンがアプリ残高に変換されました。' },
  'wallet.deposit_failed': { zh: '❌ 存入入账失败: ', en: 'Deposit failed: ', ja: '入金失敗: ' },
  'wallet.portfolio_desc': { zh: '您持有的全部音乐共创共享股权和认购股份。', en: 'All music co-curation equity and subscribed shares you hold.', ja: '保有しているすべての音楽共創持分および購入シェア。' },
  'wallet.real_time_valuation': { zh: '持股参考估值', en: 'Equity Reference Value', ja: '持分参考評価額' },
  'wallet.shares_held': { zh: '持有份额', en: 'Shares Held', ja: '保有シェア数' },
  'wallet.history_dividends': { zh: '累计赚取分红', en: 'Accumulated Dividends', ja: '累積獲得配当' },
  'wallet.system_shares': { zh: ' 份', en: ' Shares', ja: ' シェア' },
  'wallet.no_equity_held': { zh: '您当前未持有任何音乐版权股权，快去共创市集看看吧！', en: 'You do not hold any music equity. Go check the co-creation market!', ja: '現在音楽持分を保有していません。共創マーケットをチェックしましょう！' },
  'wallet.top_up_fiat': { zh: '极速充值积分', en: 'Quick Top Up', ja: 'クイックチャージ' },
  'wallet.top_up_success': { zh: '充值成功！', en: 'Top-up Successful!', ja: 'チャージ成功！' },
  'wallet.top_up_success_desc': { zh: '您的充值金额已通过安全支付渠道到账，余额已实时更新。', en: 'Your payment was processed successfully. Balance updated in real-time.', ja: '決済が正常に処理されました。残高がリアルタイムで更新されました。' },
  'wallet.top_up_warning': { zh: '注意：当前处于内测阶段，支付仅做测试仿真体验。', en: 'Note: Current phase is beta test. Payments are simulated.', ja: '注意：現在はベータテスト段階です。支払いはシミュレーションされます。' },
  'wallet.select_preset': { zh: '选择快捷充值额度', en: 'Select preset amount', ja: 'クイックチャージ金額を選択' },
  'wallet.input_amount': { zh: '输入自定义金额', en: 'Enter custom amount', ja: 'カスタム金額を入力' },
  'wallet.payment_gateway': { zh: '选择支付通道', en: 'Select Payment Gateway', ja: '決済方法を選択' },
  'wallet.stripe_processing': { zh: '正在调用 Stripe 结算网关...', en: 'Processing via Stripe gateway...', ja: 'Stripe決済を処理中...' },
  'wallet.pay_now': { zh: '确认支付', en: 'Confirm Payment', ja: '支払いを確定' },
  'wallet.transactions_log': { zh: '收益与充值流水', en: 'Earnings & Transactions Log', ja: '収益＆トランザクションログ' },
  'wallet.no_records': { zh: '暂无交易流水记录', en: 'No transaction records found', ja: 'トランザクション記録はありません' },
  'wallet.tx_type_listen': { zh: '听歌挖矿收益', en: 'Listen Mining Reward', ja: 'リスニングマイニング報酬' },
  'wallet.tx_type_upload': { zh: '作品发行收益', en: 'Music Publishing Reward', ja: '音楽配信報酬' },
  'wallet.tx_type_invite': { zh: '邀请好友奖励', en: 'Referral Reward', ja: '紹介報酬' },
  'wallet.tx_type_gift': { zh: '系统赠送福利', en: 'System Gift', ja: 'システムギフト' },
  'wallet.tx_type_dividend_pool': { zh: '版权分红发放', en: 'Copyright Dividend Distribution', ja: '著作権配当分配' },
  'wallet.tx_type_dividend_payout': { zh: '版权持有收益', en: 'Copyright Holding Dividend', ja: '著作権持分配当' },
  'wallet.tx_type_download': { zh: '付费下载扣减', en: 'Paid Download Cost', ja: '有料ダウンロード費用' },
  'wallet.tx_unknown': { zh: '其他流水记录', en: 'Other transaction record', ja: 'その他トランザクション' },
  'wallet.tx_song': { zh: '关联歌曲', en: 'Related Song', ja: '関連曲' },
  'wallet.settled': { zh: '已入账', en: 'Settled', ja: '決済済み' },
};
export const useLanguageStore = create<LanguageState>()(
  persist(
    (set, get) => ({
      language: 'zh',
      setLanguage: (lang) => set({ language: lang }),
      t: (key) => {
        const lang = get().language;
        return translations[key]?.[lang] || key;
      },
    }),
    {
      name: 'echo-language-storage',
    }
  )
);
