import { create } from 'zustand';
import { persist } from 'zustand/middleware';

interface LanguageState {
  language: 'zh' | 'en' | 'ja';
  setLanguage: (lang: 'zh' | 'en' | 'ja') => void;
  t: (key: string) => string;
}

export const translations: Record<string, { zh: string; en: string; ja: string }> = {
  // AUTH namespace
  'auth.access_password': { zh: '访问密码', en: 'Password', ja: 'パスワード' },
  'auth.and': { zh: '与', en: 'and', ja: 'および' },
  'auth.back_to_login': { zh: '返回登录', en: 'Back to Login', ja: 'ログインに戻る' },
  'auth.create_account': { zh: '创建账号', en: 'Create Account', ja: 'アカウント作成' },
  'auth.email': { zh: '邮箱地址', en: 'Email Address', ja: 'メールアドレス' },
  'auth.email_tab': { zh: '邮箱账号', en: 'Email Account', ja: 'メールアカウント' },
  'auth.enter_otp': { zh: '请输入验证码', en: 'Enter OTP', ja: 'OTPを入力' },
  'auth.forgot_pwd': { zh: '忘记密码？', en: 'Forgot Password?', ja: 'パスワードを忘れた？' },
  'auth.get_otp': { zh: '获取验证码', en: 'Get OTP', ja: 'OTPを取得' },
  'auth.get_otp_first': { zh: '请先获取验证码', en: 'Get OTP first', ja: '先にOTPを取得' },
  'auth.has_account': { zh: '已有账号？点击登录', en: 'Have an account? Login', ja: 'アカウントがある？ログイン' },
  'auth.invite_bonus': { zh: '双方均得奖励', en: 'Both get rewards', ja: '両方が報酬を受け取る' },
  'auth.invite_code': { zh: '邀请码 (选填)', en: 'Invite Code (optional)', ja: '招待コード (任意)' },
  'auth.invite_placeholder': { zh: '请输入邀请码 (选填)', en: 'Enter invite code (optional)', ja: '招待コードを入力 (任意)' },
  'auth.join_community': { zh: '加入民主化音乐社区，共享创作收益', en: 'Join the democratized music community, share creative earnings', ja: '民主化された音楽コミュニティに参加し、クリエイティブ収益を共有' },
  'auth.join_echorura': { zh: '开启 ECHORURA', en: 'Join ECHORURA', ja: 'ECHORURAに参加' },
  'auth.logging_in': { zh: '正在登录...', en: 'Logging in...', ja: 'ログイン中...' },
  'auth.login_now': { zh: '立即登录', en: 'Login Now', ja: '今すぐログイン' },
  'auth.login_or_register': { zh: '立即登录', en: 'Login', ja: 'ログイン' },
  'auth.new_password': { zh: '设置新密码 (不低于6位)', en: 'New Password (min 6 chars)', ja: '新しいパスワード (6文字以上)' },
  'auth.no_account': { zh: '还没有账号？点击注册', en: 'Don\'t have an account? Sign up', ja: 'アカウントがない？登録する' },
  'auth.password': { zh: '登录密码', en: 'Password', ja: 'パスワード' },
  'auth.phone_login': { zh: '手机号登录', en: 'Phone Login', ja: '電話番号でログイン' },
  'auth.phone_login_desc': { zh: '使用手机号与密码登录极声', en: 'Login with phone number and password', ja: '電話番号とパスワードでログイン' },
  'auth.phone_number': { zh: '手机号码', en: 'Phone Number', ja: '電話番号' },
  'auth.phone_recover_desc': { zh: '填写手机号并验证以重置密码', en: 'Enter phone number and verify to reset password', ja: '電話番号を入力して確認しパスワードをリセット' },
  'auth.phone_register': { zh: '手机号注册', en: 'Phone Register', ja: '電話番号で登録' },
  'auth.phone_register_desc': { zh: '填写手机号与密码，获取验证码激活', en: 'Enter phone number and password, get OTP to activate', ja: '電話番号とパスワードを入力してOTPを取得' },
  'auth.phone_tab': { zh: '手机号账号', en: 'Phone Account', ja: '電話番号アカウント' },
  'auth.recover_pwd': { zh: '找回密码', en: 'Recover Password', ja: 'パスワード回復' },
  'auth.register_now': { zh: '立即注册', en: 'Register Now', ja: '今すぐ登録' },
  'auth.registering': { zh: '注册中...', en: 'Registering...', ja: '登録中...' },
  'auth.resend_countdown': { zh: 's 后重新获取', en: 's to resend', ja: '秒後に再送信' },
  'auth.reset_login': { zh: '重置密码并登录', en: 'Reset & Login', ja: 'リセットしてログイン' },
  'auth.resetting': { zh: '重置中...', en: 'Resetting...', ja: 'リセット中...' },
  'auth.set_password': { zh: '自设密码 (不低于6位)', en: 'Set Password (min 6 chars)', ja: 'パスワード設定 (6文字以上)' },
  'auth.sms_code': { zh: '短信验证码', en: 'SMS Code', ja: 'SMS認証コード' },
  'auth.terms_agree': { zh: '注册即代表您同意', en: 'By registering you agree to the', ja: '登録することで以下に同意します：' },
  'auth.welcome_back': { zh: '欢迎回来', en: 'Welcome Back', ja: 'おかえりなさい' },
  'auth.or_continue_with': { zh: '或者使用以下方式继续', en: 'Or continue with', ja: 'または以下で続行' },

  // COMMON namespace
  'common.cancel': { zh: '取消', en: 'Cancel', ja: 'キャンセル' },
  'common.confirm': { zh: '确认', en: 'Confirm', ja: '確認' },
  'common.just_now': { zh: '刚刚', en: 'Just now', ja: 'たった今' },
  'common.login_required': { zh: '请先登录', en: 'Please log in first', ja: '先にログインしてください' },
  'common.me': { zh: '我', en: 'Me', ja: '自分' },

  // COMMUNITY namespace
  'community.assembly': { zh: '议事厅', en: 'Assembly', ja: '議事堂' },
  'community.desc': { zh: '民主决策、创作共鸣与权益交易的枢纽中心', en: 'Hub for democratic decisions, creative resonance and equity trading', ja: '民主的決定、創作の共鳴、株式取引のハブセンター' },
  'community.empty': { zh: '荒野之中，虚位以待... 成为第一个发言的人吧！', en: 'No posts yet. Be the first to speak!', ja: 'まだ投稿はありません。最初に投稿しましょう！' },
  'community.equity_distributed': { zh: '权益已分发', en: 'Equity Distributed', ja: '権益配布済み' },
  'community.equity_sold': { zh: '% 权益售出', en: '% equity sold', ja: '% 権益売却' },
  'community.ipo_progress': { zh: 'IPO 进度', en: 'IPO Progress', ja: 'IPO 進捗' },
  'community.login_btn': { zh: '立即登录', en: 'Log In Now', ja: '今すぐログイン' },
  'community.login_only': { zh: '仅限已登录用户发表', en: 'Logged-in users only', ja: 'ログインユーザーのみ投稿可能' },
  'community.login_placeholder': { zh: '只有登录后才能发表动态，快去登录吧！', en: 'Please log in to post updates.', ja: 'ログインすると投稿できます。' },
  'community.market': { zh: '市场', en: 'Market', ja: 'マーケット' },
  'community.no_comments': { zh: '荒野之中，虚位以待... 来抢沙发吧！', en: 'No comments yet. Be the first!', ja: 'まだコメントはありません。最初に！' },
  'community.placeholder_assembly': { zh: '发起一个民主提案...', en: 'Propose a democratic initiative...', ja: '民主的な提案を発議...' },
  'community.placeholder_square': { zh: '分享你的创作灵感...', en: 'Share your creative inspiration...', ja: '創作のインスピレーションを共有...' },
  'community.post': { zh: '发布动态', en: 'Post', ja: '投稿' },
  'community.publish': { zh: '发布动态', en: 'Publish Post', ja: '投稿する' },
  'community.publishing': { zh: '发布中...', en: 'Publishing...', ja: '投稿中...' },
  'community.raising': { zh: '正在募集', en: 'Raising', ja: '募集中' },
  'community.reply': { zh: '回复讨论', en: 'Reply', ja: '返信' },
  'community.reply_login': { zh: '登录后即可参与讨论...', en: 'Login to join the discussion...', ja: 'ログインして議論に参加...' },
  'community.reply_placeholder': { zh: '写下你的回复...', en: 'Write a reply...', ja: '返信を書く...' },
  'community.send': { zh: '发送', en: 'Send', ja: '送信' },
  'community.sending': { zh: '发送中...', en: 'Sending...', ja: '送信中...' },
  'community.shares_left_c': { zh: '剩余', en: 'Left', ja: '残り' },
  'community.square': { zh: '广场', en: 'Square', ja: '広場' },
  'community.title': { zh: 'ECHORURA 社区', en: 'ECHORURA Community', ja: 'ECHORURAコミュニティ' },

  // COMPLIANCE namespace
  'compliance.app_name_global': { zh: '极声音乐 Global', en: 'ECHORURA Global', ja: 'ECHORURA Global' },
  'compliance.app_name_hk': { zh: '极声音乐 (ECHORURA HK)', en: 'ECHORURA HK', ja: 'ECHORURA HK' },
  'compliance.app_name_sg': { zh: 'ECHORURA SG', en: 'ECHORURA SG', ja: 'ECHORURA SG' },
  'compliance.equity_global': { zh: '版权股权 (Music Equity)', en: 'Music Equity', ja: '音楽著作権持分' },
  'compliance.equity_hk': { zh: '共创共享权益', en: 'Co-Curation Equity', ja: '共創共有持分' },
  'compliance.equity_sg': { zh: '粉丝成就徽章 (Fan Badges)', en: 'Fan Badges', ja: 'ファンバッジ' },
  'compliance.fiat_exchange_rate_global': { zh: '1.00 USD = 10.00 ECHO 代币', en: '1.00 USD = 10.00 ECHO Token', ja: '1.00 USD = 10.00 ECHOトークン' },
  'compliance.fiat_exchange_rate_hk': { zh: '10.00 HKD = 10.00 ECHO 社区积分', en: '10.00 HKD = 10.00 ECHO Community Points', ja: '10.00 HKD = 10.00 ECHOコミュニティポイント' },
  'compliance.fiat_exchange_rate_sg': { zh: '1.50 SGD = 10.00 ECHO 代币', en: '1.50 SGD = 10.00 ECHO Token', ja: '1.50 SGD = 10.00 ECHOトークン' },
  'compliance.token_global': { zh: 'ECHO Token', en: 'ECHO Token', ja: 'ECHOトークン' },
  'compliance.token_hk': { zh: 'ECHO 社区积分', en: 'ECHO Community Points', ja: 'ECHOコミュニティポイント' },
  'compliance.token_sg': { zh: 'ECHO Token', en: 'ECHO Token', ja: 'ECHOトークン' },

  // DISCOVER namespace
  'discover.add_playlist': { zh: '收录到歌单', en: 'Add to Playlist', ja: 'プレイリストに追加' },
  'discover.ai_pass': { zh: 'AI 首性质检通过', en: 'AI Quality Check Passed', ja: 'AI品質チェック通過' },
  'discover.ai_score': { zh: 'AI 评分:', en: 'AI Score:', ja: 'AIスコア：' },
  'discover.all_qualify': { zh: '🛡️ 全员上榜', en: '🛡️ All qualify', ja: '🛡️ 全員通過' },
  'discover.arena': { zh: '听审竞技场', en: 'Curation Arena', ja: 'キュレーションアリーナ' },
  'discover.arena_title': { zh: '听审竞技场', en: 'Curation Arena', ja: 'キュレーションアリーナ' },
  'discover.artist_label': { zh: '艺人:', en: 'Artist:', ja: 'アーティスト：' },
  'discover.clear_filters': { zh: '清除所有筛选', en: 'Clear All Filters', ja: 'すべてのフィルターをクリア' },
  'discover.creator_channel': { zh: '创作者极速报名通道 (Creator Registration Channel)', en: 'Creator Fast-Register Channel', ja: 'クリエイター高速登録通道' },
  'discover.dao_badge': { zh: 'DAO 社区听审投票机制', en: 'DAO Community Curation', ja: 'DAOコミュニティキュレーション' },
  'discover.dashboard': { zh: '本轮对决数值仪表盘', en: 'Round Dashboard', ja: 'ラウンドダッシュボード' },
  'discover.day1_desc': { zh: '当前处于「质押报名期」。创作者可质押 10.00 ECHO 为自己的原创歌曲报名参赛。每日参赛限制前 20 首。报名成功的作品将于今晚 24:00 自动进入投票环节。', en: 'Currently in Registration Day. Creators stake 10 ECHO to enter. Daily limit: 20 songs. Registered songs enter voting at midnight.', ja: '現在登録期間中。クリエイターは10 ECHOをステークして参加可能。1日制限：20曲。登録曲は深夜0時に投票フェーズに移行。' },
  'discover.day1_label': { zh: '今日质押报名期', en: 'Today: Registration Day', ja: '今日：登録日' },
  'discover.day2_desc': { zh: '以下歌曲今日开放公众投票。每位用户可对每首歌曲进行一次「支持」或「反对」打分。当日 24:00 截止，得票最多的前10首将晋级首页推荐！', en: 'Songs below are open for public voting. Each user can vote once per song. Deadline: midnight. Top 10 will be featured on the homepage!', ja: '以下の曲が一般投票に公開されています。各ユーザーは1曲につき1回投票可能。締切：深夜0時。上位10曲がホームページに掲載！' },
  'discover.day2_label': { zh: '今日待投票金曲', en: 'Today: Voting Day', ja: '今日：投票日' },
  'discover.day3_desc': { zh: '✅ 今日投票已于 24:00 截止。本批次结算完成，胜出曲目已同步至首页「今日推荐榜」。感谢所有参与投票的听审会员！', en: '✅ Voting closed at midnight. Results settled. Winners synced to homepage. Thank you all voters!', ja: '✅ 投票は深夜0時に締め切られました。結果確定。勝者はホームページに表示。ありがとう！' },
  'discover.day3_label': { zh: '今日已结算榜单', en: 'Today: Results Day', ja: '今日：結果発表' },
  'discover.deadline': { zh: '截止: 当日 24:00', en: 'Deadline: Midnight', ja: '締切：深夜0時' },
  'discover.default_playlist_desc': { zh: '由极声共创创作者精选分享的声学合辑。', en: 'A curated acoustic collection by ECHORURA co-creators.', ja: 'ECHORURAの共同クリエイターがキュレーションしたアコースティックコレクション。' },
  'discover.echorura_user': { zh: '极声用户', en: 'ECHORURA User', ja: 'ECHORURAユーザー' },
  'discover.genre': { zh: '音乐风格 (Genre)', en: 'Music Genre', ja: '音楽ジャンル' },
  'discover.genre_cyber': { zh: '赛博', en: 'Cyber', ja: 'サイバー' },
  'discover.genre_joy': { zh: '喜悦', en: 'Joy', ja: '喜び' },
  'discover.genre_party': { zh: '派对', en: 'Party', ja: 'パーティー' },
  'discover.genre_pop': { zh: '流行', en: 'Pop', ja: 'ポップ' },
  'discover.goto_profile': { zh: '前往个人中心发布并质押报名', en: 'Go to Profile to publish & register', ja: 'プロフィールで公開して登録する' },
  'discover.live_duels': { zh: '🔥 本日待投票对决金曲 (Live Voting Duels)', en: '🔥 Today\'s Live Voting Duels', ja: '🔥 本日の投票対決曲' },
  'discover.loser_msg': { zh: '🔽 抱歉落榜淘汰：未能杀入本批次前 10。作品以普通身份上架曲库；您的 10.00 ECHO 保证金已被收回充公，作为伯乐奖励均分给了参与投票的听审会员。', en: '🔽 Not qualified: Did not make top 10. Song listed normally. 10 ECHO stake forfeited and split among voters.', ja: '🔽 不通過：上位10入りならず。曲は通常掲載。10 ECHOのステークは没収され投票者に均等分配。' },
  'discover.loser_settled': { zh: '已结算：淘汰未通过', en: 'Settled: Eliminated', ja: '決済済み：脱落' },
  'discover.main_stage': { zh: '探索主舞台', en: 'Main Stage', ja: 'メインステージ' },
  'discover.no_duel': { zh: '🔘 暂无对决', en: '🔘 No duels', ja: '🔘 対決なし' },
  'discover.no_duel_desc': { zh: '今日暂无处于对决中的听审曲目。每日 0:00 会将报名的歌曲自动转移至此进行投票！', en: 'No songs in duel today. Songs are moved here automatically at midnight!', ja: '本日対決中の曲はありません。登録曲は毎日深夜0時に自動的にここに移行します！' },
  'discover.no_duel_songs': { zh: '暂无对决作品', en: 'No duel songs', ja: '対決曲なし' },
  'discover.no_playlists': { zh: '🌌 暂未发掘到公开的精选推荐歌单', en: '🌌 No featured playlists found yet', ja: '🌌 おすすめプレイリストはまだありません' },
  'discover.no_results': { zh: '暂时没有找到匹配的作品，换个心情试试？', en: 'No matching songs found, try another mood?', ja: '一致する曲が見つかりません。別のムードを試してください？' },
  'discover.no_songs': { zh: '暂无歌曲', en: 'No Songs', ja: '曲なし' },
  'discover.no_songs_to_register': { zh: '您当前没有待报名的原创歌曲。上传并发布您的第一首原创歌曲（或等今日报名期结束后明天再投），即可在此通道质押 10.00 ECHO 报名参赛！', en: 'No songs ready to register. Upload your first original song (or try again tomorrow after registration closes) and stake 10 ECHO to compete!', ja: '登録可能な曲はありません。最初のオリジナル曲をアップロード（または本日の登録終了後に明日再試行）し、10 ECHOをステークして競争に参加！' },
  'discover.pending': { zh: '⚠️ 待定', en: '⚠️ Pending', ja: '⚠️ 保留中' },
  'discover.play_count': { zh: '次收听', en: 'plays', ja: '再生' },
  'discover.playlists': { zh: '精选推荐歌单 (Featured Playlists)', en: 'Featured Playlists', ja: 'おすすめプレイリスト' },
  'discover.protect_msg': { zh: '🛡️ 保护机制生效：本批次不足 10 首，作品无淘汰成功晋级首页「本日推荐榜」！根据 DAO 协议，您的 10.00 ECHO 保证金已转为社区伯乐激励均分给听审员。', en: '🛡️ Protection active: Fewer than 10 songs this round, all qualify for homepage! Per DAO protocol, your 10 ECHO stake is split among voters as reward.', ja: '🛡️ 保護発動：今回は10曲未満のため全曲がホームページに掲載！DAOプロトコルに従い、10 ECHOのステークは投票者に均等分配。' },
  'discover.qualified': { zh: '✅ 上榜圈', en: '✅ Qualified', ja: '✅ 通過' },
  'discover.queue_empty_desc': { zh: '今日还没有任何作品报名听审竞技场。赶快成为首个发起质押报名的创作者吧！', en: 'No songs registered today. Be the first creator to stake and register!', ja: '本日登録された曲はありません。最初にステークして登録するクリエイターになりましょう！' },
  'discover.queue_empty_title': { zh: '今日报名队列为空', en: 'Registration queue is empty', ja: '登録キューは空です' },
  'discover.queue_full': { zh: '当前已满:', en: 'Currently full:', ja: '現在満員：' },
  'discover.queue_locked_msg': { zh: '🔒 队列锁定中：该作品已成功完成质押排队。每天 0:00 将会自动转移到上方对决投票区开启 24 小时公开听审。', en: '🔒 Queued: Song staked successfully. It will move to the voting area at midnight for 24h public curation.', ja: '🔒 キュー中：曲のステーク完了。毎日深夜0時に投票エリアに移動し24時間の公開キュレーションが始まります。' },
  'discover.queue_status': { zh: '报名队列状态:', en: 'Queue Status:', ja: 'キュー状態：' },
  'discover.queue_title': { zh: '🔒 今日已报名待流转队列 (Registered Queue)', en: '🔒 Today\'s Registered Queue', ja: '🔒 本日登録済みキュー' },
  'discover.queued': { zh: '🔒 排队中', en: '🔒 Queued', ja: '🔒 キュー中' },
  'discover.rank_rule': { zh: '上榜规则:', en: 'Ranking Rule:', ja: 'ランキングルール：' },
  'discover.settled': { zh: '🏆 往期对决已结算金曲 (Previous Settled Winners)', en: '🏆 Previous Settled Winners', ja: '🏆 過去の決済勝者' },
  'discover.sink': { zh: '下沉 (Down)', en: 'Sink (Down)', ja: '沈める (Down)' },
  'discover.songs_count': { zh: '首歌曲', en: 'songs', ja: '曲' },
  'discover.songs_today': { zh: '今日待决金曲:', en: 'Today\'s Songs:', ja: '今日の曲数：' },
  'discover.soul_state': { zh: '灵魂状态 (Soul State)', en: 'Soul State', ja: 'ソウルステート' },
  'discover.stake_locked': { zh: '10.00 ECHO 质押锁仓中 🔒', en: '10.00 ECHO Staked & Locked 🔒', ja: '10.00 ECHO ステーク＆ロック中 🔒' },
  'discover.stake_register': { zh: '💎 质押 10 ECHO 报名参赛', en: '💎 Stake 10 ECHO to Register', ja: '💎 10 ECHOをステークして登録' },
  'discover.staking': { zh: '正在质押报名...', en: 'Staking...', ja: 'ステーク中...' },
  'discover.support': { zh: '支持 (Up)', en: 'Support (Up)', ja: 'サポート (Up)' },
  'discover.support_votes': { zh: '支持得票:', en: 'Support Votes:', ja: 'サポート票数：' },
  'discover.top10': { zh: '🔥 前10首上榜', en: '🔥 Top 10 qualify', ja: '🔥 上位10曲通過' },
  'discover.voted': { zh: '已打分', en: 'Voted', ja: '投票済み' },
  'discover.votes': { zh: '票', en: 'votes', ja: '票' },
  'discover.voting_closed': { zh: '🔒 投票已截止', en: '🔒 Voting Closed', ja: '🔒 投票終了' },
  'discover.waiting_duel': { zh: '等待明日对决', en: 'Awaiting Tomorrow\'s Duel', ja: '明日の対決を待機中' },
  'discover.waiting_transfer': { zh: '等待明日 0:00 流转开启对决', en: 'Waiting for midnight to start duel', ja: '深夜0時の対決開始を待機中' },
  'discover.winner_msg': { zh: '🏆 竞选挑战成功：歌曲在激烈比拼中挺进前 10！已自动登上极声主页「今日推荐榜」黄金资源位，且 10.00 ECHO 保证金全额退还！', en: '🏆 Challenge success: Song made top 10! Featured on homepage & 10 ECHO stake refunded!', ja: '🏆 挑戦成功：曲が上位10入り！ホームページに掲載、10 ECHOのステークも返還！' },
  'discover.winner_settled': { zh: '已结算：晋级上榜', en: 'Settled: Promoted', ja: '決済済み：昇格' },

  // GENRE namespace
  'genre.acg': { zh: '二次元', en: 'ACG', ja: 'アニメ・ゲーム' },
  'genre.alternative': { zh: '另类独立', en: 'Alternative', ja: 'オルタナティブ' },
  'genre.ambient': { zh: '氛围放松', en: 'Ambient', ja: 'アンビエント' },
  'genre.china': { zh: '国风', en: 'Chinese Style', ja: '中国風' },
  'genre.classical': { zh: '古典', en: 'Classical', ja: 'クラシック' },
  'genre.electro': { zh: '电子舞曲', en: 'Electronic', ja: 'エレクトロ' },
  'genre.folk': { zh: '民谣', en: 'Folk', ja: 'フォーク' },
  'genre.hiphop': { zh: '嘻哈', en: 'Hip-Hop', ja: 'ヒップホップ' },
  'genre.jazz': { zh: '爵士', en: 'Jazz', ja: 'ジャズ' },
  'genre.pop': { zh: '流行', en: 'Pop', ja: 'ポップ' },
  'genre.rock': { zh: '摇滚', en: 'Rock', ja: 'ロック' },
  'genre.soul': { zh: '灵魂乐', en: 'Soul', ja: 'ソウル' },
  'genre.soundtrack': { zh: '影视原声', en: 'Soundtrack', ja: 'サウンドトラック' },

  // HERO namespace
  'hero.desc': { 
    zh: 'ECHORURA是基于WEB3技术的去中心化音乐社区。在 ECHORURA，创作与收听都是在挖掘价值。让音乐回归民众，让收益归于听众与创作者。', 
    en: 'ECHORURA is a decentralized music community based on Web3 technology. At ECHORURA, both creation and listening are mining value. Return music to the people, and rewards to listeners and creators.', 
    ja: 'ECHORURAはWeb3技術に基づいた分散型音楽コミュニティです。ECHORURAでは、創作とリスニングの両方が価値をマイニングしています。音楽を人々に返し、報酬をリスナーとクリエイターに還元します。' 
  },
  'hero.ipo_info': { zh: '共创音乐市集', en: 'Co-Curation Market', ja: 'マーケットへ' },
  'hero.start': { zh: '开启音乐之旅', en: 'Start Music Journey', ja: '音楽の旅を始める' },
  'hero.title': { zh: '创作与收听，皆为价值', en: 'CREATION & LISTENING, ALL ARE VALUE', ja: '創作とリスニング、すべてに価値がある' },

  // HOME namespace
  'home.creator_fans': { zh: '近期粉丝: +', en: 'New Fans: +', ja: '新規ファン: +' },
  'home.creator_score': { zh: '热度:', en: 'Score:', ja: 'スコア:' },
  'home.dao_badge': { zh: '🏆 DAO 听审认证', en: '🏆 DAO Certified', ja: '🏆 DAO 公認' },
  'home.empty_arena': { zh: '今日听审擂台暂无胜出金曲，快去发现页投票，或者上传你的歌曲吧！', en: 'No winners in today\'s Arena yet. Go vote on Discover, or upload your song!', ja: '今日のアリーナにはまだ勝者がいません。発見ページで投票するか、あなたの曲をアップロードしましょう！' },
  'home.empty_hot': { zh: '当前还没有热播歌曲，上传您的音乐开启播放收益吧！', en: 'No hot plays yet. Upload your music to start earning!', ja: '急上昇曲はまだありません。音楽をアップロードして収益を得ましょう！' },
  'home.empty_join': { zh: '等你加入', en: 'Be the First!', ja: 'あなたが最初に！' },
  'home.empty_new': { zh: '当前暂无新发布歌曲，上传并分享您的第一首原创音乐！', en: 'No new releases yet. Upload and share your first original music!', ja: '新着リリースはまだありません。最初のオリジナル音楽をアップロードして共有しましょう！' },
  'home.empty_trending': { zh: '当前没有被发现的歌曲，快去上传第一首吧！', en: 'No trending songs yet. Upload the first one!', ja: 'トレンド曲はまだありません。最初の曲をアップロードしましょう！' },
  'home.follow': { zh: '关注', en: 'Follow', ja: 'フォロー' },
  'home.hot_plays': { zh: '本日热播 TOP10', en: 'Today\'s Hot Plays TOP10', ja: '本日急上昇 TOP10' },
  'home.new_releases': { zh: '新歌速递', en: 'New Releases', ja: '新着リリース' },
  'home.play_count': { zh: '次收听', en: 'plays', ja: '再生' },
  'home.rising_artists': { zh: '新锐艺人 TOP10', en: 'Rising Artists TOP10', ja: '急上昇アーティスト TOP10' },
  'home.stat_active_nodes': { zh: '活跃创作者节点', en: 'Active Creator Nodes', ja: 'アクティブクリエイターノード' },
  'home.stat_community_share': { zh: '社区分润率', en: 'Community Revenue Share', ja: 'コミュニティ収益分配率' },
  'home.stat_decentralized': { zh: '● 去中心化节点认证', en: '● Decentralized Node Certified', ja: '● 分散型ノード認証' },
  'home.stat_listen_rewards': { zh: '全网累计收听奖励', en: 'Total Listen Rewards', ja: '累計リスニング報酬' },
  'home.stat_profit_back': { zh: '● 100% 利润社区回馈', en: '● 100% Profit Returned to Community', ja: '● 100% 利益をコミュニティに還元' },
  'home.stat_smart_contract': { zh: '● 智能合约实时结算', en: '● Smart Contract Settlement', ja: '● スマートコントラクト決済' },
  'home.top_picks': { zh: '本日推荐金曲 TOP10', en: 'Today\'s Top Picks', ja: '本日おすすめ TOP10' },
  'home.trending': { zh: '热门发现', en: 'Trending Discoveries', ja: 'トレンド発見' },
  'home.unknown_creator': { zh: '极声创作者', en: 'ECHORURA Creator', ja: 'ECHORURAクリエイター' },
  'home.view_all': { zh: '查看全部 →', en: 'View All →', ja: '全て見る →' },
  'home.visit_profile': { zh: '去主页关注', en: 'Visit Profile', ja: 'プロフィールを見る' },

  // MARKET namespace
  'market.aa_wallet_balance': { zh: '您的 AA 智能钱包余额', en: 'Your AA Smart Wallet Balance', ja: 'AAスマートウォレット残高' },
  'market.active_ipos': { zh: '正在募集中', en: 'Active IPOs', ja: '募集中' },
  'market.available_credit': { zh: '当前可用', en: 'Available Credit', ja: '現在の利用可能額' },
  'market.co_creation_market': { zh: '共创共享市集', en: 'Co-Curation Market', ja: '共創マーケット' },
  'market.confirm_curation_support': { zh: '确认参与共创共享', en: 'Confirm Curation Support', ja: '共同制作支援を確定する' },
  'market.confirm_support': { zh: '确认支持', en: 'Confirm Support', ja: '支援を確認' },
  'market.cost_per_share': { zh: '单价', en: 'Price per Share', ja: '単価/シェア' },
  'market.curation_payment': { zh: '共创支持付款', en: 'Curation Payment', ja: '共創支援支払い' },
  'market.curation_shares': { zh: '认购份额', en: 'Curation Shares', ja: '購入シェア数' },
  'market.curation_success': { zh: '共创支持成功！', en: 'Curation Support Success!', ja: '共創支援に成功しました！' },
  'market.desc_earn': { zh: '永久分享该歌曲产生的每一次收听奖励。', en: 'Earn a share of every listening reward permanently.', ja: 'その曲が再生されるたびに発生する報酬を永続的に共有します。' },
  'market.desc_equity_detail_1': { zh: '认购完成后，您将直接持有该歌曲在去中心化网络中的分红权。', en: 'Once subscribed, you will directly hold the dividend rights of the song in the decentralized network.', ja: '購入完了後、分散型ネットワーク内における該当楽曲の配当権を直接保有します。' },
  'market.desc_equity_detail_2': { zh: '收益将通过智能合约自动结算至您的账户。', en: 'Earnings will be automatically settled to your account via smart contracts.', ja: '収益はスマートコントラクトを介して自動的にアカウントに決済されます。' },
  'market.desc_ipo': { zh: '创作者将其作品的部分收益权（股权）进行公开募集。', en: 'Creators raise funds by offering equity of their works.', ja: 'クリエイターが作品の収益権（株式）の一部を公開募集します。' },
  'market.desc_trust_contract': { zh: '该项目由智能合约自动托管与执行。', en: 'This project is automatically managed and executed by smart contracts.', ja: 'このプロジェクトはスマートコントラクトによって自動的に管理および実行されます。' },
  'market.equity': { zh: '权益', en: 'Equity', ja: '持分' },
  'market.funded': { zh: '已募集', en: 'Funded', ja: '募集完了' },
  'market.header_subtitle': { zh: '发现优质音乐，参与共创，分享链上播放红利', en: 'Discover quality music, participate in co-creation, and share on-chain streaming dividends', ja: '優れた音楽を発見し、共創に参加して、オンチェーン再生の配当を共有します' },
  'market.header_title': { zh: '共创音乐市集', en: 'Co-Curation Market', ja: '共創音楽マーケット' },
  'market.no_active_songs': { zh: '当前没有正在募集中或已经结束的项目', en: 'No active or completed projects currently', ja: '現在募集中のプロジェクトはありません' },
  'market.preview': { zh: '试听', en: 'Preview', ja: '試聴' },
  'market.shares_left': { zh: '剩余份额', en: 'Shares Left', ja: '残りシェア' },
  'market.shares_left_format': { zh: '剩余 {shares} 股', en: '{shares} Shares Left', ja: '残り {shares} シェア' },
  'market.sold_out': { zh: '已售罄', en: 'Sold Out', ja: '完売' },
  'market.support_now': { zh: '立即支持', en: 'Support Now', ja: '今すぐ支援' },
  'market.support_progress': { zh: '支持进度', en: 'Support Progress', ja: '支援進捗' },
  'market.title': { zh: '什么是音乐 IPO?', en: 'What is Music IPO?', ja: '音楽IPOとは？' },
  'market.toast_confirm_metamask': { zh: '请在 MetaMask 钱包中确认交易', en: 'Please confirm the transaction in MetaMask wallet', ja: 'MetaMaskウォレットでトランザクションを確認してください' },
  'market.toast_curation_success_1': { zh: '成功认购 ', en: 'Successfully subscribed to ', ja: 'の購入に成功しました：' },
  'market.toast_curation_success_2': { zh: ' 份份额！', en: ' shares!', ja: ' シェア！' },
  'market.toast_curation_success_3': { zh: '已计入您的资产中心。', en: 'Has been added to your Asset Center.', ja: 'アセットセンターに追加されました。' },
  'market.toast_insufficient_balance': { zh: '账户余额不足！请充值或切换至信用额度代付。', en: 'Insufficient account balance! Please top up or switch to Credit Limit payment.', ja: 'アカウント残高が不足しています！チャージするか信用枠払いに切り替えてください。' },
  'market.toast_insufficient_credit': { zh: '信用额度不足！请使用余额或充值。', en: 'Insufficient credit limit! Please use balance or top up.', ja: '信用枠が不足しています！残高を使用するか、チャージしてください。' },
  'market.toast_network_error': { zh: '网络错误，请稍后重试', en: 'Network error, please try again later', ja: 'ネットワークエラーが発生しました。後で再試行してください' },
  'market.toast_not_logged_in': { zh: '请先登录！', en: 'Please log in first!', ja: '先にログインしてください！' },
  'market.toast_payment_failed': { zh: '付款失败：', en: 'Payment failed: ', ja: '支払い失敗：' },
  'market.toast_payment_success': { zh: '付款成功，正在处理交易...', en: 'Payment success, processing transaction...', ja: '支払い成功、トランザクションを処理中...' },
  'market.toast_tx_failed': { zh: '链上代币划转失败！请检查余额或重试。', en: 'On-chain token transfer failed! Check balance or retry.', ja: 'オンチェーンのトークン転送に失敗しました！残高を確認するか再試行してください。' },
  'market.toast_tx_submitted': { zh: '代币划转交易已提交，等待链上确认...', en: 'Token transfer transaction submitted, waiting for confirmation...', ja: 'トークン転送トランザクションが送信されました。確認を待機中...' },
  'market.use_credit_limit': { zh: '使用信用额度支付', en: 'Pay with Credit Limit', ja: '信用枠で支払う' },
  'market.waiting_join': { zh: '等待加入', en: 'Waiting to Join', ja: '参加待機中' },
  'market.wallet_signing': { zh: '正在调用钱包签名...', en: 'Calling wallet signature...', ja: 'ウォレット署名を呼び出し中...' },

  // MOOD namespace
  'mood.focus': { zh: '专注', en: 'Focus', ja: '集中' },
  'mood.healing': { zh: '治愈', en: 'Healing', ja: '癒し' },
  'mood.hot': { zh: '热血', en: 'Energetic', ja: '熱血' },
  'mood.lonely': { zh: '孤独', en: 'Lonely', ja: '孤独' },
  'mood.meditation': { zh: '冥想', en: 'Meditation', ja: '瞑想' },
  'mood.midnight': { zh: '午夜', en: 'Midnight', ja: '真夜中' },
  'mood.relax': { zh: '放松', en: 'Relax', ja: 'リラックス' },
  'mood.sad': { zh: '伤感', en: 'Sad', ja: '悲しい' },
  'mood.sleep': { zh: '助眠', en: 'Sleep', ja: '睡眠' },
  'mood.workout': { zh: '运动', en: 'Workout', ja: 'ワークアウト' },

  // NAV namespace
  'nav.community': { zh: '社区', en: 'Community', ja: 'コミュニティ' },
  'nav.discover': { zh: '发现', en: 'Discover', ja: '発見' },
  'nav.home': { zh: '首页', en: 'Home', ja: 'ホーム' },
  'nav.login': { zh: '登录 / 注册', en: 'Login / Register', ja: 'ログイン / 登録' },
  'nav.logout': { zh: '退出登录', en: 'Logout', ja: 'ログアウト' },
  'nav.profile': { zh: '我的', en: 'Profile', ja: 'プロファイル' },
  'nav.wallet': { zh: '钱包', en: 'Wallet', ja: 'ウォレット' },

  // PLAYER namespace
  'player.add_to_playlist': { zh: '添加至歌单', en: 'Add to Playlist', ja: 'プレイリストに追加' },
  'player.back_to_cover': { zh: '返回封面', en: 'Back to Cover', ja: 'カバーに戻る' },
  'player.clear_queue': { zh: '清空播放队列', en: 'Clear Queue', ja: 'キューをクリア' },
  'player.clear_queue_confirm': { zh: '确定要清空播放队列吗？', en: 'Are you sure you want to clear the playback queue?', ja: '再生キューを空にしますか？' },
  'player.co_creation': { zh: '共创', en: 'Co-Curation', ja: '共創' },
  'player.co_creation_cost_estimate': { zh: '本次共创认购预计可获得该作品约 <strong>{percentage}%</strong> 的版权共有份额及对应的版税分红权。', en: 'This co-creation subscription is estimated to yield approximately <strong>{percentage}%</strong> of the work\'s shared copyright and corresponding royalty dividends.', ja: 'この共創サブスクリプションにより、作品の共有著作権の約 <strong>{percentage}%</strong> と対応するロイヤリティ配当が得られると推定されます。' },
  'player.co_creation_inactive': { zh: '筹备中', en: 'Upcoming', ja: '準備中' },
  'player.co_creator': { zh: '联合创作者', en: 'Co-Creator', ja: '共同制作者' },
  'player.collapse': { zh: '收起', en: 'Collapse', ja: '折りたたむ' },
  'player.comment_failed': { zh: '发表评论失败，请重试', en: 'Failed to post comment, please try again', ja: 'コメントの投稿に失敗しました。再試行してください' },
  'player.comment_placeholder': { zh: '发表你的精彩评论...', en: 'Write a comment...', ja: 'コメントを書く...' },
  'player.comment_submit': { zh: '发送', en: 'Send', ja: '送信' },
  'player.comments': { zh: '评论', en: 'Comments', ja: 'コメント' },
  'player.confirm_download': { zh: '确认下载', en: 'Confirm Download', ja: 'ダウンロード確認' },
  'player.confirm_purchase': { zh: '确认认购', en: 'Confirm Purchase', ja: '購入確認' },
  'player.current_queue': { zh: '播放队列', en: 'Play Queue', ja: '再生キュー' },
  'player.current_song': { zh: '当前播放', en: 'Current Song', ja: '再生中の曲' },
  'player.download': { zh: '下载', en: 'Download', ja: 'ダウンロード' },
  'player.download_cost_desc': { zh: '下载作品《{title}》需要支付 2.00 ECHO 积分（直接分配给创作者与版权合伙人），确认下载吗？', en: 'Downloading "{title}" costs 2.00 ECHO (distributed directly to creators and equity holders). Confirm download?', ja: '作品「{title}」をダウンロードするには2.00 ECHOが必要です（クリエイターおよび持分保有者に直接分配されます）。ダウンロードしますか？' },
  'player.download_started': { zh: '开始下载...', en: 'Download started...', ja: 'ダウンロードを開始しました...' },
  'player.favorite': { zh: '收藏', en: 'Favorite', ja: 'お気に入り' },
  'player.favorite_added': { zh: '已添加至收藏', en: 'Added to favorites', ja: 'お気に入りに追加しました' },
  'player.favorite_removed': { zh: '已从收藏中移除', en: 'Removed from favorites', ja: 'お気に入りから削除しました' },
  'player.insufficient_balance_download': { zh: '余额不足以支付下载费用！', en: 'Insufficient balance for download!', ja: 'ダウンロードするための残高が不足しています！' },
  'player.insufficient_balance_ipo': { zh: '余额不足，无法参与认购！', en: 'Insufficient balance to invest!', ja: '残高不足のため購入できません！' },
  'player.insufficient_shares_ipo': { zh: '剩余份额不足！', en: 'Insufficient shares left!', ja: '残りシェアが不足しています！' },
  'player.invest': { zh: '支持共创', en: 'Invest', ja: '投資' },
  'player.ipo_failed_toast': { zh: '认购失败，请稍后重试', en: 'Investment failed, please try again later', ja: '購入に失敗しました。後で再試行してください' },
  'player.ipo_percentage_label': { zh: '分红比例', en: 'Dividend %', ja: '配当割合' },
  'player.ipo_success_toast': { zh: '认购成功！', en: 'Investment successful!', ja: '購入に成功しました！' },
  'player.ipo_tx_failed_err': { zh: '交易执行失败，请重试', en: 'Transaction failed, please try again', ja: 'トランザクションに失敗しました。再試行してください' },
  'player.like': { zh: '点赞', en: 'Like', ja: 'いいね' },
  'player.login_to_comment': { zh: '请先登录以发表评论', en: 'Please log in to comment', ja: 'コメントするにはログインしてください' },
  'player.login_to_download': { zh: '请先登录以进行下载', en: 'Please log in to download', ja: 'ダウンロードするにはログインしてください' },
  'player.login_to_favorite': { zh: '请先登录以收藏歌曲', en: 'Please log in to favorite songs', ja: 'お気に入り登録するにはログインしてください' },
  'player.lyrics': { zh: '词', en: 'Lyrics', ja: '歌詞' },
  'player.lyrics_synced': { zh: '歌词同步', en: 'Lyrics Synced', ja: '歌詞シンク' },
  'player.max_label': { zh: '最大', en: 'MAX', ja: '最大' },
  'player.metamask_payment_prompt': { zh: '请在 MetaMask 中确认付款...', en: 'Please confirm payment in MetaMask...', ja: 'MetaMaskで支払いを確認してください...' },
  'player.mining': { zh: '听歌挖矿中', en: 'Mining Rewards', ja: 'マイニング報酬中' },
  'player.mining_rate_desc': { zh: '产出速率 1.00 ECHO/分', en: 'Rate: 1.00 ECHO/min', ja: 'レート: 1.00 ECHO/分' },
  'player.play_queue': { zh: '播放队列', en: 'Play Queue', ja: '再生キュー' },
  'player.price_per_share': { zh: '单价', en: 'Price/Share', ja: '単価/シェア' },
  'player.purchase_equity_title': { zh: '认购音乐 IPO 份额', en: 'Purchase Music IPO Shares', ja: '音楽IPOシェアを購入' },
  'player.queue_empty': { zh: '播放队列为空', en: 'Playback queue is empty', ja: '再生キューが空です' },
  'player.remaining_shares_label': { zh: '剩余份额', en: 'Remaining Shares', ja: '残りシェア数' },
  'player.remove_from_queue': { zh: '从队列中移除', en: 'Remove from Queue', ja: 'キューから削除' },
  'player.reviews_title': { zh: '乐评', en: 'Reviews', ja: 'レビュー' },
  'player.share': { zh: '分享', en: 'Share', ja: '共有' },
  'player.share_click_to_listen': { zh: '点击立刻收听', en: 'Click to listen now', ja: 'クリックして今すぐ聴く' },
  'player.share_item': { zh: '分享歌曲', en: 'Share Song', ja: '曲を共有' },
  'player.share_prompt_copied': { zh: '复制成功！', en: 'Copied successfully!', ja: 'コピーに成功しました！' },
  'player.share_prompt_copied_link': { zh: '分享链接已复制到剪贴板！', en: 'Share link copied to clipboard!', ja: '共有リンクをクリップボードにコピーしました！' },
  'player.share_prompt_copied_link_fallback': { zh: '已复制链接，请手动分享', en: 'Link copied, please share manually', ja: 'リンクがコピーされました。手動で共有してください' },
  'player.share_prompt_copied_rt': { zh: '分享文案已复制！', en: 'Share text copied!', ja: '共有テキストをコピーしました！' },
  'player.share_text': { zh: '向你推荐一首在 ECHORURA 上发掘的好歌：《{title}》- {artist}。听歌还能挖矿，快来一起收听吧！', en: 'I recommend a great song I discovered on ECHORURA: "{title}" - {artist}. You can mine rewards while listening, come join me!', ja: 'ECHORURAで見つけた素晴らしい曲をおすすめします：「{title}」- {artist}。聴きながらマイニングもできます、一緒に聴きましょう！' },
  'player.shares_to_buy': { zh: '认购份额', en: 'Shares to Buy', ja: '購入シェア数' },
  'player.shares_unit': { zh: '份', en: 'Shares', ja: 'シェア' },
  'player.total_cost': { zh: '总额', en: 'Total Cost', ja: '合計金額' },
  'player.transferring': { zh: '划转代币中...', en: 'Transferring tokens...', ja: 'トークンを転送中...' },
  'player.tx_failed': { zh: '链上支付失败: ', en: 'On-chain payment failed: ', ja: 'オンチェーン決済失敗: ' },
  'player.tx_submitted_waiting': { zh: '交易已提交，等待链上确认...', en: 'Transaction submitted, waiting for on-chain confirmation...', ja: 'トランザクション送信済み、チェーン上の確認を待機中...' },
  'player.view_lyrics': { zh: '查看歌词', en: 'View Lyrics', ja: '歌詞を見る' },

  // PLAYLIST namespace
  'playlist.add_to_collection': { zh: '收藏到歌单', en: 'Add to Playlist', ja: 'プレイリストに追加' },
  'playlist.added': { zh: '已加入', en: 'Added', ja: '追加済み' },
  'playlist.adding_song': { zh: '正在将《{songTitle}》加入您的收藏', en: 'Adding \"{songTitle}\" to your collection', ja: '「{songTitle}」をコレクションに追加中' },
  'playlist.back_to_page': { zh: '返回页面', en: 'Back', ja: '戻る' },
  'playlist.confirm_create_add': { zh: '确认创建并加入', en: 'Create & Add', ja: '作成して追加' },
  'playlist.confirm_remove': { zh: '确定要从该歌单中移除这首歌曲吗？', en: 'Are you sure you want to remove this song from the playlist?', ja: 'この曲をプレイリストから削除してもよろしいですか？' },
  'playlist.create_first': { zh: '创建首个歌单', en: 'Create First Playlist', ja: '最初のプレイリストを作成' },
  'playlist.create_new': { zh: '创建新歌单', en: 'Create New Playlist', ja: '新規プレイリスト作成' },
  'playlist.empty': { zh: '📭 您还没有创建任何歌单', en: '📭 You haven\'t created any playlists yet', ja: '📭 プレイリストがまだ作成されていません' },
  'playlist.empty_list': { zh: '空空如也', en: 'Empty', ja: '空っぽ' },
  'playlist.label': { zh: '歌单', en: 'Playlist', ja: 'プレイリスト' },
  'playlist.link_copied': { zh: '链接已复制', en: 'Link copied', ja: 'リンクがコピーされました' },
  'playlist.loading': { zh: '载入歌单列表中...', en: 'Loading playlist list...', ja: 'プレイリスト一覧を読み込み中...' },
  'playlist.loading_content': { zh: '正在极速载入歌单内容...', en: 'Loading playlist content...', ja: 'プレイリストのコンテンツを読み込み中...' },
  'playlist.new_name': { zh: '新建歌单名称', en: 'New Playlist Name', ja: '新規プレイリスト名' },
  'playlist.new_playlist': { zh: '新建歌单', en: 'New Playlist', ja: '新規プレイリスト' },
  'playlist.no_custom_playlists': { zh: '您尚未创建任何自定义歌单', en: 'You have not created any custom playlists yet', ja: 'カスタムプレイリストはまだ作成されていません' },
  'playlist.no_desc': { zh: '暂无描述信息', en: 'No description info', ja: '説明はありません' },
  'playlist.no_songs': { zh: '暂无歌曲，快去探索音乐并把歌曲加入你的歌单吧！', en: 'No songs yet, explore music and add some to your playlist!', ja: '曲がありません。音楽を探索してプレイリストに追加しましょう！' },
  'playlist.no_songs_short': { zh: '暂无歌曲', en: 'No Songs', ja: '曲がありません' },
  'playlist.not_found': { zh: '⚠️ 歌单不存在或已被删除', en: '⚠️ Playlist not found or deleted', ja: '⚠️ プレイリストが見つからないか削除されました' },
  'playlist.not_found_desc': { zh: '无法加载此歌单的信息，可能链接已失效。', en: 'Unable to load info, the link may have expired.', ja: '情報を読み込めません。リンクの有効期限が切れている可能性があります。' },
  'playlist.placeholder': { zh: '例如：深夜解压纯音乐、午后节奏特调', en: 'e.g. Midnight Ambient, Afternoon Beats', ja: '例：深夜のアンビエント、午後のビート' },
  'playlist.play_all': { zh: '播放全部', en: 'Play All', ja: 'すべて再生' },
  'playlist.remove': { zh: '从歌单中移除', en: 'Remove from Playlist', ja: 'プレイリストから削除' },
  'playlist.remove_failed': { zh: '移除失败', en: 'Remove failed', ja: '削除に失敗しました' },
  'playlist.share': { zh: '分享歌单', en: 'Share Playlist', ja: 'プレイリストを共有' },
  'playlist.share_desc': { zh: '向您推荐这张高品质极声音频歌单《{name}》！快来加入共创并听歌获取收益。', en: 'Highly recommend this high-quality ECHORURA playlist \"{name}\"! Join co-creation & listen to earn.', ja: '高品質なECHORURAプレイリスト『{name}』をおすすめします！共創に参加して聴いて稼ぎましょう。' },
  'playlist.share_link': { zh: '歌单链接：', en: 'Link: ', ja: 'リンク：' },
  'playlist.share_title': { zh: '极声音乐推荐歌单《{name}》', en: 'ECHORURA Recommended Playlist: {name}', ja: 'ECHORURAおすすめプレイリスト『{name}』' },
  'playlist.songs_count': { zh: '{count} 首作品', en: '{count} songs', ja: '{count} 曲' },
  'playlist.songs_list': { zh: '歌单曲目 ({count})', en: 'Playlist Tracks ({count})', ja: '収録曲 ({count})' },

  // PROFILE namespace
  'profile.audience_holder': { zh: '0.3(听众) / 0.7(权益人)', en: '0.3(Audience) / 0.7(Equity Holder)', ja: '0.3(リスナー) / 0.7(持分保有者)' },
  'profile.creator_overview': { zh: '创作者概览', en: 'Creator Overview', ja: 'クリエイター概要' },
  'profile.current_balance': { zh: '当前账户余额', en: 'Current Account Balance', ja: '現在のアカウント残高' },
  'profile.earning_model': { zh: '收益模型: ', en: 'Revenue Model: ', ja: '収益モデル: ' },
  'profile.login_required': { zh: '请先登录', en: 'Please Log In', ja: 'ログインしてください' },
  'profile.login_required_desc': { zh: '只有登录后才能管理你的作品和收益', en: 'You need to log in to manage your works and earnings.', ja: '作品と収益を管理するにはログインが必要です。' },
  'profile.my_favorites': { zh: '我的收藏', en: 'My Favorites', ja: 'マイお気に入り' },
  'profile.my_follows': { zh: '我的关注', en: 'My Follows', ja: 'マイフォロー' },
  'profile.my_playlists': { zh: '我的歌单', en: 'My Playlists', ja: 'プレイリスト' },
  'profile.my_works': { zh: '我的作品', en: 'My Works', ja: 'マイ作品' },
  'profile.no_bio': { zh: '暂无简介', en: 'No bio yet', ja: 'プロフィール文は未設定です' },
  'profile.no_favorites': { zh: '暂无收藏作品', en: 'No favorite works yet', ja: 'お気に入り作品はありません' },
  'profile.no_follows': { zh: '您还未关注任何创作者', en: 'You have not followed any creators yet', ja: 'まだクリエイターをフォローしていません' },
  'profile.no_works': { zh: '你还没有发布过任何作品', en: 'You have not published any works yet', ja: 'まだ作品を公開していません' },
  'profile.plays_count': { zh: '播放量', en: 'Plays', ja: '再生数' },
  'profile.publish_new_work': { zh: '发布新作品', en: 'Publish New Work', ja: '新規作品を公開' },
  'profile.published_works': { zh: '已发布作品', en: 'Published Works', ja: '公開済み作品' },
  'profile.staked_today': { zh: '今日推荐质押中 (10 ECHO)', en: 'Staking Today (10 ECHO)', ja: '本日アリーナ質押中 (10 ECHO)' },
  'profile.total_plays': { zh: '累计收听量', en: 'Total Plays', ja: '累計再生数' },
  'profile.visit_homepage': { zh: '访问主页', en: 'Visit Profile', ja: 'プロフィールを見る' },

  // Profile Upload / Publish Modal namespace
  'profile.upload_modal_title': { zh: '发布作品 (Studio)', en: 'Publish Work (Studio)', ja: '作品を公開 (Studio)' },
  'profile.upload_title_label': { zh: '作品标题', en: 'Title', ja: '作品タイトル' },
  'profile.upload_title_placeholder': { zh: '例如: Neon Dreamscape', en: 'e.g. Neon Dreamscape', ja: '例: Neon Dreamscape' },
  'profile.upload_artist_label': { zh: '艺术家名称', en: 'Artist Name', ja: 'アーティスト名' },
  'profile.upload_artist_placeholder': { zh: '默认使用用户名', en: 'Defaults to username', ja: 'デフォルトはユーザー名' },
  'profile.upload_lyrics_label': { zh: '作品歌词 (Lyrics)', en: 'Lyrics', ja: '歌詞' },
  'profile.upload_lyrics_plain': { zh: '纯文本', en: 'Plain Text', ja: 'プレーンテキスト' },
  'profile.upload_lyrics_lrc': { zh: '⏱ LRC 时间轴', en: '⏱ LRC Sync', ja: '⏱ LRC 同期' },
  'profile.upload_lrc_hint_title': { zh: '📌 LRC 时间轴格式说明', en: '📌 LRC Sync Format Guide', ja: '📌 LRC同期フォーマットガイド' },
  'profile.upload_lrc_hint_body': { zh: '每行格式：', en: 'Each line format:', ja: '各行の形式：' },
  'profile.upload_lrc_format_example': { zh: '[分:秒.毫秒] 歌词文字', en: '[min:sec.ms] Lyric text', ja: '[分:秒.ミリ秒] 歌詞テキスト' },
  'profile.upload_lrc_example_label': { zh: '例如：', en: 'e.g. ', ja: '例：' },
  'profile.upload_lrc_example_line1': { zh: '[00:12.34] 那是多年以前', en: '[00:12.34] Years ago...', ja: '[00:12.34] 何年も前のこと' },
  'profile.upload_lrc_example_line2': { zh: '[00:15.80] 秋天的一个傍晚', en: '[00:15.80] On an autumn evening...', ja: '[00:15.80] 秋の日の夕暮れ...' },
  'profile.upload_lrc_template_content': { zh: '[00:00.00] 第一句歌词\n[00:04.00] 第二句歌词\n[00:08.00] 第三句歌词\n[00:12.00] 请替换为实际歌词与对应时间戳', en: '[00:00.00] First lyric line\n[00:04.00] Second lyric line\n[00:08.00] Third lyric line\n[00:12.00] Please replace with actual lyrics and timestamps', ja: '[00:00.00] 最初の歌詞\n[00:04.00] 2番目の歌詞\n[00:08.00] 3番目の歌詞\n[00:12.00] 実際の歌詞とタイムスタンプに置き換えてください' },
  'profile.upload_lyrics_placeholder_lrc': { zh: '[00:00.00] 第一句歌词\n[00:04.50] 第二句歌词\n[00:09.00] 第三句歌词...', en: '[00:00.00] First line\n[00:04.50] Second line\n[00:09.00] Third line...', ja: '[00:00.00] 最初の歌詞\n[00:04.50] 2番目の歌詞\n[00:09.00] 3番目の歌詞...' },
  'profile.upload_lyrics_placeholder_plain': { zh: '粘贴作品歌词（纯文本，将按比例滚动显示）...', en: 'Paste lyrics (plain text, will scroll proportionally)...', ja: '歌詞を貼り付け（プレーンテキスト、比率に応じてスクロール表示）...' },
  'profile.upload_lrc_studio_btn': { zh: '🎧 开启录音棚打轴模式', en: '🎧 Open Studio Sync Mode', ja: '🎧 スタジオ同期モードを開く' },
  'profile.upload_lrc_select_audio_first': { zh: '请先选择音频', en: 'Select audio first', ja: '先に音声を選択' },
  'profile.upload_lrc_template': { zh: '📋 LRC 模板', en: '📋 LRC Template', ja: '📋 LRCテンプレート' },
  'profile.upload_lrc_valid': { zh: '✅ 已检测到 LRC 时间戳，共 {count} 行将精准同步', en: '✅ LRC timestamps detected, {count} lines will sync precisely', ja: '✅ LRCタイムスタンプを検出、{count}行が精密に同期されます' },
  'profile.upload_lrc_invalid': { zh: '⚠️ 未检测到时间戳，请使用 [00:00.00] 格式，否则将退回比例滚动模式', en: '⚠️ No timestamps detected, use [00:00.00] format or it will fall back to scroll mode', ja: '⚠️ タイムスタンプが検出されません。[00:00.00]形式を使用してください。' },
  'profile.upload_genres_label': { zh: '音乐风格 (Genres)', en: 'Music Genre', ja: '音楽ジャンル' },
  'profile.upload_moods_label': { zh: '灵魂状态 (Soul States)', en: 'Soul State', ja: 'ソウルステート' },
  'profile.upload_audio_label': { zh: '上传音频文件 (MP3/WAV)', en: 'Upload Audio (MP3/WAV)', ja: '音声ファイルをアップロード (MP3/WAV)' },
  'profile.upload_audio_drag': { zh: '选择或拖入音频文件', en: 'Select or drag audio file', ja: '音声ファイルを選択またはドラッグ' },
  'profile.upload_audio_optimized': { zh: '✓ 极声声码优化完成', en: '✓ Audio Optimized', ja: '✓ オーディオ最適化完了' },
  'profile.upload_audio_retry': { zh: '点击重新选择并上传', en: 'Click to reselect and upload', ja: 'クリックして再選択してアップロード' },
  'profile.upload_audio_error': { zh: '❌ 优化发生错误', en: '❌ Optimization error', ja: '❌ 最適化エラー' },
  'profile.upload_ai_title_alert': { zh: '请先填写作品标题，以便 AI 提取视觉灵感！', en: 'Please fill in the title first for AI to extract inspiration!', ja: 'AIがインスピレーションを得られるよう、先にタイトルを入力してください！' },
  'profile.upload_ai_prompt_alert': { zh: '请先填写作品标题，以便 AI 捕获核心意境！', en: 'Please fill in the title first for AI to capture the core mood!', ja: 'AIが楽曲イメージを捉えられるよう、先にタイトルを入力してください！' },
  'profile.upload_cover_label': { zh: '作品封面', en: 'Cover Art', ja: 'カバーアート' },
  'profile.upload_cover_manual': { zh: '自主上传', en: 'Upload', ja: 'アップロード' },
  'profile.upload_cover_ai': { zh: 'AI 智能创作', en: 'AI Generate', ja: 'AI生成' },
  'profile.upload_cover_drag': { zh: '选择或拖入封面', en: 'Select or drag cover', ja: 'カバーを選択またはドラッグ' },
  'profile.upload_cover_selected': { zh: '已选择封面', en: 'Cover selected', ja: 'カバー選択済み' },
  'profile.upload_cover_generated': { zh: '已智能排版生成', en: 'AI generated', ja: 'AI生成済み' },
  'profile.upload_cover_ai_preview': { zh: '根据歌曲信息智能渲染高级艺术封面', en: 'AI will render premium art cover based on song info', ja: '曲情報に基づいてプレミアムアートカバーをAIがレンダリングします' },
  'profile.upload_ai_style_cyber': { zh: '赛博霓虹', en: 'Cyber Neon', ja: 'サイバーネオン' },
  'profile.upload_ai_style_zen': { zh: '水墨禅意', en: 'Zen Ink', ja: '水墨禅' },
  'profile.upload_ai_style_vaporwave': { zh: '蒸汽波', en: 'Vaporwave', ja: 'ヴェイパーウェーブ' },
  'profile.upload_ai_style_ambient': { zh: '极光治愈', en: 'Aurora Heal', ja: 'オーロラヒール' },
  'profile.upload_ai_prompt_label': { zh: '画面描述 (做图要求 / AI Prompt)', en: 'Visual Description (AI Prompt)', ja: 'ビジュアル説明 (AIプロンプト)' },
  'profile.upload_ai_random_btn': { zh: '💡 随机生成灵感描述词', en: '💡 Random Inspiration', ja: '💡 ランダムなインスピレーション' },
  'profile.upload_ai_prompt_placeholder': { zh: '输入做图要求，例如: 赛博朋克霓虹城市、浮空飞船...', en: 'Enter prompt, e.g. cyberpunk neon city, floating spaceship...', ja: 'プロンプトを入力、例: サイバーパンクネオンシティ...' },
  'profile.upload_ai_gen_btn': { zh: '一键生成智能封面', en: 'Generate AI Cover', ja: 'AIカバーを生成' },
  'profile.upload_ai_regen_btn': { zh: '重新生成 AI 封面', en: 'Regenerate AI Cover', ja: 'AIカバーを再生成' },
  'profile.upload_ai_generating': { zh: '正在解析旋律与情绪...', en: 'Analyzing melody & mood...', ja: 'メロディーと感情を解析中...' },
  'profile.upload_promotion_label': { zh: '推荐推广模式 (Promotion Selector)', en: 'Promotion Mode', ja: 'プロモーションモード' },
  'profile.upload_mode_regular_title': { zh: '普通自主上架 (Regular Upload)', en: 'Regular Upload', ja: '通常アップロード' },
  'profile.upload_mode_regular_desc': { zh: '• AI 指纹质检后普通入库上架', en: '• AI quality check then standard listing', ja: '• AI品質チェック後に通常掲載' },
  'profile.upload_mode_stake_title': { zh: '质押冲刺「本日推荐榜」 (Stake Curation)', en: 'Stake for Today\'s Feature', ja: '本日おすすめ枠にステーク参加' },
  'profile.upload_mode_stake_desc1': { zh: '• 进入「听审竞技场」竞逐 30 票 Upvote 挑战', en: '• Enter Curation Arena, compete for 30 Upvote challenge', ja: '• キュレーションアリーナに参加、30 Upvoteに挑戦' },
  'profile.upload_mode_stake_desc2': { zh: '• 🏆 挑战成功：登上首页推荐榜，退回质押积分！', en: '• 🏆 Win: Featured on homepage & stake refunded!', ja: '• 🏆 成功：ホームページ掲載＆ステーク返金！' },
  'profile.upload_mode_stake_desc3': { zh: '• 🔽 挑战失败：质押不退，作品保留为普通', en: '• 🔽 Lose: Stake forfeited, song listed normally', ja: '• 🔽 失敗：ステーク没収、曲は通常掲載' },
  'profile.upload_creator_reward': { zh: '创作者奖励', en: 'Creator Reward', ja: 'クリエイター報酬' },
  'profile.upload_mode_stake_win': { zh: '挑战成功', en: 'Challenge Successful', ja: 'チャレンジ成功' },
  'profile.upload_mode_stake_win_desc1': { zh: '登上首页「本日推荐榜」', en: 'Featured on Homepage', ja: 'ホームページの「本日のおすすめ」に掲載' },
  'profile.upload_mode_stake_win_and': { zh: '，并', en: ', and ', ja: '、かつ' },
  'profile.upload_mode_stake_win_desc2': { zh: '退回质押积分', en: 'stake refunded', ja: 'ステークしたポイントは返金されます' },
  'profile.upload_mode_stake_fail': { zh: '挑战失败', en: 'Challenge Failed', ja: 'チャレンジ失敗' },
  'profile.upload_mode_stake_fail_desc': { zh: '质押不退并作为伯乐分红，作品保留为普通', en: 'stake forfeited and distributed as Curation dividends, work listed normally', ja: 'ステークは没収され、キュレーターに分配されます。作品は通常掲載として残ります' },
  'profile.upload_mode_stake_amount': { zh: '质押数量', en: 'Stake Amount', ja: 'ステーク数量' },
  'profile.upload_ipo_toggle': { zh: '开启歌曲共创', en: 'Enable Co-Creation', ja: '共同制作（Co-Creation）の有効化' },
  'profile.upload_ipo_shares_label': { zh: '发行总份额 (1 ECHO = 1 份)', en: 'Total Shares (1 ECHO = 1 share)', ja: '総発行数 (1 ECHO = 1シェア)' },
  'profile.upload_ipo_sell_ratio': { zh: '权益出售比例', en: 'Equity Sale Ratio', ja: '権益売却比率' },
  'profile.upload_ipo_listener_income': { zh: '听众固定收益', en: 'Listener Yield', ja: 'リスナー固定収益' },
  'profile.upload_ipo_equity_pool': { zh: '权益池分配', en: 'Equity Pool Dist.', ja: '権益プール分配' },
  'profile.upload_ipo_your_equity': { zh: '你保留的权益', en: 'Your retained equity', ja: 'あなたの保有権益' },
  'profile.upload_fan_push_title': { zh: '推送给粉丝 (Fan Push)', en: 'Fan Push Notification', ja: 'ファンへ通知 (Fan Push)' },
  'profile.upload_fan_push_desc': { zh: '向关注你的粉丝发送上新通知', en: 'Send new release notification to your followers', ja: 'フォロワーに新着通知を送信' },
  'profile.upload_agree_text': { zh: '我已认真阅读并自愿同意签署', en: 'I have read and agree to sign', ja: '私は以下に同意して署名します：' },
  'profile.upload_agree_link': { zh: '《极声音乐创作者原创作品上传与收益分配协议》', en: 'ECHORURA Creator Revenue Sharing Agreement', ja: 'ECHORURAクリエイター収益分配協定' },
  'profile.upload_agree_notice': { zh: '。我明确知悉并同意本协议第三条：作品一经发布，即自动进入听众分账及权益共创流通，因涉及多方既得财产安全，作品将永久存续在平台中，创作者不可单方面进行物理删除或物理下架。', en: '. I acknowledge that once published, the work enters listener revenue sharing and co-creation circulation. Due to multi-party property rights, works will permanently remain on the platform and cannot be unilaterally deleted or taken down.', ja: '。一度公開された作品はリスナー収益分配および共同創作流通に自動的に参加し、多方面の財産権が絡むため、作品はプラットフォームに永続的に保存され、一方的に削除・非公開にすることはできません。' },
  'profile.upload_cancel': { zh: '取消', en: 'Cancel', ja: 'キャンセル' },
  'profile.upload_submitting': { zh: '正在加密发布中...', en: 'Encrypting & publishing...', ja: '暗号化して公開中...' },
  'profile.upload_compressing': { zh: '声码优化压缩中...', en: 'Compressing audio...', ja: '音声圧縮中...' },
  'profile.upload_agree_first': { zh: '请先同意签署创作者协议', en: 'Please agree to the creator agreement first', ja: 'クリエイター協定に同意してください' },
  'profile.upload_submit': { zh: '正式发布作品', en: 'Publish Work', ja: '作品を正式公開' },
  'profile.upload_creator_agreement_title': { zh: '极声音乐创作者原创作品上传与收益分配协议', en: 'ECHORURA Creator Revenue Sharing Agreement', ja: 'ECHORURAクリエイター収益分配協定' },
  'profile.agreement_notice_title': { zh: '重要提示：', en: 'Important Notice:', ja: '重要なお知らせ：' },
  'profile.agreement_notice_body': { zh: '本协议是极声音乐（ECHORURA）平台与创作者之间关于原创作品上传、流通及收益分配的法律协议。在您勾选同意或上传作品前，请务必仔细阅读本协议，特别是第三条中关于作品“不可下架”与“不可删除”的重要声明。', en: 'This agreement is a legal contract between ECHORURA and the creator. Please read it carefully before checking agree or uploading, especially Article 3 regarding "immutability" and "non-deletability".', ja: '本規約は、ECHORURAプラットフォームとクリエイターとの間の契約です。同意チェックまたはアップロードの前に、必ず本規約をよくお読みください。特に第三条の「非公開不可」および「削除不可」の声明にご注意ください。' },
  'profile.agreement_sec1_title': { zh: '第一条：引言与共识基础', en: 'Article 1: Introduction & Consensus Base', ja: '第一条：導入とコンセンサス基礎' },
  'profile.agreement_sec1_body': { zh: '极声音乐是一个基于 Web3 共享经济与去中心化理念构建的音乐分发与价值共创平台。创作者在此上传、发布歌曲，即代表自愿将作品接入极声音乐的“听审竞技场（Curation Arena）”及“版权共创 Sound Equity 机制”，与听众、伯乐分享数字红利，共同打造公平、透明、自治的音乐创作新生态。', en: 'ECHORURA is a music distribution and value co-creation platform built on Web3 sharing economy and decentralization. By uploading, creators voluntarily connect their works to ECHORURA\'s "Curation Arena" and "Sound Equity" mechanisms, sharing digital dividends with listeners and curators to build a fair, transparent, and self-governed music ecosystem.', ja: 'ECHORURAは、Web3共有経済と分散型の理念に基づき構築された、音楽配信および価値共同創造のプラットフォームです。クリエイターが作品をアップロードすることは、作品を「キュレーションアリーナ」および「著作権共同創造 Sound Equity メカニズム」に自主的に接続し、リスナーやキュレーターと配当を共有することに同意したことを意味します。' },
  'profile.agreement_sec2_title': { zh: '第二条：版权归属与非独占授权', en: 'Article 2: Copyright Ownership & Non-exclusive License', ja: '第二条：著作権の归属および非独占的ライセンス' },
  'profile.agreement_sec2_body': { zh: '创作者对其在平台上传的作品拥有 100% 原始著作权。创作者仅非独占性、全球性、无偿地授予极声音乐在平台内传播、播放、缓存、生成动态推荐分享卡片及通过听歌挖矿分发给听众进行流媒体播放的权利。', en: 'Creators retain 100% original copyright of their uploaded works. Creators grant ECHORURA a non-exclusive, worldwide, royalty-free license to distribute, play, cache, generate sharing cards, and stream to listeners through listen-to-earn mining within the platform.', ja: 'クリエイターは、アップロードした作品に対して100%の原始著作権を保有します。クリエイターはECHORURAに対し、プラットフォーム内での送信、再生、キャッシュ、共有カードの生成、およびリスナーへの視聴マイニングを通じたストリーミング配信を行うための、非独占的、全世界的、無償のライセンスを付与します。' },
  'profile.agreement_sec3_title': { zh: '第三条：🚫 作品不可下架与不可删除声明 (Immutability Clause)', en: 'Article 3: 🚫 Immutability & Non-deletability Statement', ja: '第三条：🚫 作品の非公開不可および削除不可声明 (Immutability Clause)' },
  'profile.agreement_sec3_body1': { zh: '极声音乐采用链上数据锚定与注意力挖矿机制。创作者一旦上传作品并成功发布：', en: 'ECHORURA utilizes on-chain data anchoring and attention mining mechanisms. Once successfully published:', ja: 'ECHORURAは、オンチェーンデータのアンカリングおよびアテンションマイニングメカニズムを採用しています。公開が完了すると：' },
  'profile.agreement_sec3_bullet1': { zh: '作品将立即与听众的“听歌挖矿收益”产生绑定。听众因播放、投票或发掘作品所产生的收益，在数据库中具有强一致性与金融资产属性。', en: 'The work is immediately bound to listeners\' mining yields. Yields generated by playing, voting, or discovering works have strong consistency and financial asset properties in the database.', ja: '作品は直ちにリスナーの視聴マイニング収益と紐づけられます。再生、投票、または発掘によって発生した収益は、データベース内で強い整合性と金融资产属性を持ちます。' },
  'profile.agreement_sec3_bullet2': { zh: '如作品开启 Sound Equity 权益共创，投资者（听众）基于对作品的认购已持有作品的“版权份额”。该份额代表真实的未来收益分红权，属于投资者的合规资产。', en: 'If Sound Equity is enabled, investors (listeners) hold copyright shares of the work based on subscription. These shares represent actual future dividend rights and are considered compliant assets.', ja: '作品のSound Equity共同創造が有効化されている場合、購入した投資家（リスナー）は著作権シェアを保有します。このシェアは将来の配当受取権を代表し、投資家の正当な資産となります。' },
  'profile.agreement_sec3_bullet3': { zh: '【非物理下架规定】 为保障全体共创听众及投资人的既得资产安全，极声音乐不提供单方面物理下架或物理删除作品的功能。 作品一经成功上传，其音频指纹、源文件 Hash 及版权池数据将永久存续在极声音乐体系中，创作者终身放弃针对已关联资产的作品执行物理下架或物理删除的权利。', en: '[Immutability Clause] To protect the asset security of co-creating listeners and investors, ECHORURA does not provide any unilateral physical takedown or deletion. Once uploaded, audio fingerprints, source hashes, and copyright pool data will permanently exist in ECHORURA, and creators waive their right to perform physical takedowns.', ja: '【非公開不可規定】 すべての共同創造リスナーおよび投資家の資産安全を保護するため、ECHORURAは一方的な作品の物理的非公開または削除機能を提供しません。アップロードが成功すると、音声指纹、ソースファイルのハッシュ、著作権プールデータはECHORURAシステムに永続的に保存され、クリエイターは非公開や削除を行う権利を放棄します。' },
  'profile.agreement_sec4_title': { zh: '第四条：Curation Arena 质押与打榜规则', en: 'Article 4: Curation Arena Staking & Leaderboard Rules', ja: '第四条：キュレーションアリーナのステークおよびランキングルール' },
  'profile.agreement_sec4_body': { zh: '创作者如选择“质押冲刺本日推荐榜”模式，需自愿质押 10.00 ECHO 作为听审保证金。平台遵循民主化听审规则。当作品在听众投票中获得的票数在前 10 名，即为挑战成功，作品将登上首页「本日推荐榜」并全额退回 10.00 ECHO 保证金。若挑战未进入前 10 名，保证金将被没收并全部作为伯乐红利自动分发给参与投票的听众。', en: 'If creators choose Curation staking, they voluntarily stake 10.00 ECHO as security deposit. ECHORURA follows democratic auditioning rules. If the work votes place it in the top 10, the challenge is successful, the work is featured on the homepage, and the stake is refunded. If not, the stake is forfeited and distributed as dividends to voting listeners.', ja: 'クリエイターがステーク参加モードを選択した場合、保証金として10.00 ECHOをステークします。プラットフォームは民主的なキュレーションルールに従います。投票で上位10名に入ると成功となり、ホームページに掲載され保証金が返還されます。トップ10に入れなかった場合、保証金は没収され、投票したリスナーに配当として分配されます。' },
  'profile.agreement_sec5_title': { zh: '第五条：收益分割与版税分润', en: 'Article 5: Revenue Splitting & Royalty Sharing', ja: '第五条：収益分割およびロイヤリティ分配' },
  'profile.agreement_sec5_body': { zh: '当作品开启共创 IPO 认购后，听歌挖矿产生的全部 ECHO 收益将以“30% 听众流媒体挖矿”和“70% 权益池认购分红”进行透明分配。创作者通过认购与保留份额，按比例在数据库事务中获得秒级实时分润，双方严格遵守平台的智能计算共识。', en: 'When co-creation subscription is enabled, all ECHO yields from listen-to-earn mining are transparently split into "30% Listener Streaming Mining" and "70% Equity Pool Dividends". Creators receive real-time, second-level dividends proportionally based on retained shares.', ja: '共同創造が有効になると、マイニングによるすべてのECHO収益は「30%リスナーストリーミング」と「70%権益プール分配」に透明に分配されます。クリエイターは保有シェアに応じて、秒単位でリアルタイムに分配金を受け取ります。' },
  'profile.agreement_sec6_title': { zh: '第六条：原创性保证与侵权处罚', en: 'Article 6: Originality Guarantee & Infringement Penalties', ja: '第六条：オリジナル性の保証および侵害への罰則' },
  'profile.agreement_sec6_body': { zh: '创作者声明并担保所上传作品完全为原创或已依法获得完整的商业授权。如发生任何涉及侵犯第三方权益的纠纷，创作者须独立承担全部法律责任，平台免责。如平台收到合理的侵权指控，为保护平台安全，有权在不通知的前提下对该作品执行“听歌屏蔽”或“暂停收益分配”等保全措施。', en: 'Creators warrant that uploaded works are entirely original or legally licensed. Creators are solely liable for third-party copyright disputes. ECHORURA reserves the right to mute the song or suspend revenue allocation upon receiving infringement notices without prior warning.', ja: 'クリエイターは、アップロードされた作品が完全にオリジナルであるか、合法的に商用ライセンスを取得していることを保証します。第三者の権利侵害に関する紛争が発生した場合、クリエイターが単独で一切の責任を負います。侵害の申立てがあった場合、プラットフォームは事前通知なしに再生ブロックや収益分配の一時停止を行う権利を有します。' },
  'profile.agreement_sec7_title': { zh: '第七条：反作弊审计', en: 'Article 7: Anti-Cheating Audit', ja: '第七条：不正防止監査' },
  'profile.agreement_sec7_body': { zh: '极声音乐严格禁止利用机器人、多开账号、模拟器等任何作弊或刷量方式恶意侵占流媒体挖矿池。系统内置 AI 流量审计引擎。一经监测到虚假播放流量，平台有权冻结相关账户的所有收益，没收质押保证金，并执行作弊地址的永久限制访问。', en: 'ECHORURA strictly prohibits bots, duplicate accounts, emulators, or traffic manipulation. Built-in AI traffic audit engine monitors activity. Upon detecting fake plays, the platform reserves the right to freeze yields, forfeit stakes, and permanently restrict account access.', ja: 'ECHORURAは、ボット、複数アカウント、エミュレーター等の使用による不正な再生回数操作を厳しく禁止します。AI監査エンジンが巡回しており、不正が検出された場合、アカウントの凍結、ステークの没収、およびアクセス制限を行います。' },
  'profile.agreement_close': { zh: '关闭阅读', en: 'Close', ja: '閉じる' },
  'profile.agreement_agree_btn': { zh: '我自愿并同意签署此协议', en: 'I voluntarily agree and sign this agreement', ja: '同意して署名する' },

  'genre.流行': { zh: '流行', en: 'Pop', ja: 'ポップ' },
  'genre.嘻哈': { zh: '嘻哈', en: 'Hip-Hop', ja: 'ヒップホップ' },
  'genre.R&B': { zh: 'R&B', en: 'R&B', ja: 'R&B' },
  'genre.电子舞曲': { zh: '电子舞曲', en: 'EDM', ja: 'ダンス/EDM' },
  'genre.摇滚': { zh: '摇滚', en: 'Rock', ja: 'ロック' },
  'genre.K-Pop': { zh: 'K-Pop', en: 'K-Pop', ja: 'K-Pop' },
  'genre.古典': { zh: '古典', en: 'Classical', ja: 'クラシック' },
  'genre.爵士': { zh: '爵士', en: 'Jazz', ja: 'ジャズ' },
  'genre.民谣': { zh: '民谣', en: 'Folk', ja: 'フォーク' },
  'genre.氛围放松': { zh: '氛围放松', en: 'Ambient', ja: 'アンビエント' },
  'genre.影视原声': { zh: '影视原声', en: 'Soundtrack', ja: 'サウンドトラック' },
  'genre.国风': { zh: '国风', en: 'Traditional Chinese', ja: '国風/中華風' },
  'genre.二次元': { zh: '二次元', en: 'ACG', ja: 'アニソン' },
  'genre.另类独立': { zh: '另类独立', en: 'Alternative Indie', ja: 'オルタナティブ/インディーズ' },
  'genre.灵魂乐': { zh: '灵魂乐', en: 'Soul', ja: 'ソウル' },

  'mood.午夜': { zh: '午夜', en: 'Midnight', ja: 'ミッドナイト' },
  'mood.孤独': { zh: '孤独', en: 'Lonely', ja: '孤独/ロンリー' },
  'mood.伤感': { zh: '伤感', en: 'Sad', ja: 'センチメンタル' },
  'mood.治愈': { zh: '治愈', en: 'Healing', ja: 'ヒーリング/癒やし' },
  'mood.放松': { zh: '放松', en: 'Relaxed', ja: 'リラックス' },
  'mood.专注': { zh: '专注', en: 'Focus', ja: '集中/フォーカス' },
  'mood.冥想': { zh: '冥想', en: 'Meditation', ja: '瞑想/メディテーション' },
  'mood.助眠': { zh: '助眠', en: 'Sleep', ja: '睡眠用' },
  'mood.热血': { zh: '热血', en: 'Energetic', ja: '熱血/エナジー' },
  'mood.运动': { zh: '运动', en: 'Workout', ja: 'ワークアウト' },
  'mood.派对': { zh: '派对', en: 'Party', ja: 'パーティー' },
  'mood.喜悦': { zh: '喜悦', en: 'Happy', ja: 'ハッピー' },
  'mood.赛博': { zh: '赛博', en: 'Cyber', ja: 'サイバー' },

  'profile.edit_genres_title': { zh: '音乐风格标签 (Genres - 可多选)', en: 'Music Genres (Multi-select)', ja: '音楽ジャンルタグ (複数選択可)' },
  'profile.edit_moods_title': { zh: '灵魂状态标签 (Moods - 可多选)', en: 'Soul States (Multi-select)', ja: 'ソウルステートタグ (複数選択可)' },
  'profile.edit_lrc_format_detected': { zh: '✅ 已检测到 LRC 时间戳格式', en: '✅ LRC timestamp format detected', ja: '✅ LRCタイムスタンプ形式を検出' },


  'profile.edit_profile_tooltip': { zh: '编辑个人资料', en: 'Edit Profile', ja: 'プロフィール編集' },
  'profile.share_profile_tooltip': { zh: '分享我的创作者主页', en: 'Share Creator Page', ja: 'クリエイターページを共有' },
  'profile.copied_link_text': { zh: '已复制！', en: 'Copied!', ja: 'コピーされました！' },
  'profile.share_profile_btn_text': { zh: '分享主页', en: 'Share Page', ja: 'ページを共有' },
  'profile.edit_profile_title': { zh: '编辑个人资料', en: 'Edit Profile', ja: 'プロフィール編集' },
  'profile.edit_avatar_label': { zh: '选择头像 (艺名形象)', en: 'Select Avatar', ja: 'アバター選択' },
  'profile.edit_stage_name': { zh: '艺名 (Stage Name)', en: 'Stage Name', ja: '活動名（ステージ名）' },
  'profile.edit_stage_name_placeholder': { zh: '输入你的舞台昵称...', en: 'Enter your stage name...', ja: 'ステージ名を入力してください...' },
  'profile.edit_bio': { zh: '个人简介 (Bio)', en: 'Bio', ja: 'プロフィール（バイオ）' },
  'profile.edit_bio_placeholder': { zh: '用一段话向粉丝介绍一下你自己...', en: 'Introduce yourself to your fans...', ja: '自己紹介を入力してください...' },
  'profile.edit_cancel': { zh: '取消', en: 'Cancel', ja: 'キャンセル' },
  'profile.edit_save': { zh: '保存更改', en: 'Save Changes', ja: '変更を保存' },
  'profile.edit_danger_zone': { zh: '危险区域 (Danger Zone)', en: 'Danger Zone', ja: '危険ゾーン' },
  'profile.edit_danger_zone_desc': { zh: '注销账户是不可逆的操作。所有的个人隐私数据将按照香港《个人资料（私隐）条例》被彻底抹除。根据平台共享经济协定，您的已发行共创歌曲将被脱敏匿名保留以保障粉丝的权益。', en: 'Account deletion is irreversible. Personal privacy data will be erased in compliance with the HK Personal Data (Privacy) Ordinance. Co-creation songs will be anonymized to protect listener shares.', ja: 'アカウント削除は取り消しできません。すべての個人情報は香港の個人データ（プライバシー）条例に従って削除されます。共同制作曲はリスナー保護のため匿名化されて保持されます。' },
  'profile.edit_delete_account_btn': { zh: '注销极声音乐账户', en: 'Delete ECHORURA Account', ja: 'ECHORURAアカウントを削除' },

  'wallet.aa_sca': { zh: 'AA 智能托管账户 (SCA)', en: 'AA Smart Custody Account (SCA)', ja: 'AAスマートコントラクトウォレット (SCA)' },
  'wallet.aa_sca_desc': { zh: '极声音乐为每位用户静默托管的无感 Web3 智能账号，安全合规，私钥未备份前不可直接导出。', en: 'Silently escrowed Web3 smart account for seamless UX. Private key cannot be exported before KYC backup.', ja: 'ECHORURAがすべてのユーザーにサイレントカストディするWeb3スマートアカウント。KYCバックアップを行うまで秘密鍵は直接エクスポートできません。' },
  'wallet.accumulated_dividends_earned': { zh: '累计赚取分红', en: 'Accumulated Dividends Earned', ja: '累積獲得配当' },
  'wallet.address_copied': { zh: '地址已复制到剪贴板', en: 'Address copied to clipboard', ja: 'アドレスをクリップボードにコピーしました' },
  'wallet.asset_hub_subtitle': { zh: '管理您的数字资产、分红权益与钱包连接', en: 'Manage your digital assets, dividend rights, and wallet connection', ja: 'デジタルアセット、配当権利、ウォレット接続を管理します' },
  'wallet.asset_name': { zh: '资产名称', en: 'Asset Name', ja: 'アセット名' },
  'wallet.asset_portfolios': { zh: ' 资产', en: ' Asset Portfolios', ja: ' アセットポートフォリオ' },
  'wallet.auditing': { zh: '听审中', en: 'Auditing', ja: '監査中' },
  'wallet.back': { zh: '返回', en: 'Back', ja: '戻る' },
  'wallet.beta_alert': { zh: '该功能处于 Beta 测试阶段，仅支持模拟交易体验！', en: 'This feature is in Beta, only simulating transaction experience!', ja: 'この機能はベータテスト中であり、シミュレーション取引のみをサポートしています！' },
  'wallet.card_number': { zh: '卡号', en: 'Card Number', ja: 'カード番号' },
  'wallet.claim_failed': { zh: '领取分红失败', en: 'Claim dividends failed', ja: '配当請求失敗' },
  'wallet.claim_on_chain_dividends': { zh: '领取链上分红收益', en: 'Claim On-chain Dividends', ja: 'オンチェーン配当を請求' },
  'wallet.claim_success_msg': { zh: '分红领取成功！已转入您的托管钱包。', en: 'Dividends claimed successfully! Transferred to escrow wallet.', ja: '配当の請求に成功しました！カストディウォレットに転送されました。' },
  'wallet.claim_tx_submitted': { zh: '分红领取交易已提交，等待链上打包...', en: 'Dividends claim transaction submitted, waiting for packaging...', ja: '配当請求トランザクションが送信されました。オンチェーンの処理を待機中...' },
  'wallet.connect_failed': { zh: '连接钱包失败，请确保已安装 MetaMask 插件', en: 'Wallet connection failed, ensure MetaMask plugin is installed', ja: 'ウォレット接続失敗、MetaMaskプラグインがインストールされているか確認してください' },
  'wallet.connect_metamask': { zh: '连接 MetaMask 钱包', en: 'Connect MetaMask Wallet', ja: 'MetaMaskウォレットを接続' },
  'wallet.connect_metamask_claim': { zh: '请先连接 MetaMask 钱包以领取链上收益', en: 'Please connect MetaMask wallet first to claim on-chain rewards', ja: 'オンチェーン報酬を請求するには、先にMetaMaskウォレットを接続してください' },
  'wallet.connect_metamask_desc': { zh: '通过连接外部 MetaMask 钱包，您可以查看、转账链上真实 ECHO 代币及音乐所有权资产。', en: 'Connect MetaMask to view and transfer real on-chain ECHO tokens and music equity.', ja: '外部のMetaMaskウォレットを接続することで、オンチェーン上のリアルなECHOトークンおよび音楽所有権アセットの確認・転送が可能です。' },
  'wallet.connected_base': { zh: '已连接 Base 主网', en: 'Connected Base', ja: 'Baseメインネットに接続中' },
  'wallet.contract_read_error': { zh: '读取链上余额失败，请确保已切换到 Base Sepolia 测试网', en: 'Failed to read on-chain balance. Make sure to switch to Base Sepolia testnet', ja: 'オンチェーン残高の読み取りに失敗しました。Base Sepoliaテストネットに切り替えてください' },
  'wallet.copy': { zh: '复制', en: 'Copy', ja: 'コピー' },
  'wallet.credit_card': { zh: '信用卡 / 借记卡', en: 'Credit / Debit Card', ja: 'クレジットカード / デビットカード' },
  'wallet.credit_desc': { zh: '基于您的信用额度进行先行代付，免去频繁签名的繁琐，适合日常快速操作。', en: 'Advance payment based on credit limit, bypassing frequent signatures.', ja: '与信枠に基づいて先行支払いを行います。頻繁な署名の手間を省き、日常の高速な操作に適しています。' },
  'wallet.credit_limit': { zh: '可用信用额度 (Available Credit)', en: 'Available Credit', ja: '利用可能与信枠 (Available Credit)' },
  'wallet.used_limit': { zh: '已用额度', en: 'Used Limit', ja: '使用済み額' },
  'wallet.credit_privilege': { zh: '信用支付特权 (Web2.5)', en: 'Credit Payment Privilege (Web2.5)', ja: '信用支付特権 (Web2.5)' },
  'wallet.curation_total': { zh: '共创共享音乐总值', en: 'Co-Curation Total Value', ja: '共創音楽総価値' },
  'wallet.current_price': { zh: '当前单价', en: 'Current Price', ja: '現在の単価' },
  'wallet.custody_status': { zh: '托管状态', en: 'Custody Status', ja: 'カストディ状態' },
  'wallet.custom_amount': { zh: '自定义金额', en: 'Custom Amount', ja: 'カスタム金額' },
  'wallet.cvc': { zh: '验证码', en: 'CVC', ja: 'セキュリティコード' },
  'wallet.equity_ref_value': { zh: '版权持股参考估值', en: 'Equity Reference Valuation', ja: '著作権持分参考評価' },
  'wallet.est_market_value': { zh: '估算市场价值', en: 'Est. Market Value', ja: '推定市場価値' },
  'wallet.evm_self_custody': { zh: 'EVM 自托管钱包 (MetaMask)', en: 'EVM Self-Custody Wallet (MetaMask)', ja: 'EVM自己管理ウォレット (MetaMask)' },
  'wallet.expiry': { zh: '有效期', en: 'Expiry', ja: '有効期限' },
  'wallet.external_metamask': { zh: '外部 MetaMask 账户', en: 'External MetaMask Account', ja: '外部MetaMaskアカウント' },
  'wallet.fiat_disclaimer': { zh: '提示：由于汇率及测试网限制，法币充值仅做测试阶段模拟展示，充值成功后将以 1 USD = 100 ECHO 的汇率计入您的极声账户余额。', en: 'Note: Fiat deposit is for demo simulation only. 1 USD = 100 ECHO.', ja: '注意：為替レートおよびテストネットの制限により、法定通貨チャージはテスト段階のシミュレーション展示のみであり、チャージ成功後は1 USD = 100 ECHOのレートでアカウント残高に加算されます。' },
  'wallet.fiat_exchange_rate': { zh: '法币汇率 (模拟)：1 USD = 100 ECHO', en: 'Fiat Rate (Sim): 1 USD = 100 ECHO', ja: '法定通貨レート (シミュレーション)：1 USD = 100 ECHO' },
  'wallet.go_to_market': { zh: '前往市集认购', en: 'Go to Market', ja: 'マーケットへ' },
  'wallet.interest_free': { zh: '免息先付', en: 'Interest-Free Pay', ja: '無利息先払い' },
  'wallet.kyc_protected': { zh: 'KYC 身份受保护', en: 'KYC Protected', ja: 'KYC保護済み' },
  'wallet.listener_weight': { zh: '基于你的 Listener Weight (收听活跃度) 动态评估', en: 'Dynamically evaluated based on your Listener Weight', ja: 'リスナーウェイト（再生アクティビティ）に基づいて動的に評価' },
  'wallet.locked_available': { zh: '已锁定可用 (Available)', en: 'Locked & Available', ja: 'ロック済み（利用可能）' },
  'wallet.min_sync_threshold': { zh: '提示：当收益累积达 5.00 ECHO 时方可进行链上清算与提取', en: 'Note: On-chain settlement & withdrawal is available when earnings reach 5.00 ECHO', ja: '注意：収益が5.00 ECHOに達すると、オンチェーン決済と引き出しが可能になります' },
  'wallet.not_connected': { zh: '未连接外部钱包', en: 'External Wallet Not Connected', ja: '外部ウォレット未接続' },
  'wallet.quick_topup': { zh: '极速充值', en: 'Quick Top-Up', ja: 'クイックチャージ' },
  'wallet.reset_midnight': { zh: '至24点清零', en: 'Resets at midnight', ja: '深夜0時リセット' },
  'wallet.sync_amount_rewards': { zh: '一键同步上链已审计收益 ({amount} ECHO)', en: 'Sync Audited Earnings to Chain ({amount} ECHO)', ja: '監査済み収益をオンチェーン同期 ({amount} ECHO)' },
  'wallet.today_listen_earn': { zh: '本日音乐收听收益', en: 'Today\'s Listen Earnings', ja: '本日のリスニング収益' },
  'wallet.token_balance': { zh: '余额', en: 'Balance', ja: '残高' },
  'wallet.topup_not_available': { zh: '内测期间，充值暂未开通', en: 'Top-up is not available during beta test', ja: 'ベータテスト中、チャージはご利用いただけません' },
  'wallet.total_limit': { zh: '总额度', en: 'Total Limit', ja: '総枠' },
  'wallet.tx_stream': { zh: '收益流水 (Txs)', en: 'Earnings (Txs)', ja: '収益ログ (Txs)' },
    'wallet.no_valid_address': { zh: '没有有效的托管地址', en: 'No valid custody address', ja: '有効なカストディアドレスがありません' },
  'wallet.insufficient_balance_sync': { zh: '当前余额不足，无法发起清算同步！', en: 'Insufficient balance, cannot initiate sync!', ja: '残高不足のため、同期を開始できません！' },
  'wallet.session_expired_sync': { zh: '会话已过期，请重新登录后再试！', en: 'Session expired, please log in again!', ja: 'セッションの期限が切れました。再ログインしてください！' },
  'wallet.sync_success': { zh: '收益已成功同步至链上智能账户！', en: 'Earnings successfully synced to chain smart account!', ja: '収益がチェーン上のスマートアカウントに同期されました！' },
  'wallet.sync_failed': { zh: '同步失败: ', en: 'Sync failed: ', ja: '同期失敗: ' },
  'wallet.syncing_rewards': { zh: '正在清算同步收益...', en: 'Syncing rewards to chain...', ja: '収益を同期中...' },
  'wallet.silent_custody': { zh: '设备密钥安全保护', en: 'Device Key Protected', ja: 'デバイスキー保護' },
  'wallet.connect_smart_wallet': { zh: '创建 / 连接 Base 智能钱包', en: 'Create / Connect Base Smart Wallet', ja: 'Baseスマートウォレットを作成 / 接続' },
  'wallet.disconnect_wallet': { zh: '断开连接', en: 'Disconnect Wallet', ja: '接続を解除' },
  'wallet.connect_first': { zh: '请先连接您的 Base 智能钱包！', en: 'Please connect your Base Smart Wallet first!', ja: '先にBaseスマートウォレットを连接してください！' },
  'wallet.wallet_status_connected': { zh: '已连接 (真实链上)', en: 'Connected (On-Chain)', ja: '接続済み (オンチェーン)' },
  'wallet.wallet_status_disconnected': { zh: '未连接', en: 'Not Connected', ja: '未接続' },
  'wallet.smart_wallet_desc': { zh: '基于 Base 链的智能合约账户，由您的设备生物识别（Passkey）安全保护。一键同步指令将自动将您的收益铸造分发到该地址。', en: 'Base smart contract account, secured by your device biometrics (Passkey). Synchronized earnings will be minted directly to this address.', ja: 'Baseスマートアカウント。デバイスの生体認証（Passkey）で安全に保護されています。同期された収益はこのアドレスに直接ミントされます。' },
  'wallet.sync_tx_sent': { zh: '一键清算指令已送达智能合约', en: 'Settlement command sent to smart contract', ja: '決済コマンドがスマートコントラクトに送信されました' },
  'wallet.sync_tx_sent_desc': { zh: '智能合约正在异步执行清算，代币分发将直接到达您的智能账户地址。', en: 'Smart contract is curating settlement. Tokens will arrive directly in your smart account.', ja: 'スマートコントラクトが決済を处理中。トークンはスマートアカウントに直接到着します。' },
  'wallet.view_on_basescan': { zh: '在 BaseScan 上查看交易', en: 'View transaction on BaseScan', ja: 'BaseScanでトランザクションを表示' },
  'wallet.onchain_balance': { zh: '已同步链上余额', en: 'Synced On-Chain Balance', ja: '同期済みオンチェーン残高' },
  'wallet.transfer_out': { zh: '转出代币', en: 'Transfer Tokens', ja: 'トークンを転送' },
  'wallet.recipient_address': { zh: '接收端以太坊地址 (0x...)', en: 'Recipient EVM Address (0x...)', ja: '受信先EVMアドレス (0x...)' },
  'wallet.transfer_amount_input': { zh: '要转出的代币数量 (ECHO)', en: 'Amount of ECHO to transfer', ja: '転送するECHO数量' },
  'wallet.transfer_sending': { zh: '正在发送区块链交易...', en: 'Sending on-chain transaction...', ja: 'チェーン上にトランザクションを送信中...' },
  'wallet.transfer_confirming': { zh: '正在等待区块确认...', en: 'Waiting for block confirmation...', ja: 'ブロックの承認を待机中...' },
  'wallet.transfer_success': { zh: '🎉 转账成功！交易已被区块打包。', en: 'Transfer successful! Transaction confirmed on block.', ja: '転送が成功しました！' },
  'wallet.transfer_failed': { zh: '❌ 转账失败: ', en: 'Transfer failed: ', ja: '転送失敗: ' },
  'wallet.close': { zh: '关闭', en: 'Close', ja: '閉じる' },
  'wallet.send': { zh: '立即发送', en: 'Send Now', ja: '送信する' },
  'wallet.invalid_recipient': { zh: '请输入有效的 0x 格式以太坊地址！', en: 'Please enter a valid 0x EVM address!', ja: '有効なEVMアドレスを入力してください！' },
  'wallet.invalid_amount': { zh: '请输入大于 0 且不超过当前余额的数量！', en: 'Please enter an amount greater than 0 and less than your balance!', ja: '有效な数量を入力してください！' },
  'wallet.deposit_to_platform': { zh: '存入平台账户', en: 'Deposit to App', ja: 'プラットフォームに入金' },
  'wallet.deposit_amount_input': { zh: '要存入的代币数量 (ECHO)', en: 'Amount of ECHO to deposit', ja: '入金するECHO数量' },
  'wallet.deposit_sending': { zh: '正在发送代币到平台...', en: 'Transferring tokens to app...', ja: 'アプリにトークンを转送中...' },
  'wallet.deposit_verifying': { zh: '正在验证链上交易并入账...', en: 'Verifying on-chain transaction & crediting...', ja: 'チェーン上のトランザクションを検証して入金中...' },
  'wallet.deposit_success': { zh: '🎉 存入成功！代币已成功兑换并转入您的平台账户余额。', en: 'Deposit successful! Tokens converted and credited to your app balance.', ja: '入金成功！トークンがアプリ残高に変換されました。' },
  'wallet.deposit_failed': { zh: '❌ 存入入账失败: ', en: 'Deposit failed: ', ja: '入金失敗: ' },
  'wallet.portfolio_desc': { zh: '您持有的全部音乐共创共享股权和认购股份。', en: 'All music co-curation equity and subscribed shares you hold.', ja: '保有しているすべての音楽共創持分および購入シェア。' },
  'wallet.real_time_valuation': { zh: '持股参考估值', en: 'Equity Reference Value', ja: '持分参考評価額' },
  'wallet.shares_held': { zh: '持有份额', en: 'Shares Held', ja: '保有シェア数' },
  'wallet.history_dividends': { zh: '累计赚取分红', en: 'Accumulated Dividends', ja: '累積獲得配当' },
  'wallet.system_shares': { zh: ' 份', en: ' Shares', ja: ' シェア' },
  'wallet.no_equity_held': { zh: '您当前未持有任何音乐版权股权，快去共创市集看看吧！', en: 'You do not hold any music equity. Go check the co-creation market!', ja: '現在音楽持分を保有していません。共創マーケットをチェックしましょう！' },
  'wallet.top_up_fiat': { zh: '极速充值积分', en: 'Quick Top Up', ja: 'クイックチャージ' },
  'wallet.top_up_success': { zh: '充值成功！', en: 'Top-up Successful!', ja: 'チャージ成功！' },
  'wallet.top_up_success_desc': { zh: '您的充值金额已通过安全支付渠道到账，余额已实时更新。', en: 'Your payment was processed successfully. Balance updated in real-time.', ja: '決済が正常に処理されました。残高がリアルタイムで更新されました。' },
  'wallet.top_up_warning': { zh: '注意：当前处于内测阶段，支付仅做测试仿真体验。', en: 'Note: Current phase is beta test. Payments are simulated.', ja: '注意：現在はベータテスト段階です。支払いはシミュレーションされます。' },
  'wallet.select_preset': { zh: '选择快捷充值额度', en: 'Select preset amount', ja: 'クイックチャージ金額を選択' },
  'wallet.input_amount': { zh: '输入自定义金额', en: 'Enter custom amount', ja: 'カスタム金額を入力' },
  'wallet.payment_gateway': { zh: '选择支付通道', en: 'Select Payment Gateway', ja: '決済方法を選択' },
  'wallet.stripe_processing': { zh: '正在调用 Stripe 结算网关...', en: 'Processing via Stripe gateway...', ja: 'Stripe決済を処理中...' },
  'wallet.pay_now': { zh: '确认支付', en: 'Confirm Payment', ja: '支払いを確定' },
  'wallet.transactions_log': { zh: '收益与充值流水', en: 'Earnings & Transactions Log', ja: '収益＆トランザクションログ' },
  'wallet.no_records': { zh: '暂无交易流水记录', en: 'No transaction records found', ja: 'トランザクション記録はありません' },
  'wallet.tx_type_listen': { zh: '听歌挖矿收益', en: 'Listen Mining Reward', ja: 'リスニングマイニング報酬' },
  'wallet.tx_type_upload': { zh: '作品发行收益', en: 'Music Publishing Reward', ja: '音楽配信報酬' },
  'wallet.tx_type_invite': { zh: '邀请好友奖励', en: 'Referral Reward', ja: '紹介報酬' },
  'wallet.tx_type_gift': { zh: '系统赠送福利', en: 'System Gift', ja: 'システムギフト' },
  'wallet.tx_type_dividend_pool': { zh: '版权分红发放', en: 'Copyright Dividend Distribution', ja: '著作権配当分配' },
  'wallet.tx_type_dividend_payout': { zh: '版权持有收益', en: 'Copyright Holding Dividend', ja: '著作権持分配当' },
  'wallet.tx_type_download': { zh: '付费下载扣减', en: 'Paid Download Cost', ja: '有料ダウンロード費用' },
  'wallet.tx_unknown': { zh: '其他流水记录', en: 'Other transaction record', ja: 'その他トランザクション' },
  'wallet.tx_song': { zh: '关联歌曲', en: 'Related Song', ja: '関連曲' },
  'wallet.settled': { zh: '已入账', en: 'Settled', ja: '決済済み' },

  // Profile General & Navigation
  'profile.system_support': { zh: '系统与支持 (Support)', en: 'Support & System', ja: 'システム＆サポート' },
  'profile.guide_help_center': { zh: '使用指南 & 帮助中心', en: 'Guide & Help Center', ja: 'ガイド＆ヘルプセンター' },
  'profile.how_to_play': { zh: '如何玩转极声音乐', en: 'How to play ECHORURA', ja: 'ECHORURAの楽しみ方' },
  'profile.about_compliance': { zh: '关于我们 & 合规说明', en: 'About Us & Compliance', ja: '私たちについて＆コンプライアンス説明' },
  'profile.mission_architecture': { zh: '使命愿景与架构公示', en: 'Platform Vision & Architecture', ja: 'ミッション・ビジョン及びアーキテクチャ公開' },
  'profile.social_rewards_title': { zh: '专属社交裂变奖励', en: 'Exclusive Social Referral Rewards', ja: '紹介リワード特典' },
  'profile.social_rewards_desc': { zh: '分享您的专属邀请码给好友，好友在注册时填写此码。注册成功后，新成员可得 10 ECHO 新人礼包，您将获得 5.00 ECHO 邀请人分润奖励，秒级发放到账！', en: 'Share your invite code with friends. Once registered with your code, they get 10 ECHO as a welcome gift, and you earn a 5.00 ECHO referral reward in real-time!', ja: '紹介コードを友達と共有しましょう。友達がコードを使って登録すると、ウェルカムギフトとして10 ECHOを獲得し、あなたにはリアルタイムで5.00 ECHOの紹介報酬が支払われます！' },
  'profile.my_invite_code': { zh: '我的邀请码', en: 'My Invite Code', ja: '私の紹介コード' },
  'profile.copy_invite_code': { zh: '复制邀请码', en: 'Copy Invite Code', ja: '紹介コードをコピー' },
  'profile.artist_link_copied': { zh: '已复制创作者主页链接！', en: 'Creator profile link copied!', ja: 'クリエイターページのリンクをコピーしました！' },
  'profile.share_artist_page': { zh: '推广分享我的创作者主页', en: 'Share my creator profile page', ja: 'クリエイターページをシェアする' },
  'profile.social_rewards_rule': { zh: '规则说明：邀请好友注册属于社区共创增长计划。每次成功邀请，奖励将以 🟢已结算 形式实时入账，可用于市集认购歌曲版权或在擂台质押！', en: 'Rule: Referring friends is part of the community growth plan. Rewards are settled instantly and can be used for song subscription or arena staking.', ja: 'ルール：友達の紹介はコミュニティ成長プランの一部です。報酬は即座に決済され、楽曲の購入やアリーナでの質押に使用できます。' },
  'profile.security_mgmt': { zh: '账户安全管理', en: 'Account Security', ja: 'アカウントセキュリティ管理' },
  'profile.change_pwd': { zh: '修改账户密码', en: 'Change Password', ja: 'パスワード変更' },
  'profile.feedback_support': { zh: '意见与问题反馈', en: 'Feedback & Support', ja: 'フィードバック＆サポート' },
  'profile.logout': { zh: '退出当前登录', en: 'Logout', ja: 'ログアウト' },

  // Profile Account Deactivation & Erasing
  'profile.anonymization_strong': { zh: '创作者匿名化：', en: 'Creator Anonymization: ', ja: 'クリエイターの匿名化：' },
  'profile.anonymization_desc': { zh: '您的 stage name 和头像数据将被清空，取而代之的是“匿名创作者 (Anonymous Creator)”标识，歌曲后续产生的任何收益均与您的个人隐私账户彻底解绑。', en: 'Your stage name and avatar data will be cleared and replaced with the "Anonymous Creator" label. Any future earnings generated by the songs will be completely unbound from your personal private account.', ja: 'あなたのステージ名とアバターデータはクリアされ、「匿名クリエイター (Anonymous Creator)」ラベルに置き換えられます。今後これらの楽曲から発生する収益は、個人用プライベートアカウントから完全にバインド解除されます。' },
  'profile.cancel_keep_account': { zh: '取消，保留账户', en: 'Cancel, Keep Account', ja: 'キャンセル、アカウントを維持' },
  'profile.confirm_next_step': { zh: '我已知晓，进入下一步', en: 'I Understand, Next Step', ja: '了解しました、次のステップへ' },
  'profile.agreement_step_title': { zh: '签署存续协议与确认', en: 'Sign Agreement & Confirm', ja: '同意書への署名と確認' },
  'profile.agreement_doc_title': { zh: '极声音乐共享资产存续与注销协议', en: 'ECHORURA Shared Asset Retention & Deactivation Agreement', ja: 'ECHORURA共有資産の存続および無効化に関する合意书' },
  'profile.agreement_doc_p1': { zh: '1. 本注销协议一经签署，即代表您与极声音乐 (ECHORURA) 之间解除全部的服务合同关系。', en: '1. Once this deactivation agreement is signed, it represents the termination of all service contract relations between you and ECHORURA.', ja: '1. この無効化合意書に署名すると、お客様とECHORURAの間のすべてのサービス契約関係が終了します。' },
  'profile.agreement_doc_p2': { zh: '2. 根据智能合约的去中心化属性，用户知悉并同意其名下已发行的 MusicIP (ERC-1155) 的总供应量、被他人持有的“共创共享权益/版权股权”将永久存在于 Base Sepolia 区块链上。平台无权且无法对此进行物理销毁或冻结。', en: '2. According to the decentralized nature of smart contracts, the user acknowledges and agrees that the total supply of MusicIP (ERC-1155) issued under their name and the "Co-creation Shared Equity/Copyright Equity" held by others will permanently exist on the Base Sepolia blockchain. The platform has no right and cannot physically destroy or freeze it.', ja: '2. スマートコントラクトの分散型の性質に基づき、ユーザーは自身の名前で発行されたMusicIP (ERC-1155)の総供給量、および他人が保有する「共創共有持分/著作権持分」がBase Sepoliaブロックチェーン上に恒久的に存在することに同意し、これを認めます。プラットフォームはこれを物理的に破壊または凍結することはできず、実行できません。' },
  'profile.agreement_doc_p3': { zh: '3. 用户在此不可撤销地同意：授权极声音乐将原账户下所有歌曲作品的所有人名称更改为“匿名创作者 (Anonymous Creator)”，并将其关联的头像更换为系统预设头像，以完全履行《个人资料（私隐）条例》对注销账户的个人隐私清除义务。', en: '3. The user hereby irrevocably agrees to authorize ECHORURA to change the owner name of all songs under the original account to "Anonymous Creator", and replace its associated avatar with the system default, in order to fully perform the personal data privacy erasure obligations for account deactivation under the Personal Data (Privacy) Ordinance.', ja: '3. ユーザーは、個人データ（プライバシー）条例に基づくアカウント無効化のための個人プライバシー消去義務を完全に履行するため、元のマイアカウントのすべての楽曲の所有者名を「匿名クリエイター (Anonymous Creator)」に変更し、関連するアバターをシステムデフォルトのものに置き換えることをECHORURAに不可逆的に同意し、承認します。' },
  'profile.agreement_doc_p4': { zh: '4. 用户知悉并同意自愿放弃注销账户内存储的所有“ECHO 积分/Token”及其他平台专属权益，平台对于未来因歌曲产生的版权分红在此账户注销后不承担任何保管、兑付、重开账户划转的法律责任。', en: '4. The user acknowledges and agrees to voluntarily forfeit all "ECHO credits/tokens" and other platform-exclusive benefits stored in the deactivated account. ECHORURA bears no legal responsibility for the custody, redemption, or transfer of future copyright dividends generated by the songs after this account is deactivated.', ja: '4. ユーザーは、無効化されたアカウントに保存されているすべての「ECHOクレジット/トークン」およびその他のプラットフォーム限定の特典を自発的に放棄することに同意し、これを認めます。ECHORURAは、このアカウントの無効化後に楽曲から発生する将来の著作権配当の保管、引き換え、またはアカウント再開設による転送について、一切の法的責任を負いません。' },
  'profile.agreement_checkbox': { zh: '我已仔细阅读并完全同意上述《极声音乐共享资产存续与注销协议》，我在此不可撤销地确认放弃我名下的全部积分余额。', en: 'I have carefully read and fully agree to the above ECHORURA Shared Asset Retention & Deactivation Agreement, and I hereby irrevocably confirm that I forfeit all credit balances under my name.', ja: '私は上記のECHORURA共有資産の存続および無効化に関する合意書を注意深く読み、完全に同意しました。ここに、私の名前のすべてのクレジット残高を放棄することを不可逆的に確認します。' },
  'profile.confirm_by_display_name': { zh: '请输入您的艺名 "{name}" 进行最终注销确认：', en: 'Please enter your stage name "{name}" for final deactivation confirmation:', ja: '最終的な無効化確認のため、ステージ名「{name}」を入力してください：' },
  'profile.confirm_by_display_name_placeholder': { zh: '在此输入您的艺名以确认', en: 'Enter your stage name here to confirm', ja: '確認のためにここにステージ名を入力してください' },
  'profile.step_previous': { zh: '上一步', en: 'Previous Step', ja: '前のステップ' },
  'profile.erasing_progress': { zh: '数字足迹抹除中...', en: 'Erasing digital footprint...', ja: 'デジタルフットプリントを消去中...' },
  'profile.confirm_deactivate_erase': { zh: '我确认注销并抹除隐私', en: 'Confirm Deactivation & Erase Privacy', ja: '無効化の確定とプライバシーの消去' },
  'profile.deactivate_success_title': { zh: '数字痕迹抹除完毕', en: 'Digital Footprint Cleared', ja: 'デジタル痕跡の消去完了' },
  'profile.deactivate_success_subtitle': { zh: 'Digital consciousness faded successfully', en: 'Digital consciousness faded successfully', ja: 'Digital consciousness faded successfully' },
  'profile.deactivate_success_desc': { zh: '正在解除您与极声音乐 (ECHORURA) 的所有数字链结... \n感谢您曾经与我们共享这段美妙的音乐共创旅程！', en: 'Severing all digital connections between you and ECHORURA... \nThank you for sharing this wonderful music co-creation journey with us!', ja: 'あなたとECHORURAの間のすべてのデジタル接続を切断しています... \n私たちとこの素晴らしい音楽共創の旅を共有していただき、ありがとうございました！' },

  // Profile Help Center & FAQ
  'profile.help_center_title': { zh: '极声帮助中心 (Help Center)', en: 'ECHORURA Help Center', ja: 'ECHORURAヘルプセンター' },
  'profile.help_center_subtitle': { zh: 'Platform FAQ & Creator Guide', en: 'Platform FAQ & Creator Guide', ja: 'Platform FAQ & Creator Guide' },
  'profile.close_faq': { zh: '关闭', en: 'Close', ja: '閉じる' },
  'profile.tab_guide': { zh: '🚀 平台使用指南', en: '🚀 Platform Guide', ja: '🚀 案内ガイド' },
  'profile.tab_credits': { zh: '🪙 {token}获取', en: '🪙 Earn {token}', ja: '🪙 {token}を獲得' },
  'profile.tab_equity': { zh: '🎼 {equity}', en: '🎼 {equity}', ja: '🎼 {equity}' },
  'profile.tab_arena': { zh: '🏆 听审竞技场机制', en: '🏆 Curation Arena', ja: '🏆 投票アリーナ' },
  'profile.guide_title': { zh: '极声音乐快速上手指南 (ECHORURA Platform Guide)', en: 'ECHORURA Platform Guide', ja: 'ECHORURAプラットフォーム案内' },
  'profile.guide_desc': { zh: '欢迎来到极声音乐！本平台采用去中心化的共享共创模型，为乐迷和创作者构建起无中介的价值链接。以下是核心使用方法：', en: 'Welcome to ECHORURA! This platform adopts a decentralized co-creation model to build an intermediate-free value link for music fans and creators. Here is how to get started:', ja: 'ECHORURAへようこそ！当プラットフォームは、分散型共創モデルを採用し、音楽ファンとクリエイターのための仲介者のない価値链接を構築します。開始手順は以下の通りです：' },
  'profile.guide_step1_title': { zh: '第一步：加入平台与获取初始积分', en: 'Step 1: Join Platform & Earn Initial Credits', ja: 'ステップ1：プラットフォームへの参加と初期クレジットの獲得' },
  'profile.guide_step1_desc': { zh: '注册并登录极声账户后，系统会自动为你建立去中心化标识。你可通过完成日常活动（如收听、打榜、签到等）轻松积累创作者初始的 <strong>{token}</strong>，或通过充值入口划转所需积分。', en: 'After registering and logging in, the system automatically builds your decentralized identity. You can easily accumulate initial <strong>{token}</strong> by completing daily activities (listening, voting, checking in, etc.), or top up credits.', ja: '登録してログインすると、システムが自動的に分散型IDを構築します。日常のアクティビティ（試聴、投票、チェックインなど）を完了することで、初期の <strong>{token}</strong> を簡単に蓄積したり、クレジットをチャージしたりできます。' },
  'profile.guide_step2_title': { zh: '第二步：参与优秀歌曲的“共创共享”', en: 'Step 2: Participate in Co-creation & Sharing', ja: 'ステップ2：共創と共有への参加' },
  'profile.guide_step2_desc': { zh: '在“共创市场 (Studio/Market)”中，优秀创作者在发布新歌时通常会拿出一部分（如 50%）的 <strong>{equity}</strong> 进行社区发行。你可以使用 <strong>{token}</strong> 认购这些份额，成为这首歌曲的社区“共创合伙人”。', en: 'In the "Co-creation Market (Studio/Market)", outstanding creators usually release a portion (e.g., 50%) of <strong>{equity}</strong> to the community when publishing new songs. You can subscribe to these shares using <strong>{token}</strong> to become a community "co-creation partner".', ja: '「共創マーケット (Studio/Market)」では、優れたクリエイターが新曲を公開する際、通常は <strong>{equity}</strong> の一部（例：50％）をコミュニティにリリースします。 <strong>{token}</strong> を使用してこれらのシェアを購読し、コミュニティの「共創パートナー」になることができます。' },
  'profile.guide_step3_title': { zh: '第三步：歌曲播放，全自动分红共享', en: 'Step 3: Music Playback & Automatic Royalty Dividends', ja: 'ステップ3：楽曲の再生と自動ロイヤリティ配当' },
  'profile.guide_step3_desc': { zh: '一旦该歌曲在平台被乐迷播放，其产生的播放收益将触发<strong>去中心化分配协议</strong>，按秒自动分红。其中 30% 分配给当前收听的乐迷，另外 70% 分配给持有这首歌的全体“权益持有人”（包括你和创作者本身）。', en: 'Once the song is played on the platform, its playback revenue triggers the <strong>decentralized distribution agreement</strong> for real-time dividends. 30% is allocated to the listening fan, and 70% to all "equity holders" (including you and the creator).', ja: 'プラットフォームで曲が再生されると、その再生収益が<strong>分散型配信契約</strong>をトリガーし、リアルタイムで配当が行われます。30％は試聴中のファンに、70％はこの曲のすべての「持分保有者」（あなたとクリエイターを含む）に分配されます。' },
  'profile.guide_step4_title': { zh: '第四步：创作者发布作品与竞技打榜', en: 'Step 4: Publish Works & Join Curation Arena', ja: 'ステップ4：作品の公開と投票アリーナへの参加' },
  'profile.guide_step4_desc': { zh: '如果你是创作者，可以直接上传作品。为了能让歌曲直接登上首页“本日推荐榜”获得曝光，建议使用 10 ECHO 积分参与“去中心化听审竞技场”，通过大众投票赢取返还和超级推广资源。', en: 'If you are a creator, you can upload works directly. To get featured on the homepage "Today\'s Recommended List", we suggest staking 10 ECHO to join the "Decentralized Curation Arena" to win back your stake and unlock premium promotion resources via community votes.', ja: 'クリエイターの方は、作品を直接アップロードできます。ホームページの「本日のおすすめリスト」に掲載されるには、10 ECHOを質押して「分散型投票アリーナ」に参加し、コミュニティ投票を通じて保証金を取り戻し、プレミアムプロモーションリソースを獲得することをお勧めします。' },
  'profile.credits_title': { zh: '如何获取与使用 {token}？', en: 'How to Obtain & Use {token}?', ja: '{token}の獲得と使用方法について' },
  'profile.credits_q1': { zh: 'Q: 什么是 {token}？', en: 'Q: What is {token}?', ja: 'Q: {token}とは何ですか？' },
  'profile.credits_a1': { zh: '这是极声去中心化社区中唯一流转的系统积分凭证。可用于认购歌曲的<strong>{equity}</strong>、给喜欢的作品打榜投票、打赏创作者，或者充值和划转。', en: 'This is the only system credit voucher circulating in the ECHORURA decentralized community. It can be used to subscribe to song <strong>{equity}</strong>, vote for works, tip creators, top up, or transfer.', ja: 'これはECHORURA分散型コミュニティで循環する唯一の系統クレジットバウチャーです。曲の <strong>{equity}</strong> の購読、作品への投票、クリエイターへの投げ銭、チャージ、転送に使用できます。' },
  'profile.credits_q2': { zh: 'Q: 如何免费“听歌挖矿”获取积分？', en: 'Q: How to earn credits via "Listen to Earn" for free?', ja: 'Q: 無料の「聴いて稼ぐ」でクレジットを獲得するには？' },
  'profile.credits_a2': { zh: '当你在极声音乐收听任何歌曲时，每一次播放产生的收益，都会分出 30% 作为<strong>聆听激励</strong>当即返还到你的平台账户。也就是说，听歌即可持续产生积分！', en: 'When you listen to any song on ECHORURA, 30% of the revenue generated by each playback will be instantly returned to your platform account as a <strong>listening incentive</strong>. That is, listening to music can continuously generate credits!', ja: 'ECHORURAで曲を聴くと、各再生で発生する収益の30％が、<strong>リスニングインセンティブ</strong>として即座にプラットフォームアカウントに返還されます。つまり、音楽を聴くだけで継続的にクレジットを獲得できます！' },
  'profile.credits_q3': { zh: 'Q: 创作者有什么免费获取途径？', en: 'Q: Are there free ways for creators to earn credits?', ja: 'Q: クリエイターがクレジットを無料で獲得する方法はありますか？' },
  'profile.credits_a3': { zh: '每当创作者成功发布一首原创歌曲，平台会自动派发 <strong>1.00 ECHO 积分</strong> 的普通发布补贴，鼓励持续创作。', en: 'Every time a creator successfully publishes an original song, the platform automatically issues a basic publishing subsidy of <strong>1.00 ECHO credits</strong> to encourage continuous creation.', ja: 'クリエイターがオリジナル曲の公開に成功するたびに、プラットフォームは継続的な創作を推奨するために <strong>1.00 ECHOクレジット</strong> の基本公開補助金を自動的に発行します。' },
  'profile.credits_q4': { zh: 'Q: 支持法币充值吗？', en: 'Q: Does it support fiat currency top-up?', ja: 'Q: 法定通貨でのチャージはサポートされていますか？' },
  'profile.credits_a4': { zh: '支持。极声对接了安全的法币（如港币 HKD / 美元 USD）积分充值接口，可在个人账户余额处点击充值，按照约 {fiatRate} 的固定兑换比例一键购入。', en: 'Yes. ECHORURA has integrated a secure fiat (e.g., HKD / USD) credit recharge interface. You can click top up at your personal account balance and purchase with a fixed exchange rate of around {fiatRate}.', ja: 'はい。ECHORURAは安全な法定通貨（HKD / USDなど）クレジットチャージインターフェースを統合しています。個人アカウント残高でチャージをクリックし、約 {fiatRate} の固定為替レートでワンクリック購入できます。' },

  // Profile Equity Details
  'profile.equity_title': { zh: '理解“{equity}”分成机制', en: 'Understanding the "{equity}" Sharing Mechanism', ja: '「{equity}」分配メカニズムの理解' },
  'profile.equity_desc': { zh: '极声倡导的是“共创共享”的音乐共享经济理念。每一首发布的优秀歌曲都不再专属于创作者一人，而是属于所有支持过它的社区粉丝。', en: 'ECHORURA advocates the concept of "co-creation and sharing" in music sharing economy. Every outstanding song published no longer belongs solely to the creator, but to all community fans who supported it.', ja: 'ECHORURAは、音楽共有経済における「共創と共有」の概念を提唱しています。公開された優れた曲は、もはやクリエイターだけの持ち物ではなく、それをサポートしたすべてのコミュニティファンのものです。' },
  'profile.equity_section1_title': { zh: '1. 什么是共创认购 (Music IPO)？', en: '1. What is Co-creation Subscription (Music IPO)?', ja: '1. 共創サブスクリプション (Music IPO) とは？' },
  'profile.equity_section1_desc': { zh: '创作者在上架歌曲时，可开启“歌曲共创”并设定发行总份额。例如：设定总权益 1000 份，出售 50%。乐迷们可以使用积分进行认购，这些购买积分将划转给创作者，用于补贴前期的音乐制作成本。', en: 'When publishing a song, creators can enable "song co-creation" and set the total shares to be issued. For example: set total equity to 1000 shares and sell 50%. Music fans can subscribe using credits. These credits will be transferred to the creator to subsidize music production costs.', ja: '曲を公開する際、クリエイターは「楽曲の共創」を有効にし、発行する総シェア数を設定できます。例：総持分を1000シェアに設定し、50％を販売します。音楽ファンはクレジットを使用して購読できます。これらのクレジットはクリエイターに転送され、音楽制作の初期費用に充てられます。' },
  'profile.equity_section2_title': { zh: '2. 分红是如何自动分配的？', en: '2. How are dividends automatically distributed?', ja: '2. 配当はどのように自動的に分配されますか？' },
  'profile.equity_section2_desc': { zh: '当用户在线播放这首歌时，单次收听产生的平台总收益池中：\n• <strong>30%</strong> 直接作为“收听奖励”到账给收听的这位乐迷；\n• <strong>70%</strong> 作为“共创分红收益”注入这首歌的歌曲公共收益池，并按照全体权益人的持股比例，全自动发放到账！即使原作者离线或注销，这笔收益依然会永久有效。', en: 'When a user plays this song online, in the platform\'s total revenue pool generated by a single play:\n• <strong>30%</strong> is directly credited to the listening fan as a "listening reward";\n• <strong>70%</strong> is injected into the song\'s public revenue pool as "co-creation dividend income", and is automatically distributed based on the shareholding ratio of all equity holders! Even if the creator goes offline or deactivates, this dividend remains permanently active.', ja: 'ユーザーがこの曲をオンラインで再生すると、1回の再生によって生成されるプラットフォームの総収益プールにおいて：\n• <strong>30%</strong> は「試聴報酬」として試聴したファンに直接入金されます。\n• <strong>70%</strong> は「共創配当収益」として曲のパブリック収益プールに注入され、すべての持分保有者の持分比率に基づいて自動的に分配されます！原作者がオフラインになったり無効化されたりしても、この配当は恒久的に有効です。' },

  // Profile Arena Details
  'profile.arena_title': { zh: '什么是“三日循环竞技赛制”？', en: 'What is the "3-Day Cycle Arena Rules"?', ja: '「3日間サイクルアリーナ規則」とは？' },
  'profile.arena_q1': { zh: 'Q: 什么是“听审竞技场”的三日运转周期？', en: 'Q: What is the 3-day cycle of the Curation Arena?', ja: 'Q: 投票アリーナの3日間サイクルとは何ですか？' },
  'profile.arena_a1': { zh: '为提升打榜含金量，极声设计了滚动式的**“三日周期竞争淘汰制”**：\n• <strong>第一天：报名期 (Registration Day)</strong> — 开放打榜报名，创作者可通过质押 10.00 ECHO 发起打榜申请。<strong>每日名额仅限 20 首</strong>，满额即关闭报名通道。\n• <strong>第二天：听审期 (Voting Day)</strong> — 报名曲目锁定，进入盲听分发池。社区用户（听审员）在此阶段进行试听并投下 Upvote（支持）或 Down（下沉）选票，系统实时排序计算排名。\n• <strong>第三天：公示榜单期 (Showcase Day)</strong> — 投票截止。胜出的优秀作品将正式登上极声主页黄金曝光位 <strong>“今日推荐榜”</strong>！', en: 'To enhance the value of ranking, ECHORURA designed a rolling **"3-Day Cycle Competition & Elimination System"**:\n• <strong>Day 1: Registration Day</strong> — Open for ranking sign-ups. Creators can apply by staking 10.00 ECHO. <strong>Limit is 20 songs per day</strong>, and registration closes once full.\n• <strong>Day 2: Voting Day</strong> — Registered tracks are locked and enter the blind listening pool. Community members (curators) listen and cast Upvote or Down votes, and the system ranks them in real-time.\n• <strong>Day 3: Showcase Day</strong> — Voting closes. Winning works will officially be featured on ECHORURA homepage\'s premium showcase spot, <strong>"Today\'s Recommendations"</strong>!', ja: 'ランキングの価値を高めるため、ECHORURAはローリング式の**「3日間サイクル競争・淘汰システム」**を設計しました：\n• <strong>1日目：登録日 (Registration Day)</strong> — ランキング登録を開始します。クリエイターは 10.00 ECHO を質押して申請できます。<strong>1日あたり20曲限定</strong>で、満員になり次第登録を締め切ります。\n• <strong>2日目：投票日 (Voting Day)</strong> — 登録されたトラックがロックされ、ブラインドリスニングプールに入ります。コミュニティメンバー（キュレーター）が試聴してUpvote（支持）またはDown（下沉）を投票し、システムがリアルタイムでランク付けします。\n• <strong>3日目：展示日 (Showcase Day)</strong> — 投票が締め切られます。勝者作品は、ECHORURAホームページのプレミアム展示スポット<strong>「今日のおすすめ」</strong>に正式に掲載されます！' },
  'profile.arena_q2': { zh: 'Q: 淘汰规则与保证金分红如何结算？', en: 'Q: How are elimination rules & staked dividend settlements calculated?', ja: 'Q: 淘汰ルールと質押配当の決済はどのように計算されますか？' },
  'profile.arena_a2': { zh: '根据每轮批次报名的歌曲总数，结算规则如下：\n<strong>1. 单期报名歌曲达 10 首或以上（最高 20 首）：</strong>\n• <strong>第 1 至 10 名（胜出）</strong>：歌曲成功晋级首页<strong>“今日推荐榜”</strong>，并<strong>全额退回 10.00 ECHO 保证金</strong>！\n• <strong>第 11 名及以后（淘汰）</strong>：歌曲转为普通作品；创作者质押的 <strong>10.00 ECHO 保证金被没收，实时平分给所有参与本次打分投票的听审员</strong>，作为对社区伯乐的劳动报酬。\n<strong>2. 单期报名歌曲不足 10 首时（少人兜底保护）：</strong>\n• <strong>全员免遭淘汰</strong>：所有报名歌曲无视竞争直接成功晋级首页<strong>“今日推荐榜”</strong>！\n• <strong>质押伯乐分红</strong>：在此情况下，创作者的 <strong>10.00 ECHO 保证金不予退还，而是全部充作社区伯乐激励，均匀平分给本期参与投票的所有听审员</strong>。', en: 'According to the total number of songs registered in each batch, the settlement rules are as follows:\n<strong>1. When registered songs are 10 or more (max 20):</strong>\n• <strong>Rank 1 to 10 (Winners)</strong>: Successfully featured on the homepage\'s <strong>"Today\'s Recommendations"</strong>, and <strong>10.00 ECHO stake is refunded in full</strong>!\n• <strong>Rank 11 and below (Eliminated)</strong>: Turned into ordinary songs; the creator\'s staked <strong>10.00 ECHO is forfeited and split equally among all curators who participated in voting</strong> as rewards.\n<strong>2. When registered songs are less than 10 (low attendance protection):</strong>\n• <strong>Everyone avoids elimination</strong>: All registered songs successfully featured on the <strong>"Today\'s Recommendations"</strong> regardless of competition!\n• <strong>Staked Curator Dividend</strong>: In this case, the creator\'s staked <strong>10.00 ECHO is not refunded, but is entirely used as curator incentives, split equally among all curators who participated in voting</strong>.', ja: '各バッチに登録された曲の総数に応じて、決済ルールは以下の通りです：\n<strong>1. 登録曲が10曲以上の場合（最大20曲）：</strong>\n• <strong>1〜10位（勝者）</strong>：ホームページの <strong>「今日のおすすめ」</strong> に正常に掲載され、<strong>10.00 ECHO の質押金が全額返金されます</strong>！\n• <strong>11位以下（淘汰）</strong>：通常の曲に変換されます。クリエイターが質押した <strong>10.00 ECHO は没収され、投票に参加したすべてのキュレーターに均等に分配されます</strong>。\n<strong>2. 登録曲が10曲未満の場合（低参加保護）：</strong>\n• <strong>全員が淘汰を回避</strong>：競争に関係なく、すべての登録曲が <strong>「今日のおすすめ」</strong> に正常に掲載されます！\n• <strong>質押キュレーター配当</strong>：この場合、クリエイターが質押した <strong>10.00 ECHO は返金されず、すべてキュレーターのインセンティブとして使用され、投票に参加したすべてのキュレーターに均等に分配されます</strong>。' },

  // Profile About Us & Compliance Detail
  'profile.about_compliance_title': { zh: '关于极声与合规说明', en: 'About ECHORURA & Compliance', ja: 'ECHORURAについてとコンプライアンス説明' },
  'profile.about_compliance_subtitle': { zh: 'Platform Vision & Compliance', en: 'Platform Vision & Compliance', ja: 'Platform Vision & Compliance' },
  'profile.about_us_section_title': { zh: '🏢 关于我们', en: '🏢 About Us', ja: '🏢 私たちについて' },
  'profile.about_us_desc': { zh: 'ECHORURA MUSIC 是由<strong class="text-white">极声科技公司</strong>创建的去中心化音乐平台。', en: 'ECHORURA MUSIC is a decentralized music platform created by <strong class="text-white">Piscesoul Technology Company</strong>.', ja: 'ECHORURA MUSICは、<strong class="text-white">极声科技公司</strong>によって構築された分散型音楽プラットフォームです。' },
  'profile.about_us_contact': { zh: '联系我们：', en: 'Contact Us: ', ja: 'お問い合わせ：' },
  'profile.about_us_rights': { zh: '极声科技公司 (ECHORURA Technologies). All Rights Reserved.', en: 'ECHORURA Technologies. All Rights Reserved.', ja: 'ECHORURA Technologies. All Rights Reserved.' },
  'profile.mission_vision_title': { zh: '🌟 我们的使命愿景', en: '🌟 Our Mission & Vision', ja: '🌟 私たちの使命とビジョン' },
  'profile.mission_vision_desc': { zh: 'ECHORURA MUSIC 致力于应用前沿的<strong>去中心化共享经济理念</strong>和分布式数字记账协议，彻底重塑音乐价值链。我们将 90% 以上的聆听与发行收益交还给创作者与乐迷社区，让音乐不再受大型流媒体平台的层层中介盘剥，实现真正意义上的“创作者经济共创共享”。', en: 'ECHORURA MUSIC is dedicated to applying cutting-edge <strong>decentralized sharing economy concepts</strong> and distributed ledger protocols to completely reshape the music value chain. We return more than 90% of listening & publishing earnings to creators and the fan community, freeing music from the exploitation of intermediaries of large streaming platforms, achieving true "creator economy co-creation & sharing".', ja: 'ECHORURA MUSICは、最先端の<strong>分散型共有経済の概念</strong>と分散型台帳プロトコルを適用して、音楽バリューチェーンを完全に再構築することに専念しています。試聴と配信収益の90％以上をクリエイターとファンコミュニティに還元し、大規模なストリーミングプラットフォームの手によって搾取される音楽から解放し、真の意味での「クリエイターエコノミー共創共有」を実現します。' },
  'profile.compliance_status_title': { zh: '当前部署版本合规状态公示', en: 'Official Compliance Status of Current Deployment', ja: '現在の展開バージョンの公式コンプライアンスステータス' },
  'profile.compliance_entity_version': { zh: '运营实体版本:', en: 'Operating Entity Version:', ja: '運営エンティティバージョン：' },
  'profile.compliance_entity_hk': { zh: 'ECHORURA MUSIC共享经济版', en: 'ECHORURA MUSIC Shared Economy Edition', ja: 'ECHORURA MUSIC共有経済版' },
  'profile.compliance_entity_sg': { zh: 'ECHORURA Singapore badges Edition', en: 'ECHORURA Singapore badges Edition', ja: 'ECHORURA Singapore badges Edition' },
  'profile.compliance_entity_global': { zh: 'ECHORURA Global Web3 Edition', en: 'ECHORURA Global Web3 Edition', ja: 'ECHORURA Global Web3 Edition' },
  'profile.compliance_core_tech': { zh: '核心技术特征:', en: 'Core Tech Features:', ja: 'コア技術特徴：' },
  'profile.compliance_core_tech_val': { zh: '去中心化分布式架构 / 密码学存证校验', en: 'Decentralized Distributed Architecture / Cryptographic Proof Verification', ja: '分散型分散アーキテクチャ / 暗号証明検証' },
  'profile.compliance_exemption': { zh: '合规豁免说明:', en: 'Compliance Exemption:', ja: 'コンプライアンス免責事項説明：' },
  'profile.compliance_exemption_val': { zh: '香港合规模式 - 基于共享使用权积分构建，不涉及 any 代币发行', en: 'HK Compliance Mode - Built on shared utility credits, no token issuance involved', ja: '香港コンプライアンスモード - 共有使用権クレジットに基づく構築、トークン発行は一切含まず' },
  'profile.compliance_transparency_disclosure': { zh: '💡 <strong>技术透明披露：</strong> 本平台账本记录及积分划转底层协议完全由去中心化公开审计的分布式校验代码自动签署运行。所有积分到账和共创共享权益分配的规则直接固化在密码学校验算法中，保障任何一方（包括平台本身）均无法被单方面篡改和没收。', en: '💡 <strong>Technical Transparency Disclosure:</strong> The ledger records and credit transfer protocols of this platform are completely automatically signed and executed by decentralized, publicly audited distributed validation code. All rules for credit accruals and co-creation equity distribution are directly solidified in cryptographic validation algorithms, ensuring that no party (including the platform itself) can unilaterally tamper with or confiscate them.', ja: '💡 <strong>技術透明性の開示：</strong> 当プラットフォームの台帳記録およびクレジット転送プロトコルは、分散型の一般公開監査された分散型検証コードによって完全に自動的に署名・実行されます。クレジット獲得と共創持分分配のすべての規則は暗号検証アルゴリズムに直接固定されており、いかなる当事者（プラットフォーム自体を含む）も一方的に改ざんまたは没収することはできません。' },
  'profile.compliance_button': { zh: '我知道了', en: 'I Understand', ja: 'わかりました' },

  // Profile Change Password Modal
  'profile.change_password_title': { zh: '修改账户密码', en: 'Change Password', ja: 'パスワード変更' },
  'profile.change_password_subtitle': { zh: 'Change Account Password', en: 'Change Account Password', ja: 'Change Account Password' },
  'profile.change_password_new_label': { zh: '输入新密码 (不低于6位)', en: 'Enter New Password (min 6 chars)', ja: '新しいパスワードを入力してください (6文字以上)' },
  'profile.change_password_confirm_label': { zh: '确认新密码', en: 'Confirm New Password', ja: '新しいパスワードの確認' },
  'profile.change_password_submit': { zh: '确认修改密码', en: 'Confirm Change Password', ja: 'パスワード変更を確定' },
  'profile.change_password_loading': { zh: '正在修改密码...', en: 'Changing password...', ja: 'パスワードを変更中...' },

  // Profile Feedback Modal
  'profile.feedback_title': { zh: '意见与问题反馈', en: 'Submit Feedback', ja: 'フィードバック' },
  'profile.feedback_subtitle': { zh: 'Submit Feedback Ticket', en: 'Submit Feedback Ticket', ja: 'Submit Feedback Ticket' },
  'profile.feedback_username_label': { zh: '用户名 (Username)', en: 'Username', ja: 'ユーザー名' },
  'profile.feedback_content_label': { zh: '反馈与意见内容 (Feedback Content)', en: 'Feedback Content', ja: 'フィードバック内容' },
  'profile.feedback_placeholder': { zh: '请详细描述您遇到的问题、改进意见或合作意向。我们将在第一时间向您的系统关联邮箱/电话回复反馈结果...', en: 'Please describe the issues you encountered, suggestions, or business cooperation proposals in detail. We will reply to your registered email/phone as soon as possible...', ja: '発生した問題、改善提案、またはビジネス提携の提案を詳細に記述してください。登録されたメール/電話にできるだけ早く返信いたします...' },
  'profile.feedback_cancel': { zh: '取消', en: 'Cancel', ja: 'キャンセル' },
  'profile.feedback_send': { zh: '发送', en: 'Send', ja: '送信' },
  'profile.feedback_sending': { zh: '正在发送...', en: 'Sending...', ja: '送信中...' },
};
export const useLanguageStore = create<LanguageState>()(
  persist(
    (set, get) => ({
      language: 'zh',
      setLanguage: (lang) => set({ language: lang }),
      t: (key) => {
        const lang = get().language;
        return translations[key]?.[lang] || key;
      },
    }),
    {
      name: 'echo-language-storage',
    }
  )
);
