export const FALLBACK_SONGS = [
  {
    id: 'mock-1',
    title: 'Neon Dreamscape #1',
    artist: 'AI Mozart',
    cover_url: 'https://picsum.photos/seed/11/400/400',
    audio_url: 'https://www.soundhelix.com/examples/mp3/SoundHelix-Song-1.mp3',
    earn_rate: 0.5,
    tags: ['流行'],
    moods: ['热血'],
    ipo_percentage: 15,
    total_shares: 100,
    remaining_shares: 15,
    is_ipo_active: true,
    play_count: 1240,
    creator: { display_name: 'AI Mozart', avatar_url: 'https://api.dicebear.com/7.x/avataaars/svg?seed=Mozart' }
  },
  {
    id: 'mock-2',
    title: 'Cyber Symphony',
    artist: 'Echo Creator',
    cover_url: 'https://picsum.photos/seed/12/400/400',
    audio_url: 'https://www.soundhelix.com/examples/mp3/SoundHelix-Song-2.mp3',
    earn_rate: 0.8,
    tags: ['电子'],
    moods: ['午夜'],
    ipo_percentage: 30,
    total_shares: 500,
    remaining_shares: 120,
    is_ipo_active: true,
    play_count: 850,
    creator: { display_name: 'Echo Creator', avatar_url: 'https://api.dicebear.com/7.x/avataaars/svg?seed=Echo' }
  },
  {
    id: 'mock-3',
    title: 'Midnight Pulse',
    artist: 'Digital Ghost',
    cover_url: 'https://picsum.photos/seed/13/400/400',
    audio_url: 'https://www.soundhelix.com/examples/mp3/SoundHelix-Song-1.mp3',
    earn_rate: 0.3,
    tags: ['流行'],
    moods: ['伤感'],
    ipo_percentage: 10,
    total_shares: 200,
    remaining_shares: 0,
    is_ipo_active: true,
    play_count: 3200,
    creator: { display_name: 'Digital Ghost', avatar_url: 'https://api.dicebear.com/7.x/avataaars/svg?seed=Ghost' }
  },
  {
    id: 'mock-4',
    title: 'Ethereal Vibes',
    artist: 'Bit Composer',
    cover_url: 'https://picsum.photos/seed/14/400/400',
    audio_url: 'https://www.soundhelix.com/examples/mp3/SoundHelix-Song-2.mp3',
    earn_rate: 0.6,
    tags: ['爵士'],
    moods: ['治愈'],
    ipo_percentage: 0,
    is_ipo_active: false,
    play_count: 450,
    creator: { display_name: 'Bit Composer', avatar_url: 'https://api.dicebear.com/7.x/avataaars/svg?seed=Bit' }
  },
  {
    id: 'mock-5',
    title: 'Solar Flare',
    artist: 'Future Sound',
    cover_url: 'https://picsum.photos/seed/15/400/400',
    audio_url: 'https://www.soundhelix.com/examples/mp3/SoundHelix-Song-1.mp3',
    earn_rate: 0.9,
    tags: ['摇滚'],
    moods: ['热血'],
    ipo_percentage: 5,
    total_shares: 1000,
    remaining_shares: 950,
    is_ipo_active: true,
    play_count: 210,
    creator: { display_name: 'Future Sound', avatar_url: 'https://api.dicebear.com/7.x/avataaars/svg?seed=Future' }
  }
];
