-- ==========================================
-- ECHORURA 社区帖子表 (community_posts) v2
-- 修复：外键指向 profiles 表 + 补充 anon 权限授权
-- 请在 Memfire Cloud -> SQL Editor 中运行
-- ==========================================

-- 如果旧表存在，先删掉重建（修正外键关联）
DROP TABLE IF EXISTS public.community_posts CASCADE;

CREATE TABLE public.community_posts (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  -- 注意：外键指向 profiles(id) 而不是 auth.users(id)
  -- 这样 PostgREST 才能用 creator:profiles(...) 做 join
  creator_id UUID REFERENCES public.profiles(id) ON DELETE CASCADE NOT NULL,
  content TEXT NOT NULL,
  type TEXT NOT NULL DEFAULT 'social', -- 'proposal' (议事厅) | 'social' (广场)
  likes INTEGER DEFAULT 0,
  created_at TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc'::text, now()) NOT NULL
);

-- 开启 RLS 安全策略
ALTER TABLE public.community_posts ENABLE ROW LEVEL SECURITY;

-- 允许所有人（包括未登录访客）读取帖子
CREATE POLICY "Allow public read" ON public.community_posts
  FOR SELECT USING (true);

-- 允许已登录用户发帖
CREATE POLICY "Allow authenticated insert" ON public.community_posts
  FOR INSERT WITH CHECK (auth.uid() = creator_id);

-- 允许作者删除自己的帖子
CREATE POLICY "Allow author delete" ON public.community_posts
  FOR DELETE USING (auth.uid() = creator_id);

-- 明确授权 anon 和 authenticated 角色的 SELECT 权限
GRANT SELECT ON public.community_posts TO anon;
GRANT SELECT, INSERT, DELETE ON public.community_posts TO authenticated;
GRANT USAGE, SELECT ON SEQUENCE public.community_posts_id_seq TO authenticated;
