-- ==========================================
-- ECHORURA 社区评论表 (community_comments)
-- 请在 Memfire Cloud -> SQL Editor 中运行
-- ==========================================

CREATE TABLE IF NOT EXISTS public.community_comments (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  post_id BIGINT REFERENCES public.community_posts(id) ON DELETE CASCADE NOT NULL,
  creator_id UUID REFERENCES public.profiles(id) ON DELETE CASCADE NOT NULL,
  content TEXT NOT NULL,
  created_at TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc'::text, now()) NOT NULL
);

-- 开启 RLS 安全策略
ALTER TABLE public.community_comments ENABLE ROW LEVEL SECURITY;

-- 允许所有人读取评论
CREATE POLICY "Allow public read" ON public.community_comments
  FOR SELECT USING (true);

-- 允许已登录用户发布评论
CREATE POLICY "Allow authenticated insert" ON public.community_comments
  FOR INSERT WITH CHECK (auth.uid() = creator_id);

-- 允许作者删除自己的评论
CREATE POLICY "Allow author delete" ON public.community_comments
  FOR DELETE USING (auth.uid() = creator_id);

-- 明确授权 anon 和 authenticated 角色的操作权限
GRANT SELECT ON public.community_comments TO anon;
GRANT SELECT, INSERT, DELETE ON public.community_comments TO authenticated;
GRANT USAGE, SELECT ON SEQUENCE public.community_comments_id_seq TO authenticated;
