-- ==========================================
-- ECHORURA 歌曲乐评表与点赞字段 (song_comments & likes)
-- 请在 Memfire Cloud -> SQL Editor 中运行
-- ==========================================

-- 1. 为现有的 songs 表新增 likes 字段（如果不存在的话）
ALTER TABLE public.songs ADD COLUMN IF NOT EXISTS likes INTEGER DEFAULT 0;

-- 允许对 songs 表的点赞数进行更新 (UPDATE 权限)
CREATE POLICY "Allow likes update on songs" ON public.songs
  FOR UPDATE USING (true) WITH CHECK (true);

-- 确保 authenticated 和 anon 都可以点赞
GRANT UPDATE(likes) ON public.songs TO authenticated, anon;


-- 2. 创建专属的歌曲乐评表 (song_comments)
CREATE TABLE IF NOT EXISTS public.song_comments (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  song_id BIGINT REFERENCES public.songs(id) ON DELETE CASCADE NOT NULL,
  creator_id UUID REFERENCES public.profiles(id) ON DELETE CASCADE NOT NULL,
  content TEXT NOT NULL,
  created_at TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc'::text, now()) NOT NULL
);

-- 开启 RLS 安全策略
ALTER TABLE public.song_comments ENABLE ROW LEVEL SECURITY;

-- 允许所有人读取乐评
CREATE POLICY "Allow public read" ON public.song_comments
  FOR SELECT USING (true);

-- 允许已登录用户发布乐评
CREATE POLICY "Allow authenticated insert" ON public.song_comments
  FOR INSERT WITH CHECK (auth.uid() = creator_id);

-- 允许作者删除自己的乐评
CREATE POLICY "Allow author delete" ON public.song_comments
  FOR DELETE USING (auth.uid() = creator_id);

-- 明确授权
GRANT SELECT ON public.song_comments TO anon;
GRANT SELECT, INSERT, DELETE ON public.song_comments TO authenticated;
GRANT USAGE, SELECT ON SEQUENCE public.song_comments_id_seq TO authenticated;
