-- ==========================================
-- ECHORURA MUSICCHAIN Artist Scoring Engine
-- 请在 Memfire Cloud -> SQL Editor 中运行此脚本
-- ==========================================

-- 1. 创建用户收藏表
CREATE TABLE IF NOT EXISTS public.user_favorites (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  user_id UUID REFERENCES public.profiles(id) ON DELETE CASCADE NOT NULL,
  song_id BIGINT REFERENCES public.songs(id) ON DELETE CASCADE NOT NULL,
  created_at TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc'::text, now()) NOT NULL,
  UNIQUE(user_id, song_id) -- 防止重复收藏
);

-- 开启 RLS
ALTER TABLE public.user_favorites ENABLE ROW LEVEL SECURITY;

CREATE POLICY "Allow public read favorites" ON public.user_favorites FOR SELECT USING (true);
CREATE POLICY "Allow authenticated insert favorites" ON public.user_favorites FOR INSERT WITH CHECK (auth.uid() = user_id);
CREATE POLICY "Allow authenticated delete favorites" ON public.user_favorites FOR DELETE USING (auth.uid() = user_id);

GRANT SELECT ON public.user_favorites TO anon;
GRANT SELECT, INSERT, DELETE ON public.user_favorites TO authenticated;


-- 2. 创建新锐艺人综合评分视图
-- 算法权重：播放=1, 点赞=2, 收藏=3
CREATE OR REPLACE VIEW public.emerging_artists_score AS
WITH 
  -- 统计每首歌的真实播放量 (从流水表计算)
  song_plays AS (
    SELECT song_id, COUNT(*) as plays
    FROM public.transactions
    WHERE type = 'listen_reward'
    GROUP BY song_id
  ),
  -- 统计每首歌的收藏量
  song_favorites AS (
    SELECT song_id, COUNT(*) as favorites
    FROM public.user_favorites
    GROUP BY song_id
  ),
  -- 汇总每个创作者旗下所有歌曲的数据
  artist_stats AS (
    SELECT 
      s.creator_id,
      SUM(COALESCE(sp.plays, 0)) as total_plays,
      SUM(COALESCE(s.likes, 0)) as total_likes,
      SUM(COALESCE(sf.favorites, 0)) as total_favorites
    FROM public.songs s
    LEFT JOIN song_plays sp ON s.id = sp.song_id
    LEFT JOIN song_favorites sf ON s.id = sf.song_id
    WHERE s.creator_id IS NOT NULL
    GROUP BY s.creator_id
  )
-- 计算最终得分并关联创作者信息
SELECT 
  p.id as creator_id,
  p.display_name as creator_name,
  p.avatar_url as creator_avatar,
  a.total_plays,
  a.total_likes,
  a.total_favorites,
  (a.total_plays * 1 + a.total_likes * 2 + a.total_favorites * 3) as artist_score
FROM artist_stats a
JOIN public.profiles p ON a.creator_id = p.id
ORDER BY artist_score DESC;

-- 授权读取视图
GRANT SELECT ON public.emerging_artists_score TO anon, authenticated, service_role;
