-- ==========================================
-- ECHORURA MUSICCHAIN Curation Arena Database Schema & RPCs
-- 请在 Memfire Cloud -> SQL Editor 中运行此脚本
-- ==========================================

-- 1. 创建报名表
CREATE TABLE IF NOT EXISTS public.arena_registrations (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  song_id BIGINT REFERENCES public.songs(id) ON DELETE CASCADE NOT NULL,
  creator_id UUID REFERENCES public.profiles(id) ON DELETE CASCADE NOT NULL,
  arena_date DATE NOT NULL DEFAULT (timezone('Asia/Shanghai', now())::date),
  stake_amount NUMERIC(10,2) NOT NULL DEFAULT 10.00,
  status TEXT NOT NULL DEFAULT 'pending', -- pending, voting, winner, loser, cancelled
  votes_count INTEGER DEFAULT 0,
  settled_at TIMESTAMP WITH TIME ZONE,
  created_at TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc'::text, now()) NOT NULL,
  UNIQUE(song_id, arena_date)
);

-- 开启 RLS
ALTER TABLE public.arena_registrations ENABLE ROW LEVEL SECURITY;
CREATE POLICY "Allow public read arena registrations" ON public.arena_registrations FOR SELECT USING (true);
GRANT SELECT ON public.arena_registrations TO anon, authenticated, service_role;

-- 2. 创建投票表
CREATE TABLE IF NOT EXISTS public.arena_votes (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  user_id UUID REFERENCES public.profiles(id) ON DELETE CASCADE NOT NULL,
  song_id BIGINT REFERENCES public.songs(id) ON DELETE CASCADE NOT NULL,
  arena_date DATE NOT NULL,
  vote_type TEXT NOT NULL DEFAULT 'up', -- 'up' (+1) or 'down' (-1)
  created_at TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc'::text, now()) NOT NULL,
  UNIQUE(user_id, song_id, arena_date)
);

-- 开启 RLS
ALTER TABLE public.arena_votes ENABLE ROW LEVEL SECURITY;
CREATE POLICY "Allow public read arena votes" ON public.arena_votes FOR SELECT USING (true);
GRANT SELECT ON public.arena_votes TO anon, authenticated, service_role;


-- 3. 报名 RPC (register_for_arena)
CREATE OR REPLACE FUNCTION public.register_for_arena(
    p_user_id UUID,
    p_song_id BIGINT
) RETURNS jsonb AS $$
DECLARE
    today_date DATE := (timezone('Asia/Shanghai', now())::date);
    today_count INTEGER;
    user_balance NUMERIC;
    song_creator UUID;
    already_registered BOOLEAN;
BEGIN
    -- A. 校验歌曲是否存在且归属当前用户
    SELECT creator_id INTO song_creator FROM public.songs WHERE id = p_song_id;
    IF song_creator IS NULL THEN
        RETURN jsonb_build_object('success', false, 'error', '歌曲不存在');
    END IF;
    IF song_creator != p_user_id THEN
        RETURN jsonb_build_object('success', false, 'error', '只能为自己的原创作品报名');
    END IF;

    -- B. 锁定并检查今天是否已报名过这首歌
    SELECT EXISTS(
        SELECT 1 FROM public.arena_registrations 
        WHERE song_id = p_song_id AND arena_date = today_date
    ) INTO already_registered;

    IF already_registered THEN
        RETURN jsonb_build_object('success', false, 'error', '该歌曲今日已报名听审竞技场，请勿重复操作');
    END IF;

    -- C. 独占锁检查今日报名总数限制 (排它锁防并发超限)
    -- 对今日报名的行进行锁定检查
    PERFORM id FROM public.arena_registrations 
    WHERE arena_date = today_date FOR UPDATE;

    SELECT COUNT(*) INTO today_count 
    FROM public.arena_registrations 
    WHERE arena_date = today_date;

    IF today_count >= 20 THEN
        RETURN jsonb_build_object('success', false, 'error', '今日听审竞技场报名人数已满（上限 20 首），请明日尽早报名！');
    END IF;

    -- D. 检查用户余额是否足够 10 ECHO
    SELECT balance INTO user_balance FROM public.wallets WHERE user_id = p_user_id FOR UPDATE;
    IF user_balance IS NULL OR user_balance < 10.00 THEN
        RETURN jsonb_build_object('success', false, 'error', '您的钱包 ECHO 余额不足 10.00，无法支付报名质押金');
    END IF;

    -- E. 扣除 10.00 ECHO 质押款
    UPDATE public.wallets 
    SET balance = balance - 10.00,
        updated_at = now()
    WHERE user_id = p_user_id;

    -- F. 记录扣款交易流水
    INSERT INTO public.transactions (user_id, amount, type, description, status, song_id)
    VALUES (p_user_id, -10.00, 'arena_stake', '听审竞技场质押金锁仓', 'settled', p_song_id);

    -- G. 写入报名记录 (状态为 pending 待进入投票期)
    INSERT INTO public.arena_registrations (song_id, creator_id, arena_date, stake_amount, status)
    VALUES (p_song_id, p_user_id, today_date, 10.00, 'pending');

    RETURN jsonb_build_object('success', true, 'remaining_balance', user_balance - 10.00, 'position', today_count + 1);
END;
$$ LANGUAGE plpgsql SECURITY DEFINER;

GRANT EXECUTE ON FUNCTION public.register_for_arena TO authenticated, service_role;


-- 4. 阶段切换 RPC (transition_arena_phase)
-- 将昨日 (或指定日期) 处于 pending 状态的报名转换为 voting 状态，准备接受今日投票
CREATE OR REPLACE FUNCTION public.transition_arena_phase(p_target_date DATE) RETURNS jsonb AS $$
DECLARE
    updated_rows INTEGER;
BEGIN
    UPDATE public.arena_registrations
    SET status = 'voting'
    WHERE arena_date = p_target_date AND status = 'pending';
    
    GET DIAGNOSTICS updated_rows = ROW_COUNT;
    
    RETURN jsonb_build_object('success', true, 'transitioned_count', updated_rows);
END;
$$ LANGUAGE plpgsql SECURITY DEFINER;

GRANT EXECUTE ON FUNCTION public.transition_arena_phase TO service_role;


-- 5. 竞技场结算 RPC (settle_arena)
-- 结算指定日期的投票结果。前10晋级退质押，余下淘汰，把淘汰总质押分给所有 distinct 投票用户
CREATE OR REPLACE FUNCTION public.settle_arena(p_target_date DATE) RETURNS jsonb AS $$
DECLARE
    rec RECORD;
    voter_rec RECORD;
    total_entries INTEGER;
    winners_count INTEGER := 0;
    losers_count INTEGER := 0;
    total_loser_stake NUMERIC := 0;
    voters_count INTEGER := 0;
    voter_reward NUMERIC := 0;
    report jsonb;
BEGIN
    -- A. 先汇总更新所有选手的 votes_count
    -- 实时根据 arena_votes 表中 up 投票数 (+1) 与 down 投票数 (-1) 统计出净得票数
    FOR rec IN 
        SELECT r.id, r.song_id, 
               COALESCE(SUM(CASE WHEN v.vote_type = 'up' THEN 1 WHEN v.vote_type = 'down' THEN -1 ELSE 0 END), 0) as net_votes
        FROM public.arena_registrations r
        LEFT JOIN public.arena_votes v ON r.song_id = v.song_id AND v.arena_date = p_target_date
        WHERE r.arena_date = p_target_date AND r.status = 'voting'
        GROUP BY r.id, r.song_id
    LOOP
        UPDATE public.arena_registrations
        SET votes_count = rec.net_votes
        WHERE id = rec.id;
    END LOOP;

    -- B. 统计当前批次的总报名人数
    SELECT COUNT(*) INTO total_entries 
    FROM public.arena_registrations 
    WHERE arena_date = p_target_date AND status = 'voting';

    IF total_entries = 0 THEN
        RETURN jsonb_build_object('success', true, 'message', '该日期无需要结算的听审竞技场批次');
    END IF;

    -- C. 晋级与退款机制
    IF total_entries <= 10 THEN
        -- 保护机制：参赛不足10首，全员晋级，全额退回质押金
        FOR rec IN 
            SELECT * FROM public.arena_registrations 
            WHERE arena_date = p_target_date AND status = 'voting'
        LOOP
            -- 更新状态为 winner
            UPDATE public.arena_registrations
            SET status = 'winner', settled_at = now()
            WHERE id = rec.id;
            
            -- 退还 10.00 ECHO 质押金
            UPDATE public.wallets
            SET balance = balance + rec.stake_amount, updated_at = now()
            WHERE user_id = rec.creator_id;

            -- 写入交易流水
            INSERT INTO public.transactions (user_id, amount, type, description, status, song_id)
            VALUES (rec.creator_id, rec.stake_amount, 'arena_refund', '听审竞技场晋级，质押金全额退回', 'settled', rec.song_id);

            winners_count := winners_count + 1;
        END LOOP;
    ELSE
        -- 参赛首数 > 10 首，按得票降序，取前10名晋级，余下淘汰
        -- 1. 前 10 名晋级退回保证金
        FOR rec IN 
            SELECT * FROM public.arena_registrations 
            WHERE arena_date = p_target_date AND status = 'voting'
            ORDER BY votes_count DESC, created_at ASC
            LIMIT 10
        LOOP
            UPDATE public.arena_registrations
            SET status = 'winner', settled_at = now()
            WHERE id = rec.id;
            
            UPDATE public.wallets
            SET balance = balance + rec.stake_amount, updated_at = now()
            WHERE user_id = rec.creator_id;

            INSERT INTO public.transactions (user_id, amount, type, description, status, song_id)
            VALUES (rec.creator_id, rec.stake_amount, 'arena_refund', '听审竞技场成功晋级前10，质押金全额退回', 'settled', rec.song_id);

            winners_count := winners_count + 1;
        END LOOP;

        -- 2. 淘汰第11名及以后的选手，收缴保证金用于分红
        FOR rec IN 
            SELECT * FROM public.arena_registrations 
            WHERE arena_date = p_target_date AND status = 'voting'
            ORDER BY votes_count DESC, created_at ASC
            OFFSET 10
        LOOP
            UPDATE public.arena_registrations
            SET status = 'loser', settled_at = now()
            WHERE id = rec.id;

            total_loser_stake := total_loser_stake + rec.stake_amount;
            losers_count := losers_count + 1;
        END LOOP;

        -- D. 分红给参与投票的所有听审员 (Distinct Users)
        -- 取得所有在 target_date 为本批次投过票的用户总数
        SELECT COUNT(DISTINCT user_id) INTO voters_count
        FROM public.arena_votes
        WHERE arena_date = p_target_date;

        IF voters_count > 0 AND total_loser_stake > 0 THEN
            voter_reward := total_loser_stake / voters_count::numeric;
            
            FOR voter_rec IN 
                SELECT DISTINCT user_id 
                FROM public.arena_votes 
                WHERE arena_date = p_target_date
            LOOP
                -- 增加听审员钱包余额
                UPDATE public.wallets
                SET balance = balance + voter_reward, updated_at = now()
                WHERE user_id = voter_rec.user_id;

                -- 写入流水记录
                INSERT INTO public.transactions (user_id, amount, type, description, status)
                VALUES (voter_rec.user_id, voter_reward, 'arena_voter_reward', '荣获听审竞技场大众听审分成奖励', 'settled');
            END LOOP;
        END IF;
    END IF;

    -- 返回结算汇总
    RETURN jsonb_build_object(
        'success', true,
        'target_date', p_target_date,
        'total_entries', total_entries,
        'winners_count', winners_count,
        'losers_count', losers_count,
        'total_loser_stake', total_loser_stake,
        'voters_count', voters_count,
        'voter_reward', voter_reward
    );
END;
$$ LANGUAGE plpgsql SECURITY DEFINER;

GRANT EXECUTE ON FUNCTION public.settle_arena TO service_role;
