-- ==========================================================
-- ECHORURA MUSICCHAIN Support Tickets Table
-- 请在 Memfire Cloud -> SQL Editor 中运行此脚本
-- ==========================================================

CREATE TABLE IF NOT EXISTS public.support_tickets (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  user_id UUID REFERENCES public.profiles(id) ON DELETE CASCADE,
  username TEXT NOT NULL,
  content TEXT NOT NULL,
  created_at TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc'::text, now()) NOT NULL
);

-- 启用 RLS
ALTER TABLE public.support_tickets ENABLE ROW LEVEL SECURITY;

-- 允许已登录用户创建工单
CREATE POLICY "Allow authenticated insert support_tickets" ON public.support_tickets
  FOR INSERT WITH CHECK (auth.uid() = user_id);

-- 允许用户查看自己的工单
CREATE POLICY "Allow user read own support_tickets" ON public.support_tickets
  FOR SELECT USING (auth.uid() = user_id);

-- 授权读取与插入
GRANT SELECT, INSERT ON public.support_tickets TO authenticated;
GRANT USAGE, SELECT ON SEQUENCE public.support_tickets_id_seq TO authenticated;
